translations/da.po
Missing translation string: http://platform.dandigbib.org/issues/635.
=> Issue #635 by cableman: Add translation string for "search content"

ding2.info, ding2.install
Ensured that redirect module is enabled by default.
See http://platform.dandigbib.org/issues/808
=> Issue #808 - Added update function to enable global redirect

themes/ddbasic/gulpfile.js
Use strict mode and add a missing `;`.
=> Fix style warnings in gulp file

.gitmodules, README.md, circle.yml
This change adds support for continuous integration using Circle CI.
This includes:
- Running drush make
- Re(building) theme assets to check for uncommitted changes
- Doing a site install
- Creating an artifact containing the code base after each build
=> Support continuous integration using Circle CI

circle.yml
The Circle image comes preinstalled with a range of dependencies. `zendframework/zend-stdlib` requires PHP 5.5 and we use 5.4 on Circle. This makes the build fail when we try to install drush.
=> Fix drush install on Circle CI

modules/ding_user/ding_user.install, modules/ding_user/ding_user.module
As a bonus, it deletes previous logged failed attempts.
=> Issue #1540 by xendk: Don't log username of failed logins.

modules/fbs/prancer/SwaggerApiRequest.php
The preauthenticated login expects a simple string in the request body,
not serialized data.
=> Issue #1393 by xendk: Fix NemID login.

.scrutinizer.yml
Currently is it easy to miss if a pull request introduces new issues. This change makes the Scrunitizer build fail which should be more visible. It is still possible to merge the pull request regardless of build failures.
=> Fail Scrutinizer build for new issues

ding2.make
Adds 2 patches to Varnish module:
http://platform.dandigbib.org/issues/1321
=> Issue #1321 by holt83: Fix "Connection reset by peer" and missing leading slash from ban URL

themes/ddbasic/scripts/ddbasic.login.js, themes/ddbasic/template.php
When user visits the login directly or clicks the login tab, the username field is set to focused.
When the user clicks the up or down key, the form is blurred (unfocused).
http://platform.dandigbib.org/issues/1267
=> Issue #1267 by bartvig: Added script that sets focus on the username in the login form, also when the Login tab is clicked.

circle.yml
They take up space and are not needed.
=> Remove node_modules from build artefacts.

.scrutinizer.yml
Generated code does not comply with our coding standards and causes the
build to fail. It is not feasible for us to fix this so we exclude it
instead.
=> Exclude generated Features code from Scrutinizer

ding2.vcl, modules/alma/lib/AlmaClient/AlmaClient.class.php
Pipe gatewayf request through varnish to ensure they are not cached.
Also set verified to TRUE in the alma self reg. call.
See http://platform.dandigbib.org/issues/659#note-31 about these corrections.
=> Issue #659: Added gatewayf to varnish VCL

circle.yml
We only need to delete the vendor folder to remove preexisting
dependencies. Deleting the entire folder causes Composer to install in
~/.config/composer and ~/.config/composer/vendor/bin is outside the
project path.
This causes subsequent calls to drush to fail.
=> Fix Drush installation on Circle CI

ding2.install, modules/alma/includes/alma.wayf.inc, modules/alma/lib/AlmaClient/AlmaClient.class.php, modules/ding_gatewayf/ding_gatewayf.module, modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.module, modules/ding_user/ding_user.module, translations/da.po
This pull request fixes a range of issues with the Gatewayf Implementation:
- The verified flag should be set to "true" instead of TRUE which is converted to 1.
- Retrieval of texts should conform to the value format of `text_format` field types
- Prevent watchdog from crashing when hash is not set
- Fix juggling of WAYF attributes during registration
- Prevent CPR, PIN and email address from being logged during self registration
=> #659: Fixes for Gatewayf

ding2.install, modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.module, translations/da.po
- Add missing translation string
- Fix typo in source string
- Remove double word (ved) in translation
Fixes http://platform.dandigbib.org/issues/659#note-65.
=> 659: Update translations

modules/ding_user/ding_user.module
This issue is caused by ask_vopros.module::ask_vopros_preprocess_html() calling field_get_items() with an array of profile2 instead of an entity (because the dummy_provider does not implement a profile).  
I have chosen to fix it in ding_user, since the profile2_load_by_user() returns an array if given  profile_type does not match and another profile is found - in this case ding_staff, and it is the responsibility of ding_user to return the profile.
=> Issue 1631: Always return an entity from ding_user_provider_profile

ding2.make
Opening hours 1.5 is no longer in beta, upgrade to the stable release.
Took the liberty of updating the patch comments.
=> 1654: Update opening_hours

modules/alma/alma.module, modules/ding_provider/connie/connie.module, modules/ding_provider/ding_provider.api.php, modules/ding_provider/ding_provider.module, modules/ding_wayf/tests/wyrna/wyrna.module, modules/fbs/fbs.module, modules/openruth/openruth.module
The current implementation is inconsistent:
1. The “file” option under “provides” are relative to the Drupal root dir
2. The root “file” option is relative to the ding_provider root dir
Part 2 results in developers with settings functions outside the .module
file have to jump through hoop to load the correct file.
Making all files paths relative to the Drupal root would require the 
smallest number of changes but that is not possible due to the way
the hook_menu() “file path” option works.
Instead we make all file paths relative to the provider root directory.
This is also the simplest going forward as all providers follow this
pattern anyway.
This change:
- Updates “file path” op ion  in the the ding_provider hook_menu
implementation for loading settings forms to be relative to the …
=> 1749: Make provider file paths relative to provider dir

modules/ting/ting.client.inc
If setting ting_cache_liftetime to zero for development, everything
breaks. Ting object pages are rendered, but the data is missing.
Somewhere someone is checking that ting_cache_get() returns '=== FALSE',
or something like that, and it happens to not return anything if the
lifetime is 0.
Simple fix.
=> Issue #1609 by xendk: Properly return false with zero cache lifetime

modules/alma/alma.module, modules/alma/lib/AlmaClient/AlmaClient.class.php
Allow the site administrator to select the security protocol to use when communicating with Alma.
See http://platform.dandigbib.org/issues/1346
=> Issue #1346: Selectable TLS/SSL version in alma

modules/ding_library/ding_library.js, modules/ding_library/ding_library.module
This is a bit hacky. I tried to disable the custom alias checkbox, but that caused path auto functionality to fail (path became node/id instead of bibliotek/name). This solution simulates a disabled checkbox with a javascript.
=> Issue 773 by Pjohans: Disable custom alias settings

modules/p2/ting_openlist/ting_openlist.module
After 1749 the fixes to the path is no longer required.
This fixes a fatal error: “require_once(profiles/ding2/modules/p2/ting_openlist/profiles/ding2/modules/p2/ting_openlist/ting_openlist.handler.inc): failed to open stream: No such file or directory”
This is required because of the change in #249.
=> 1401: Fix path to openlist provider file

modules/ting_covers_addi/ting_covers_addi.install
Addi variables are not migrated properly. This results in the following error:
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from '/moreinfo.wsdl' : failed to load external entity "/moreinfo.wsdl"
The error is caused by a faulty migration of the addi variables.
=> 1671: Fix migration of addi variables

modules/ding_frontend/ding_frontend.features.inc, modules/ding_frontend/includes/callback_user_role_filter.inc
Allow users to have more than the required roles.
Eg. staff may also have editor an still be indexed.
See http://platform.dandigbib.org/issues/430
=> Issue #430: Fixed roles match filter in search API

modules/alma/alma.features.field_base.inc, modules/openruth/openruth.features.field_base.inc, translations/da.po, translations/fields_da.po
This reverts commit 4677481355b031677e66bd40e467e1adfc21151d.
"Issue #976 by Inlead: Add support for 24 months interest period."
=> 976: Revert changes as it is superseded by 1606

ding2.make
This also means we have to reapply patches.
Upgrading Workflow has introduced a range of other problems.
Creating a News node spawns errors:
- Workflow 1 cannot be loaded. Contact your system administrator. 
Workflow 1 cannot be loaded. Contact your system administrator.
Error: content 42 has no workflow attached. The data is not saved.
PDOException: SQLSTATE23000: Integrity constraint violation: 1048 Column 'field_bpi_workflow_value' cannot be null: INSERT INTO {field_data_field_bpi_workflow} (entity_type, entity_id, revision_id, bundle, delta, language, field_bpi_workflow_value) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( …
=> 1894: Revert upgrading Workflow module to 2.7

modules/ding_dibs/ding_dibs.module
We no longer need to provide the full module path for includes.
=> 1749: Reduce path to dibs provider

modules/p2/ding_list/ding_list.module
Without this change the installation process will fail. There is no flag_content table as the flag module is not enabled.
=> 1916: Fix bookmark import when there is no flag module

modules/ding_gatewayf/ding_gatewayf.install, modules/ding_gatewayf/ding_gatewayf.module, translations/da.po
http://platform.dandigbib.org/issues/1527
Redirect unknown users logging in via WAYF to the registration page.
We avoid redirecting to the front page (as it used to be) because messages will are lost on sites that strip sessions cookies from the front page.
=> 1527: Redirect to registration page for unknown WAYF logins

ding2.make, modules/bpi/bpi.info, modules/bpi/bpi.module
This fixes http://platform.dandigbib.org/issues/2118 by making the bpi module load dependencies for the bpi-client library.
Depends on PR to the bpi-client library: https://github.com/ding2/bpi-client/pull/12
=> 2118: Fixed bpi module to use xautoload for bpi-client dependencies

modules/bpi/bpi.push.inc
In the near future a couple of new fields, url and data, will be added to the BPI web service. In order to not break running sites when these are added (the bpi client makes all fields required), we add the fields now and they will simply be ignored by the web service until it's updated.
http://platform.dandigbib.org/issues/2074
=> 2074: Added extra values to bpi data

ding2.make
This closes a security hole. The change is also included in release
2.9 but updating Features may also introduce other changes and thus
introduce risk.
=> 2305: Patch Features against SA-CONTRIB-2016-020

ding2.make, modules/bpi/bpi_features/bpi_features.field_group.inc, modules/ding_event/ding_event.field_group.inc, modules/ding_frontend/ding_frontend.field_group.inc, modules/ding_groups/ding_groups.field_group.inc, modules/ding_library/ding_library.field_group.inc, modules/ding_news/ding_news.field_group.inc, modules/ding_page/ding_page.field_group.inc, modules/ding_staff/ding_staff.field_group.inc, modules/ding_ting_frontend/ding_ting_frontend.field_group.inc, modules/ting_material_details/ting_material_details.field_group.inc, modules/ting_oembed/ting_oembed_features/ting_oembed_features.field_group.inc
This fixes a security vulnerability in 1.4.
The new version does not introduce new permissions.
The new version introduces a few additional configuration options.
One of these changes has to do with handling of additional classes. 
Consequently we update all Feature exports of field groups
accordingly. Otherwise we use the defaults.
The new version may introduce new strings.
=> 2306: Update Field Group to 1.5

ding2.make
Release 2.7 contains a security vulnerability.
There are no changes to configuration, permissions or texts between the
two version.
=> 2307: Update jQuery Update to 2.7

ding2.make
This fixes [multiple security vulnerabilities up until 3.15](https://www.drupal.org/project/views/releases?api_version%5B%5D=103).
We update to 3.16 as 3.15 has some changes which hav subsequently been
reverted to earlier behaviour. We do not want to risk updating the
system due to these changes only to have to change them back in a
subsequent update.
The new version may introduce new strings.
The new version may introduce new configuration options.
We use the defaults here.
The new version does not introduce any new permissions.
=> 2320: Update Views to 3.16

ding2.make
This fixes [a security vulnerability](https://www.drupal.org/node/2710063).
Updating also means we can drop a patch which has been merged into
the new release.
There are no new permissions or configuration changes.
The new version does have new texts in the administrative interface.
=> 2321: Update Search API to 1.18

ding2.make
This fixes a security vulnerability.
The update also means that we can drop two patches which have been
merged into the newer version.
The new version may introduce new strings.
The new version may introduce new configuration options.
We use the defaults here.
The new version does not introduce any new permissions.
=> 2324: Update Organic Groups to 2.9

ding2.make
This fixes a security vulnerability.
Updating also means we can drop a patch which has been merged into
the newer version of the module.
There are no new permissions, configuration options or texts in the
newer version.
=> 2325: Update Organic Groups Menu to 3.0

ding2.make
The current release lies between 2.0-rc4 and 2.0-rc5. Release 3.0 is
out and consequently the current version will no longer receive
security updates.
This also means we can drop a patch since it has been merged in the
newer version of the module.
There are no new tests, permissions or configuration changes in the
newer version.
=> 2328: Update Media: YouTube module to 3.0

ding2.make
Release 3.2 contains a security vulnerability.
There are no changes to configuration, permissions or texts between the
two version.
=> 2301: Update Views Bulk Operations to 3.3

ding2.make
This fixes a security vulnerability.
The new version does not introduce any configuration or permission
changes which require updates.
The new version introduces new strings but they are purely admin
facing.
=> 2317: Update metagtag to 1.21

modules/ding_campaign/plugins/content_types/campaign.inc
Don't render block content, as it'll never be empty
CTools hides the pane when empty($block->content), but an array with
an empty #markup is never empty.
Also, there's no need for drupal_render as ctools will do that for us.
=> Don't render empty campaigns 

themes/ddbasic/templates/node--ding-library.tpl.php
Temporary hack. The proper solution is to just render the field as
part of content.
=> 2414: Don't render opening_hours if not set

ding2.make
Release 1.x is no longer supported and thus does not receive security
updates.
The configuration options for the two modules are partly mirrored
between the two releases. The new one adds a few new options. We use 
the default configuration for the old module so we use the default configuration for the new one as well.
The new version does not introduce any new permissions so this part
does not require any changes.
The new version introduces new strings but they are purely admin
facing so do not require any updates.
=> 2300: Update module filter to 2.0

README.md, ding2.profile, drupal.make, modules/ding_permissions/ding_permissions.module
Drupal 7.44 has several security vulnerabilities. Updating will fix 
these.
The new version introduces a new permission “administer fields”. This
permission is only granted to administrators
Updating also means we can drop a patch as the issue it addressed was 
fixed in 7.51.
Update documentation accordingly.
The new version may introduce new strings.
The new version may introduce a few additional configuration options.
We use the defaults here.
While we are at is we also drop FTP based downloading of Drupal Core.
=> 2308: Update Drupal Core to 7.54

README.md, circle.yml, ding2.make, modules/bpi/bpi.install
The latest version of the BPI client requires PHP 5.6. We have decided
to bump the requirements for the entire platform as well.
Consequently we update our documentation and continuous integration
environment accordingly.
=> Core: Update PHP requirement to 5.6 / Ubuntu 14.04 compatability

ding2.profile
Seems that there's still some demand for the alma provider, so add it
back as an option in the installer.
=> 1625: Resurrect Alma

themes/ddbasic/sass/components/menu.scss
http://platform.dandigbib.org/issues/2540
=> 2540: Fixed. Text-align right removed for items in user-menu

ding2.make
This closes security vulnerability DRUPAL-SA-CONTRIB-2017-068.
=> 2677: Update Views to 3.17

ding2.info, ding2.make, drupal.make
Otherwise builds will include obsolete versions of the code.
=> Core: Remove version information from non-release branch

modules/ding_permissions/ding_permissions.module
Admins, editors and guest bloggers should also have access to the
media module to be able to create content with images and video.
=> 2330: Add media permissions to more roles

modules/ding_tabroll/ding_tabroll.module, modules/ding_tabroll/templates/views-view-fields--ding-tabroll.tpl.php
http://platform.dandigbib.org/issues/2439
This also corrects hook_theme() to use the correct 'base hook' instead of 'original hook'. Se the following for more info:
https://api.drupal.org/api/views/help!api-default-views.html/7.x-3.x
https://drupal.stackexchange.com/questions/25846/how-to-tell-drupal-to-look-for-templates-in-module-directory
https://www.drupal.org/node/2106635
The problem with not using 'base hook' is that we have to specify processors manually. As we can see if we take a closer look at https://api.drupal.org/api/drupal/includes%21theme.inc/function/_theme_process_registry/7.x, this locks them down and prevents other modules and themes from using variable processors on our theme suggestion.
There seems to be a lot of misinformation about this. For example the Views doc …
=> 2439: Fix dobbelt encoding in tabroll title

ding2.profile
https://platform.dandigbib.org/issues/2565
=> 2565 by Inlead: Enable ding_mobilesearch during new installations.

ding2.profile
Reverts ding2/ding2#791
Installing ding_mobilesearch as a part of the installation process breaks the installer.
=> Revert "2565 by Inlead: Enable ding_mobilesearch during new installations."

modules/ding_ddbasic/ding_ddbasic.module, modules/ting_material_details/ting_material_details.features.field_instance.inc, themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/2861
The field_group module was updated in this issue https://platform.dandigbib.org/issues/1905
After the update the field-group name was no longer printet out as a class. We have added a pre render to do this.
Furthermore a field has been removed from the teaser view-mode, and the correct class-names are used in the scss.
=> 2861: Field-group name added as class. Field removed from view-mode

themes/ddbasic/sass/components/node/library.scss
https://platform.dandigbib.org/issues/2999
=> 2999: getColumn used to avoid margin-right set to zero on last child

modules/ding_content/ding_content.features.wysiwyg.inc
https://platform.dandigbib.org/issues/2998
=> 2998: Underline removed from wysiwyg

modules/ding_carousel/ding_carousel.theme.inc, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/functions.inc, themes/ddbasic/template.php
* Fixed access callback for ajax loading ding lists in carousels
* Ensures that 0-hit search carousel don't make infinite loop in JS. 
* Fixes ratings in carousel items.
See https://platform.dandigbib.org/issues/1770
=> 1770: fixes for carousels

modules/bpi/bpi.syndicate.inc
This fixes http://platform.dandigbib.org/issues/1990.
Before this fix, the _second page_ of nodes from BPI was used to build the facets filters, but if this list of nodes was empty (when BPI ws contains very few nodes) the filters were not built.
=> 1990: Fixed query used to fetch facets

modules/fbs/includes/fbs.reservation.inc
http://platform.dandigbib.org/issues/2293
=> 2293 by Inlead: Make FBS reservation error translateable.

modules/ding_availability/ding_availability.module, modules/ding_availability/templates/ding-holdings.tpl.php
Rather than displaying "0 reservations" on non-reservables, display "Cannot be reserved".
Also removes the count column (redmine 31).
=> 1458: Add custom message when not reservable

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/3151
The bug moves the caret outside of the input fields. This makes it hard to log in, resulting in some users giving up entirely. This has only been observed on iPhones so far. I have testet on iPad and the additional screen space seems to prevent the problem.
In some situations the caret moves on top of the submit button, making it impossible to push.
See: https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8 for an illustration of the problem and more info.
Also: https://stackoverflow.com/questions/46339063/ios-11-safari-bootstrap-modal-text-area-outside-of-cursor.
I considered using user agent checking (cheking for iPhone iOS 11) on client or server side:
https://github.com/hgoebl/mobile-detect.js …
=> 3151: Fix iOS 11 modal bug

modules/alma/alma.module, modules/ding_loan/ding_loan.module, modules/ding_provider/ding_provider.debt.inc, modules/ding_reservation/ding_reservation.module, modules/ding_session_cache/ding_session_cache.module, modules/fbs/fbs.info, modules/fbs/fbs.module, modules/fbs/includes/fbs.debt.inc, modules/fbs/includes/fbs.loan.inc, modules/fbs/includes/fbs.reservation.inc, modules/fbs/includes/fbs.user.inc, modules/openruth/openruth.module
Added ding_session_cache to FBS as in the old providers. Without this FBS var called 9-12 times to show the user profile page and on every page load after login (6-9 times for logged in users to build header menu).
See https://platform.dandigbib.org/issues/3073
=> 3073: FBS session cache

docs/release_process.md
There is no reason to keep a history of commits on the release branch
hanging around. Their position in relation to the master branch is not
correct anyway.
Consequently we should amend changes to any existing release commit and
thus in practice overriding it. We already rebase the branch on the
master branch. This ensures that each release commit is only a single
commit away from master.
=> Core: Amend changes to release commits

modules/ting/ting.field.inc, modules/ting_search/includes/ting_search.admin.inc
https://platform.dandigbib.org/issues/3352
The current implementation included url decoding of generated links.
This was added to support from field values to urls containing query
parameters which are double encoded - primarily facets. This causes 
problems when the url does not contain query parameters as these links
are not double encoded.
This change introduces ? as a separator between the search string and 
query parameters. Handling is moved to a single function and 
surrounding code is cleaned up.
=> 3352: Fix author and subject links when not using facets

modules/ting_infomedia/ting_infomedia.info, modules/ting_infomedia/ting_infomedia.module
https://platform.dandigbib.org/issues/3338
The module is called ting_infomedia but requests to the infomedia
service uses the client library also used to access Opensearch.
Consequently we update the form alter for the module to target the
opensearch admininistration form.
We also solidify the dependency on Opensearch by adding the module as
a dependency for ting_infomedia. In theory it should be possible to 
decouple the two services down the line if needed.
=> 3338: Move infomedia administration fields to new opensearch form

modules/ding_provider/connie_search/includes/connie_search.search.inc, modules/ding_provider/tests/ding_provider_implementation.test, modules/opensearch/includes/opensearch.search.inc, modules/ting/src/Search/TingSearchRequest.php
https://platform.dandigbib.org/issues/3339
Fuzzy search with add wildcards characters before and after the search
string. This makes opensearch reply much slower and requests time out.
Do not use fuzzy search and instead add a trailing wildcard. This
also matches previous behavior.
Reference queries where the only place where this functionality was
used. Remove it entirely to simplify things a bit before usage and
confusion whether it should be used or not spreads.
=> 3339: Only use trailing wildcard for reference queries

modules/ting/ting.install
https://platform.dandigbib.org/issues/2685
The current codebase enables the new opensearch module as the default
search provider on new sites during installation. However nothing is
done to ensure that a search provider is active on existing sites.
Consequently we implement an update hook which enables the opensearch
module if no other search provider is active.
=> 2685: Enable opensearch module as search provider on existing sites

modules/opensearch/includes/opensearch.search.inc
https://platform.dandigbib.org/issues/3346
Current handling of relations for OpenSearch does not check sufficiently 
for valid objects before calling methods on them. This causes fatal 
errors.
This change adds more checks for proper - not-NULL - values before
calling methods. This also allows the relation code to use more of the
proper class methods instead of relying on DingEntity magic.
=> 3346: Prevent method on non-object fatal errors for relations

modules/opensearch/includes/opensearch.search.inc, modules/opensearch/opensearch.client.inc, modules/ting/ting.controllers.inc
https://platform.dandigbib.org/issues/3356
This prevents fatal errors opensearch_get_object can return multiple
types including NULL. OpenSearchTingObjectCollection only accepts a
TingClientObjectCollection.
Returning NULL from the search provider collection_load method should
not cause problems. Callers already check for empty results.
Update DocBlocks accordingly.
=> 3356: Return null if OpenSearch cannot retrieve collection for id

docs/provider_integrations.md
https://platform.dandigbib.org/issues/3272
This is an attempt at providing documentation for the provider integration and list requirements for library systems and search systems in case new providers have to be evaluated in regard to compliance with Ding2.
Note that some of the documentation assumes that the search abstraction layer in #982 is merged.
=> 3272: Provider intergration docs

modules/ding_provider/connie_search/src/ConnieTingObjectCollection.php
An invalid property will always be empty.
This should also fix the tests.
=> 2685: Fix retrieval of primary object for collection in Connie

modules/opensearch/src/OpenSearchTingObject.php
[Relations for the object will only be set if they can be retrieved](https://github.com/ding2/ding2/compare/master...reload:feature/3346-fix-relation-notice?expand=1#diff-cd656e119bf1220b60ff65335fffe0feL69).
Consequently we have to initialize the property to an empty array to
avoid returning NULL if relations cannot be retrieved.
=> 3346: Initialize OpenSearch relations to empty list

modules/ting/ting.field.inc
https://platform.dandigbib.org/issues/3352
preg_split will only return a single entry causing list to issue a
notice.
=> 3352: Fix notice when search string does not contain query

modules/opensearch/opensearch.admin.inc
https://platform.dandigbib.org/issues/3380
Use `system_settings_form()` for OpenSearch Autocomplete configuration to add a save button and support updating of configuration.
We also have to remove a fieldset wrapper around the configuration form to ensure that variables are set with the expected names. From a UI perspective the wrapper was not needed anyway.
=> 3380: Fix opensearch autocomplete settings

modules/opensearch/opensearch.module, modules/ting/ting.module
The current detection of periodicals based on types is not suitable
across search providers which may use different languages.
The current values are tied to OpenSearch and the Danish municipal 
libraries. Consequently we move the detection to the opensearch module.
=> 3325: Move periodical detection to search system

modules/bpi/bpi.module, modules/ding_ekurser/ding_ekurser.module, modules/ding_provider/connie_search/includes/connie_search.search.inc, modules/ding_provider/tests/ding_provider_implementation.test, modules/opensearch/includes/opensearch.search.inc, modules/p2/ding_entity_rating/ding_entity_rating.serendipity.inc, modules/p2/ding_message/ding_message.module, modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity_fallback/ding_serendipity_fallback.module, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module, modules/p2/ding_serendipity_taxonomy_term/ding_serendipity_taxonomy_term.module, modules/p2/ding_serendipity_ting_entity/ding_serendipity_ting_entity.module, modules/ting/src/Search/TingSearchRequest.php, modules/ting_new_materials/ting_new_materials.module, modules/ting_reference/ting_reference.module, modules/ting_search/plugins/content_types/search_backends.inc, modules/ting_search/tests/ting_search_unit.test, modules/ting_search/ting_search.module, modules/ting_search_carousel/ting_search_carousel.module
https://platform.dandigbib.org/issues/3408
This change ensure that a new search object is generated and passed
along each time it is changed. This way we avoid unintentional changes
to existing search requests when we reuse an object to generate a new
search.
This is an alternate approach to the issue being tackled in #1056. This makes cloning and additional arguments unnecessary.
The approach taken using `withX` instead of `setX` is inspired by the [PSR-7 implementation](https://www.php-fig.org/psr/psr-7/) where messages are also immutable. [See the Guzzle implementation for example code](https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php#L245).
=> 3408: Make search requests immutable

drupal.make
This protects against the SA-CORE-2018-002 security vulnerability.
https://www.drupal.org/sa-core-2018-002
=> 3432: Update Drupal Core to 7.58

drupal.make
Issue: https://platform.dandigbib.org/issues/3486
This protects against the SA-CORE-2018-004 security vulnerability.
https://www.drupal.org/sa-core-2018-004
=> 3486: Update Drupal Core to 7.59

ding2.profile, modules/opensearch/opensearch.module
https://platform.dandigbib.org/issues/3534
We try to set some defaults for opensearch and moreinfo service during install. Appearently this wasn't happening because of some typos.
I tested that it works with drush site-install and manual install via browser.
Just can't find a reason why these are not just placed on the form itself, but I have not changed it.
=> 3534: Fix default values during install

modules/fbs/includes/fbs.reservation.inc
When using NemID to create a new library user the profile don't exists. So when trying to get default interest periode and this is the process the periode should use the default value.
See https://platform.dandigbib.org/issues/3537
=> 3537: Added check that profile exists for interest period

modules/opensearch/opensearch.client.inc, modules/ting_fulltext/ting_fulltext.module
When switching to datawell 5.0 the agency is required to make search and the format is obsolete.
See https://platform.dandigbib.org/issues/3388
=> 3388: Added agency to fulltext request

ding2.install
https://platform.dandigbib.org/issues/3572
Previous changes were made to an update hook which has already been
run on production and thus did not have any effect. Consequently we
rerun the hook.
=> 3572: Enable ding_app_variables on existing Opensearch sites

modules/p2/ding_serendipity/ding_serendipity.module
This error prevented login as the $query object in variables when syslog module enabled was sendt to strstr() which then makes php crash.
See https://platform.dandigbib.org/issues/3607
=> 3607: Removed watchdog logging of empty searches

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_provider/ding_provider.loan.inc, modules/fbs/includes/fbs.loan.inc, themes/ddbasic/sass/components/ting-object/material-item.scss
https://platform.dandigbib.org/issues/3191
In this PR I try to provide some better renewal feedback on the loan list.
renewalStatus is returned from FBS API in two cases:
1. When a loan is renewed
2. When a patrons loans is fetched
Until now we have only used the renewalStatus for feedback when the patron renews a loan.
With the changes in this PR the renewalStatus will also be used to provide useful information when the user is viewing the loan list. More information about what exactly is shown on redmine (https://platform.dandigbib.org/issues/3191#note-40).
As we don't have any information about the "renewal-history" of the materials, I have also used the ding_session_cache to remember which loans was renewed in the current session. This should fix the confusing "The material can not be …
=> 3191: better renewal feedback

modules/ting_search/plugins/content_types/search_result.inc
When SAL was introduced into core the hooks need to sub-search modules was removed.
This re-introduce the hooks.
Used by: "Mente du" and "Maskinebare oversættelser"
See https://platform.dandigbib.org/issues/3600
=> 3600: Re-add search message prefix/suffix hooks

modules/ting_covers/js/ting-covers.js
Missing ] seems to only trip up Safari on iOS.
=> Fix cover loading for iOS devices

modules/bpi/bpi.install
I missed this one in the last in the PR.
As a result the admin_views node view isn't activated on fresh installs.
https://platform.dandigbib.org/issues/2193
=> 2193: Don't disable admin_views node view on BPI install

modules/ding_user/ding_user.module
This happens when disabling all providers, which is a trick used when switching to the new FBS system.
=> 420: Catch no provider exception during login

modules/ting_covers/ting_covers_placeholder/ting_covers_placeholder.info, modules/ting_covers/ting_covers_placeholder/ting_covers_placeholder.install, modules/ting_covers/ting_covers_placeholder/ting_covers_placeholder.module
https://platform.dandigbib.org/issues/3385
This module will generate placeholder images for all Ting entities using
the placeholder.com service. This is useful for development and testing
purposed since some functionality such as carousels depend on covers
being available. Few objects in the test services have proper covers.
Placeholder.com is used as it provides needed features like specifying
image dimensions, colors and text. It also seems to be a stable service
in an area where services might get shut down quickly. For example it
has a company backing it - not a private person.
The module is placed under the ting_covers module as it also provides
a reference implementation of a module which provides covers.
=> 3385: Implement covers module using placeholder.com

modules/ding_ipe_filter/ding_ipe_filter.module
If the provided category argument is included in the available
categories we should not check for panes. Doing this will result in
notices and warnings
=> 3192: Prevent notices for invalid categories

modules/opensearch/opensearch.client.inc
The detection of the format for response from the datawell has changed to be objectFormat from format, which did break the fulltext module.
See https://platform.dandigbib.org/issues/3388
=> 3388: Changed fulltext XML check from format to objectFormat

modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/3727
Webtrekk was failing to track well search. Needs a little update after SAL.
After testing https://silkeborgbib.dk/search/node/test it looks like the node search is tracking properly.
=> 3727: Make webtrekk SAL compatible

modules/ding_user/ding_user.install, modules/ding_user/plugins/access/external_user.inc
Instead of relying on init on user table and authname on authmap to be equal, this change just verifies
that the user is externally authenticated by ding_user instead. 
This should be more robust, since there has been cases where init and authname for some reason wasn't  synchronized properly.
More info the description: https://platform.dandigbib.org/issues/3069
=> 3069: Refactor ding_user external access plugin

modules/ding_user/ding_user.module
Fixes an error where global variable $user is
not assigned to $account if no arguments where
provided.
=> 3745: Fix misspelling of $account

modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/3827
Predict cache function do not handle empty collections do to data-well errors
=> 3827: Error handling in predict cache

modules/ding_loan/plugins/content_types/loans.inc, modules/fbs/includes/fbs.loan.inc
https://platform.dandigbib.org/issues/3191
There was some problems with the renewal_status check logic:
1. I assumed that we should only show feedback when the material wasn't renewable. But some libraries doesn't have any restrictions on when you can renew, so materials will be renewable right after they have been renewed. In these cases the information about "The material was renewed", "The material was borrowed today", etc. is still useful.
2. It make more sense to show "The material was renewed" message first, since it's better feedback than "Material was borrowed today. So I changed the order of some checks.
It gets a bit complicated and I have tried to provide some good comments in the code.
=> 3191: Fix order of renewal_status checks

modules/ting_covers/ting_covers.module
Fixes an undefined function error if a local file path is encountered, and makes a copy for the cache instead of a move in order to not delete managed/unmanaged files that have other dependencies.
=> 3742: BUGFIX: Cache local files by creating a copy into the covers cache.

ding2.install, ding2.make, ding2.profile, modules/ding_base/ding_base.module, patches/customerror-disable_auto_redirect.ding2.patch
https://platform.dandigbib.org/issues/3841
We use the customerror module to show special pages for 403 og 404. If an anonymous user tries to visit any page without permission, the module will try to redirect to this page, if the user logs in later. In our setup, this has some unfortunate effects:
1. Since we use AJAX in our log in process, the redirect is never triggered when the user logs in, but rather on a subsequent form submission. This can be very confusing, if the user is redirected to a seemingly unrelated page after, for example, renewing a loan.
2. The session variable will cause a session cookie to be saved in the user's browser and following requests will circumvent our Varnish cache.
3. When this error manifests it will, appearently, often be because of an AJAX-request that …
=> 3841: Disable customerror redirect

Makefile, README.md, drupal.make, patches/drupal_core.robots.txt.ding2.patch
https://platform.dandigbib.org/issues/2158
Had a lot of issues with the Makefile, since it needs tabs to separate lines. My editor is set to use spaces when working with ding2 and Drupal in general.
And sublime text was not helping. Had to use this plugin: https://packagecontrol.io/packages/TabNukerNuker 
Anyway, I think I got those tabs inserted after some hard work hehe :)
I was wondering: Are there any particular reason why we use a MakeFile for circleci? I can't seem to find any documentation about that.
=> 2158: Add core patch to disallow gatewayf in robots

modules/fbs/fbs.field.inc, modules/fbs/fbs.module
Adds new validation of "on hold" dates in the FBS provider users profile.
This PR also reverts the other PR's already merged into Core for the issue
=> 3043: Validation of "on hold" date in FBS provider profile

modules/ding_event/ding_event.features.field_instance.inc
https://platform.dandigbib.org/issues/3829
=> 3829 by Inlead: Make Event Target vocabulary mandatory.

modules/ding_ekurser/ding_ekurser.module
And also ensure the search query is using facet.subject.
https://platform.dandigbib.org/issues/3703
Regarding simplification of facet.subject terms extraction. As mentioned in commit message:
As documented in \Ting\Search\TingSearchResultInterface, the getFacets() method returns a list of facets keyed by facet name. Hence there can only be one entry for the facet with name facet.subject and there's no need to do any filtering. 
This simplification also fixes the fatal PHP error, since it remove the need to use the splat-operator (which where failing before because of associative array)
=> 3703: Fix fatal php error when viewing /ekurser.

modules/ding_varnish/ding_varnish.module
https://platform.dandigbib.org/issues/3696
Some libraries was experiencing spam on the contact-form, which was already honeypot enabled.
I discovered that honeypot was trying to mark page as non-cacheable, but because of the logic in ding_varnish module this wasn't respected.
I have testet with Varnish that the contact-form isn't cached anymore with the changes in this PR.
=> 3696: Check drupal_page_is_cacheable() for anonymous users

modules/ding_adhl_frontend/templates/ding_adhl_frontend_recommendation_list_entry.tpl.php, modules/ding_campaign/ding_campaign.module, modules/ding_event/ding_event.views_default.inc, modules/ding_gatewayf/ding_gatewayf.module, modules/ding_news/ding_news.views_default.inc, modules/ding_provider/connie_search/src/ConnieSearchResult.php, modules/ting/src/Search/TingSearchFacet.php, modules/ting/src/Search/TingSearchResultInterface.php, translations/da.po
https://platform.dandigbib.org/issues/3898
Multiple places within the sourcecode there is misspellings of "were found", which is given as "where found". Some places are strings that are actually presented/displayed to the user.
=> 3898 by Inlead: Fix misspellings.

.circleci/config.yml, README.md
https://platform.dandigbib.org/issues/3875
This PR depends on #1205. Key commit is f640cfc.
This is orchestrated by CircleCI.
A database Docker images will allow developers to spin up a site without
going through the installation process which can be slow and tedious.
The image is based on MySQL 5.7.23 as that is the closest version to 
what we are using for the rest of our CI process.
The image gets the database dump from the workspace copied into a 
specific folder which the database image is configured to load SQL
files from on startup.
To provide a stable starting point we set a fixed username and password.
The Dockerfile is not included in the project as we are not providing a
Full Docker setup at this point in time. Instead we generate it during
the build.
Once the image is built it …
=> 3875: Create database docker image as a part of build

themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/templates/node/node--ding-event--view-mode--teaser.tpl.php
https://platform.dandigbib.org/issues/3861
New method used for sizing image on event teasers. This ensures the image format is the same on all screen sizes.
No comments
=> 3861: Responsive image format on event teasers

modules/ting_field_search/ting_field_search.ting_field_search_default_profiles.inc
Zinio has changed name to rbdigital.
https://platform.dandigbib.org/issues/3682
=> 3682: Update periodical search profile

ding2.make, modules/ding_content/ding_content.features.wysiwyg.inc
https://platform.dandigbib.org/issues/3473
Security update of ckeditor library: https://www.drupal.org/sa-core-2018-003 
I had to update the wysiwyg module also. Refer to this editor support matrix: https://www.drupal.org/docs/7/modules/wysiwyg/supported-editors-matrix 
I also did re-export of our Wysiwyg profile config after running the updates from the updated wysiwyg-module.
The version we used before was from may 2015 (ref: 7981731f4f3db2f932419499d2ec13a073e9b88f), There's a lot of changes from 2.2 to 2.5. Looks like editor preferences is separated from profile settings and editor version is now exported in features.
The available options appear to be largely the same, apart from a view additions to the paste plugin (I have informed about this in the case) and that now you can set …
=> 3473 update ckeditor

.circleci/config.yml
https://platform.dandigbib.org/issues/3012
CircleCI has an odd way of handling jobs which are both filtered by tags
and requiring other jobs. In these cases all precursors must also be
filtered by tags for the job to run.
-> https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681/5
This lead to the workflow for the latest release 7.x-4.6.0-rc1 looking like this. A tagged Docker image was not created and the release was not published. 
This is hard to handle so instead of requiring tags we require the
release branch (which usually contain our tags) and only publish 
releases if a tag for the commit can be determined.
After the change the workflow for a `release` branch should look like [this](https://circleci.com/workflow-run/5227900a-dae0-415f-9adc-5c530810b663):
Resulting …
=> 3012: Do not depend on tags for CircleCI releases and Docker images

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module, modules/ding_ipe_filter/js/ding_ipe_filter.js
https://platform.dandigbib.org/issues/3269
Added ting carousel back into the IPE menu options, so localadmins can insert it on the frontpage when using IPE. 
Furthermore did som small improvements to the display of the menu and its affects.
=> 3269 by Inlead: Add ting carousel to list of IPE menu options.

.circleci/config.yml
None - Core issue.
Currently our builds fail on CircleCI when installing additional extensions with the error: `/usr/local/bin/docker-php-ext-enable: 108: /usr/local/bin/docker-php-ext-enable: cannot create /conf.d/docker-php-ext-gd.ini: Directory nonexistent`
This is caused by a change in the underlying PHP image - see also docker-library/php#750.
This change applies the suggested fix and furthermore improves our use of the `PHP_INI_DIR` environment variable which is the source of the issue.
=> Core: Fix builds of PHP images on CircleCI

modules/ding_availability/ding_availability.field.inc
Before the search abstraction layer was introduced [the `getOnline_url()`
method accepted a boolean to determine whether to retrieve relations
for fetching online urls for an object or not](https://github.com/ding2/ding2/blob/7.x-4.2.1/modules/ting/ting.entities.inc#L289-L333). [The availability field 
Formatter was the only element which used this functionality](https://github.com/ding2/ding2/blob/7.x-4.2.1/modules/ding_availability/ding_availability.field.inc#L227) to prevent 
relations from being fetched when determining whether a material was 
online or not.
When the search abstraction layer was introduced a new method for
determining if an object is online without fetching relations was 
introduced: …
=> 3905: Do not retrieve online urls to determine if object is online

modules/opensearch/opensearch.client.inc
This PR is based on the work from #1269. Only the last three commits should be considered.
OpenSearch supports retrieving many objects in a single request by
passing multiple ids.
This results in a unique request for all these ids and thus a unique
cache entry despite the fact that information for some or all of these
objects may already be cached based on individual requests.
Consequently we update our cache handling to split all object requests 
into multiple single id object requests, check each request for a
cached version and if found merge these cached responses into the
combined response.
To facilitate this cache handling is moved to single function combining
retrieval and insertion as well as static and persistent caching.
We also cache …
=> 3905: Cache multiple objects per collection

modules/ting_covers/ting_covers.module, modules/ting_covers_addi/lib/addi-client/AdditionalInformation.php, modules/ting_covers_addi/lib/addi-client/AdditionalInformationService.php, modules/ting_covers_addi/ting_covers_addi.admin.inc, modules/ting_covers_addi/ting_covers_addi.module
https://platform.dandigbib.org/issues/3892
In some cases moreinfo supplies an external reference to a cover. In this PR I implement the usage of this and related settings.
There's a lot more info in the case.
Ereolen global search without externURL:
Ereolen global search with externURL:
=> 3892: Use moreinfo externURL

modules/ding_base/ding_base.module, modules/ding_base/js/ding_base.prevent_auto_submit.js
https://platform.dandigbib.org/issues/3816
As it was requested, was added possibility to filter nodes on /content page by taxonomy terms. The taxonomy term filtration depends on selected taxonomy vocabulary filter from the same form.
New filter is realized as a textfield which will be in disabled state until taxonomy vocabulary filter is not selected. If an taxonomy vocabulary is selected, terms filter changes it's state to active and autocomplete functionality is added.
Regarding opportunity to assign taxonomies through bulk update, this is already realized in VBO actions and can be done with "Change value" action.
=> 3816 by Inlead: Filter by taxonomy in /content.

modules/ding_ekurser/ding_ekurser.info, modules/ding_ekurser/ding_ekurser.module
https://platform.dandigbib.org/issues/3703
Opensearch is using date field for sorting, but ding_ekurser was using acquisitionDate. Before the introduction of SAL this was no problem, but now Ting search has to verify that the provider supports the current sort. Since opensearch is not returning acquisitionDate it's ignored bothwhen performing search and setting default value.
date = The date the material was published.
acquisitionDate = The date the material was added to the library.
Even though the Opensearch webservice is supporting acquisitionDate (and also localAcquisitionDate), the simplest and best solution seems to be just make ding_ekurser use date field for sort. I think it's the most intuitive sort and it prevents us from having to introduce acquisitionDate in the main search …
=> 3703: Fix ekurser date sort

modules/ding_campaign_plus/modules/ding_campaign_plus_basic/ding_campaign_plus_basic.module
https://platform.dandigbib.org/issues/3930
Add a simple search term match trigger to campaign plus to trigger simple searches as "Åbningstider". 
No comments.
=> 3930: Added search term match as basic campaign trigger

ding2.info, ding2.install
https://platform.dandigbib.org/issues/3914
Enables campaign plus as default.
No screenshot
No comments
=> 3914: Enable campaign plus as default

modules/ting_field_search/plugins/ting_field_search_ctools_export_ui.inc, modules/ting_field_search/ting_field_search.module, modules/ting_field_search/ting_field_search.ting_field_search_default_profiles.inc, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/3908 
There was an option to allow for "empty searches" on profiles, but it stopped working because the '()' was, rightfully, removed from the query when there was no keywords entered in the UI.
I fixed this and decided to remove the option, such that it's always possible to search without keywords when using a profile. I think it makes really good sense to allow searching without keywords, when the user already have selected a profile. And I couldn't come up with any good reasons to why you would not want that functionality on a search profile.
=> 3908: Allow searching without keywords when using profile

modules/ding_permissions/ding_permissions.module, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc, modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/include/menu_callbacks.inc, modules/p2/ding_list/plugins/content_types/list_menu.inc
https://platform.dandigbib.org/issues/3830
Allow admins to hide user lists from public lists
=> 3830: Remove list from public lists

modules/opensearch/includes/opensearch.search.inc, modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/3828
Related PR: https://github.com/ding2/ting-client/pull/25
We used a special 'manifestation' search request to translate fausts to pids, but this was interfering with caching of collections, such that the manifestation would be cached as single object collections. This would result in material types getting "hidden" from users in the UI, because of these incomplete collections.
Switching to getObject request instead of search will fix this (in situations where the translation is the culprit) and is also a better solution in my opinion. 
There might still be problems with incomplete collection in other places, but this is out of scope of this PR.
Also fixes issue with get_objects, when over 169 objects are requested. See this comment for more info …
=> 3828: workmatch memory

modules/ting_reference/ting_reference.module
https://platform.dandigbib.org/issues/3923
ting_reference default formatter attached js even when the field was empty, that causes the field to be rendered. Now the js is only attached if the field has content.
=> 3923: Fixed Ding news render empty materials ref

modules/ding_ddbasic/ding_ddbasic.module
https://platform.dandigbib.org/issues/3893
Add and enable the expanded checkbox to the menu settings part of a node form.
=> 3893: Add and enable expanded to node menu settings

modules/ding_tabroll/ding_tabroll.module
https://platform.dandigbib.org/issues/3822
Move tabroll pane items switching speed configuration from deprecated ding_frontend settings form into pane's settings form.
=> 3822 by Inlead: Changes to tabroll settings in new version.

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3296
Initial implementation (https://github.com/ding2/ding2/pull/1009) was made by checking whether sales status was open and amount of tickets is 0:
```
if ($p2b_result->headers['sales-status'] == 'open' && (int) $p2b_result->headers['available-tickets'] == 0) {
$type = 'order-waiting-list';
$url = $p2b_result->headers['location'];
}
```
However this is not what defines whether an event is with a waiting list or not. This is defined in the properties of the event in the external system, and the event gets a header called "`waiting-list`".
This value can be true even if the event is paused, stopped or open for sales. Therefore the check in this change-set is duplicated. Code is convoluted and refactoring is not a part of this task.
=> 3296 by Inlead: Refactored waiting list state.

README.md, drupal.make, modules/bpi/bpi.module
https://platform.dandigbib.org/issues/2608
Set proper menu item types, since when missing, item types defaults to `MENU_NORMAL_ITEM`. This makes the menu items visible.
On top of that, patch to drupal core is required for this to work - https://www.drupal.org/project/drupal/issues/1079628
This change-set itself doesn't solve the issue, a patch to Drupal core is required which is provided above. In short - drupal cache clear doesn't cleanup the `menu_links` table when changing menu item type to `MENU_CALLBACK`. This results in menu items that became route callbacks to be still rendered as normal menu items.
=> 2608 by Inlead: Set proper menu item types.

modules/bpi/bpi_features/bpi_features.features.field_base.inc, modules/bpi/bpi_features/bpi_features.features.field_instance.inc
https://platform.dandigbib.org/issues/3640
Hide the field via features. Revert of `bpi_features` is needed to accomplish the task.
=> 3640 by Inlead: Hide comment workflow field.

themes/ddbasic/sass/base/standard.scss
https://platform.dandigbib.org/issues/3702
Changed the position of ul from inside to outside and added needed padding.
=> 3702 by Inlead: Fix ul position.

modules/bpi/bpi.install, modules/bpi/bpi.module, modules/bpi/bpi_features/bpi_features.features.field_base.inc, modules/bpi/bpi_features/bpi_features.features.inc, modules/bpi/bpi_features/bpi_features.rules_defaults.inc, translations/da.po
https://platform.dandigbib.org/issues/3643
Disable the 'Pre-sending to BPI' status. Also migrate content that might have this status to 'Local content' status instead.
Removing the `Pre-sending to BPI` workflow state, as a result, also introduced the fact that upon new node creation the `Save and push` button is also removed. This button was linked to a Rule definition that redirected the user to the workflow page of lately created node, which is removed as well in this PR.
Overall, taking into consideration that original issue stated that this workflow status is redundant and confuses users, removal of it also brought some UX changes as well. These, however, might not fit the general requirement in the final result.
=> 3643 by Inlead: Disable the 'Pre-sending to BPI' status and update translations.

modules/bpi/bpi.module, modules/bpi/bpi.push.inc, modules/bpi/bpi.rules.inc
https://platform.dandigbib.org/issues/3639
Simply remove the authorship checkbox and push all content with FALSE authorship value.
This change will display the authorship in backend (when syndicating) and not in frontend (after syndication). Normally authorship would appear as a suffix to the body value, which is not the case now.
For existing nodes that were pushed with authorship flag enabled, this also involves service changes to make sure no authoring information is appended to the content.
=> 3639 by Inlead: Remove authorship checkbox.

modules/opensearch/opensearch.client.inc
If it is not then we risk passing NULL to array_key_exists(). This
will issue a warning.
=> 3905: Ensure static OpenSearch cache is always initialized

modules/ding_base/ding_base.install
We have previously updated the site default version of jQuery to
Use via JQuery Update to 3.1. The module has previously been used
to update the site to 1.7.2 and use the same version for the admin
theme.
However the migration path for the updated version of jQuery Update will
set the version to use for the admin theme to Drupal default (1.4) if no
specific version has been set.
This causes JavaScript to break as some of our code relies on updated
versions of jQuery and calls functions which are not defined in 1.4.
To fix this we run an update hook which configures the admin theme to
use the default version set by jQuery Update (3.1).
It is important that this update hook runs after jQuery Updates own
update hooks which will set the version to …
=> 3603: Use updated jQuery version on admin theme

ding2.install, ding2.profile, modules/ding_campaign_plus/ding_campaign_plus.install
See https://platform.dandigbib.org/issues/3914
Enabled all campaign plus "extra" modules but only with soft dependency, so libraries that don't want theme can disable theme again.
No screenshot.
No comments.
=> 3914: Enable all campaign plus modules

modules/ding_campaign_plus/modules/ding_campaign_plus_auto/ding_campaign_plus_auto.module
See https://platform.dandigbib.org/issues/3977
Default configuration was missing from auto generated campaigns. So when no configuration existed in the database. This would trigger an error on campaign node insert.
No screenshot.
No comments.
=> 3977: Ensured config exists for auto campaigns

modules/ding_news/ding_news.views_default.inc
https://platform.dandigbib.org/issues/3922
The news-list now aggregates results to remove duplicates when a news node is related to more than one library group. Also the filter criteria that a node needs a library-group relationship has been removed, to allow news to be shown that is not connected to any specific library.
=> 3922: Aggregates news-list view results and removes group criteria

modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/3828
Issue 3828 (#1261) introduced the possibility for requesting OpenSearch objects 
by local id (Faust) as well as object id (PID). In parallel the cache 
handling was updated with #1271 
. The two changes did not take each other into
account.
This resulted in situations for local id requests without object ids 
where types were mismanaged causing fatal type errors.
To handle the situation better this change does two things:
1. Cache objects in responses by local id as well as object id.
2. Try to retrieve objects for the cache by local id (if defined) as
well as object id (if defined)
To ensure that the change integrity I have tested that doing a search only results in a single request to OpenSearch and …
=> 3905: Cache objects by local id as well as id

modules/ding_base/ding_base.install
The latest version of jQuery causes problems for the Module Filter
module: https://www.drupal.org/project/module_filter/issues/2986511
There is no immediate fix for this and the problem which originally
caused the upgrade is only relevant for patron actions performed in the 
DDBasic theme.
Consequently we downgrade the version of jQuery used to 1.7 (in practice
1.7.2) which is the same version currently used.
We need to ensure that the correct version is set on current and new
sites so we implement both hook_update and update hook_install to
make this change.
Current version for new sites is actually 1.4 because the previous version only included a hook_update:
When updating the site to 3.1.1 for the admin theme the module filter breaks: …
=> 3603: Downgrade jQuery to 1.7 for the administration interface/theme

ding2.make
The latest version of the localization client module is ~5 years old
and has problems with newer versions of jQuery because $.browser has
been removed.
We patch the module to fix the problem. The chosen patch has also been
committed by the module maintainer.
Faulty site:
=> 3603: Patch localization client to support newer jQuery versions

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/3919
Hides library, locality_block and street_block from ding_event teaser, when no place room is entered.
=> 3919: Changed event_teaser location markup

modules/bpi/bpi.module, modules/bpi/bpi.push.inc, modules/bpi/bpi.rules.inc, modules/bpi/translations/da.po, translations/da.po
https://platform.dandigbib.org/issues/3638
Replace checkbox with a dropdown with image pushing options prior to node push towards BPI.
=> 3638 by Inlead: Push with images option as dropdown.

themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/3910
Text color changed on ting teasers with disabled overlay. Redundant css removed.
No further comments.
=> 3910: Change text color. Remove redundant css

modules/ding_carousel/js/ding_carousel.js, modules/ting_search_carousel/plugins/content_types/carousel.inc, modules/ting_search_carousel/ting_search_carousel.module
https://platform.dandigbib.org/issues/1353
Adds option to filter carousel materials down to available items.
It's done in the ajax callback, using provider availability data, in order to not have to deal with ting caching.
Requires https://github.com/ding2/ding2/pull/1235
=> 1353 carousel availability

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_webtrekk/ding_webtrekk.js, modules/ding_webtrekk/ding_webtrekk.module, modules/ting/ting.module
https://platform.dandigbib.org/issues/3901
In this PR the tracking capabilities of ding_webtrekk is extended to include several new Most Wanted Actions (MWAs) like reservation, rating, carousel click etc. The implementation follows the guidelines for parameter names and values from following spreadsheet, which also lists all the tracking that is added in this PR (those marked with "Skal implementeres"):
[Webtrekk 20171128 - MWA list](https://docs.google.com/spreadsheets/d/1OdUWGQc_hiY8F6BPViKRrBykSQfHLnhv4-YMdUzswSI/edit#gid=0)
With Webtrekk we have three methods of tracking:
**Page parameters**
These are used for information about the page that are known at load time and are only related to that page. For example what is the type of the material being shown or what sort was used on the …
=> 3901: Webtrekk MWA traking

modules/ding_libs/ding_libs.module
As a part of #1243 we now download js.cookie 2.20 for jQuery 3 compatibility.
We have to update the library definition accordingly for the library to
get loaded properly.
The Scrutinizer error is irrelevant to the change at hand and should be disregarded.
=> 3603: Update definition of js.cookie library

ding2.make
The version of jQuery that we use can have significant impact on the
functionality of the site and break other JavaScript elements.
Consequently normal users should not be able to change this.
To address this we patch jQuery Update to add a new permission which is
used to determine access to functionality provided by jQuery Update.
The new permission is intentionally not assigned to any roles. This
prevents access to everyone except user 1.
I do not know why Scrutinizer fails for this PR. It is not related to the change at hand.
=> 3603: Prevent access to changing jQuery version

modules/ding_carousel/js/ding_carousel.js, modules/p2/ding_list/plugins/content_types/public_lists.inc
https://platform.dandigbib.org/issues/3985
Instead of removing the .placeholder in the slick slide, it now makes sure to remove the entire .sick-slide, if the placeholder is nested inside (it also removes the .slick-slide if the placeholder is not nested).
=> 3985: Remove .slick-slide placeholder

themes/ddbasic/sass/base/standard.scss, themes/ddbasic/sass/components/header.scss
https://github.com/ding2/ding2/pull/1167
After introducing https://github.com/ding2/ding2/pull/1167, the tests showed that the searchbar disappeared on non-frontpage/non-search-page pages.
It seems to be caused by legacy code, which is no longer relevant.
This PR is mostly cleanup.
I've tested it throughly and it seems to work as intended now.
=> 3667: Make sure extended search is displayed on all pages.

modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/1261
The current usage of $form and $form_state seems to have been
mixed up in two instances. This results in a 500 error response when
logging in with invalid credentials:
“TypeError: Argument 2 passed to drupal_array_set_nested_value() must
be of the type array, null given”
Switch them around to fix this.
The error:
The Scrutinizer error is irrelevant to the change at hand.
=> 1261: Fix errors for invalid logins

modules/ding_dummy_provider/ding_dummy_provider.user.inc, modules/ding_provider/connie/connie.user.inc, modules/ding_user/ding_user.module, modules/fbs/includes/fbs.user.inc, modules/openruth/includes/openruth.user.inc
https://platform.dandigbib.org/issues/1261
https://platform.dandigbib.org/issues/1491
Changing passwords suffer from a number of issues due to recent changes:
1. 0fac6ea Authentication failures now throw exceptions. This change was not handled by the password changing code which performs authentication with existing password before updating to a new one. This results in an uncaught exception. Catch this and handle it appropriately.
2. 6a997ab Exception throwing was not implemented for all providers. It is now.
3. 0409675 We did not pass the library card number to the password updating process when using FBS. This causes the updating process to always fail. We now pass the library card number. **NB: Please check the commit message for this change**
4. 7294668 Password validation always ran …
=> 1261+1491: Fix password changing

modules/bpi/bpi.syndicate.inc
https://platform.dandigbib.org/issues/153
Simply hide the `Syndicate` link in the result set for the content that has the same agency as the current bpi setup.
=> 153 by Inlead: Disable ability to syndicate own content.

modules/ding_campaign_plus/modules/ding_campaign_plus_auto/ding_campaign_plus_auto.module
https://platform.dandigbib.org/issues/3984
Remove leading slash from auto generated campaign plus node links.
No screenshot
The Scrutinizer error is in code not related to this PR.
=> 3984: Removed leading slash from node link

themes/ddbasic/sass/components/form/form-search-sort.scss
https://platform.dandigbib.org/issues/3668
Tests found out that clicking on the select arrow on the form sort didnt open the select.
This also fixes an issue in firefox where the text was cut off.
=> 3668: Make arrow clickable for search sort select.

themes/ddbasic/sass/components/ding-carousel.scss, themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/3910#change-39903
Padding-left removed from ul in ding-carousel. Font-style changed for ting-object with no overlay
No further comments or questions.
=> 3910: Remove padding and change font-style

modules/ding_campaign_plus/modules/ding_campaign_plus_basic/ding_campaign_plus_basic.module
https://platform.dandigbib.org/issues/3908
When there's no search string the array to match against becomes empty, since FALSE and empty values are filtered out. db_select condition throws a [syntax error exception](https://platform.dandigbib.org/issues/3908#note-17) when using an empty array with 'IN'. The query doesn't make much sense anyway, since it will always return 0 rows. 
More info: https://www.drupal.org/project/drupal/issues/1976666 
So instead we just skip the select-query when the search string is empty and return empty array.
Alternatively, we should not filter out empty strings in array_filter, so that it would be possible to make campaign triggers that matches against empty strings, but I didn't think this was the right way to go. However, my knowledge about this module is …
=> 3908: Fix DB error on searches without keywords

modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/3901
Some small changes was requested by the business:
1. The Page parameter p_mat_category was incorrectly using a dc:subject DKABM field for the value. Instead it should only show whether the material is fiction or nonfiction (or none at all).
The only reliable way to check this, is by using the 'sk' marker in the DK5-classification. This value gets stripped in OpenSearchTingObject::getClassification(), so it's going to be a bit "hacky" to get to this. Either go directly to the record or look for empty string/FALSE. I choose the latter approach in this PR.
Alternatively, we should add a new getCategory() method to the TingObjectInterface, which purpose is to return fiction/nonfiction or FALSE if not applicable.
2. We have chosen to also track the …
=> 3901: Webtrekk MWA fixes

modules/fbs/includes/fbs.reservation.inc
https://platform.dandigbib.org/issues/4041
A small change in https://platform.dandigbib.org/issues/1261 has led to a fatal error, when trying to delete reservations:
`Recoverable fatal error: Argument 2 passed to fbs_reservation_delete() must be of the type array, string given i fbs_reservation_delete()`
An array PHP typehint was added to FBS delete_reservation function. ding_reservation has always passed the reservations ids one by one and not in an array. See:
`ding_reservation_delete_reservations_form_ajax_submit()`
`ding_reservation_reservations_delete_submit()`
Now, FBS API does actually support deletion of more reservations at a time, but to support this we need to change the provider API and this will also effect other library providers.
So I think the best action right now, is to …
=> 4041: Fix fatal error on reservation delete

modules/ting/js/ting.js, modules/ting_search/js/ting_search_overlay.js
https://platform.dandigbib.org/issues/4039
The search overlay spinner suddenly started appearing when clicking the reserve-button. Investigating further I found these click-handlers from ting.js to be the culprit:
https://github.com/ding2/ding2/blob/7.x-4.6.0-rc5/modules/ting/js/ting.js#L18 
https://github.com/ding2/ding2/blob/7.x-4.6.0-rc5/modules/ting/js/ting.js#L25
These were not a problem before, since they were implemented with the jQuery `.live()` method, which for some reason wasn't fired (probably because of some code stopping event propagation). However, with the jQuery update, these were changed to `.on()` making them work and resulting in the search overlay incorrectly popping up when clicking on ding entity buttons (for example).
We only want these to pop up when users are …
=> 4039: fix search overlay spinner

modules/opensearch/opensearch.client.inc
Ensure that the uncached ids array in opensearch client when working with local ids are the correct ids.
The issue is in php's array_merge which resets keys/index when the keys are numeric only, which they are when the request is for local ids only.
No screenshot.
See https://platform.dandigbib.org/issues/3905#note-27 for more information.
=> 3905: Fixed uncached local ids in cache logic

modules/fbs/includes/fbs.availability.inc, modules/opensearch/opensearch.client.inc, modules/ting/ting.client.inc
This PR is dependant on https://github.com/ding2/ting-client/pull/26
https://platform.dandigbib.org/issues/3739
Adds support for fetching multiple marc-objects from opensearch at once and use this when generating shelfmark for holdings in FBS. The translation of faust to pid is also moved out of the loop, to also translate them all at once.
The process could in theory be optimized even further by avoiding the translation of faust completely. I do not think this is worth pursuing, since in all cases the holdings are fetched in a subsequent AJAX-request and doesn't prolong the initial request. Also, the translation is also done in a single getObject request now, which is very fast.
=> 3739: Availability optimization

themes/ddbasic/sass/components/header.scss, themes/ddbasic/sass/configuration/_variables.scss
3667: Move sub-menu to be above search.
In a previous revision we moved the main menu links position.
We forgot to also move the sub-menu links, so this commit
moves the sub menu to be in connection with the main menu.
N/A
=> 3667: Move sub-menu to be above search.

modules/bpi/bpi.module, modules/bpi/bpi.push.inc
https://platform.dandigbib.org/issues/3638
On top of the original 3638 requirement, is to explicitly mark the field required and only validate it's value prior to BPI push.
_Scrutinizer issue is unrelated._
=> 3638 by Inlead: Require image share permission prior to BPI pushing.

modules/ting_search_carousel/ting_search_carousel.module
https://platform.dandigbib.org/issues/1353
TingSearchCarouselQuery is converted to a string ID by taking the configuration, converting it to JSON and base64 encoding it.
This string ID is then used as suffix for the lock and cache ids, when fetching items for the carousel. The problem is that these IDs can get very long preventing the module from obtaining a lock, since lock ids are restricted to 255 characters in the DB. As a consequence the search was never actually performed and the carousel just kept requesting new items because it always returned offset 0. (See screenshot).
Another effect was that the carousel items was never cached, but the problem with lock id is much more serious since it prevents the carousel from functioning at all.
I propose that we instead use a hash of the …
=> 1353: Use hash on carousel id when generating lock and cache id

modules/bpi/bpi.module, modules/bpi/templates/bpi-preview-item.tpl.php
https://platform.dandigbib.org/issues/153
Disable the ability to save the node form, when syndicating own content. Even-though the original link is removed from the bpi content overview it is still possible to use the node syndication URI by manually pasting it into the browser url bar. For such cases show a message and disable form actions at all.
Also, remove the syndication when previewing when previewing own content.
Node form:
Preview (own content):
=> 153 by Inlead: Disable form actions when syndicating own content.

modules/ting_search/templates/ting-search-results-count.tpl.php, modules/ting_search/templates/ting-search-results.tpl.php, modules/ting_search/ting_search.module, modules/ting_search/ting_search.pages.inc, themes/ddbasic/templates/ting_search/ting-search-results.tpl.php
https://platform.dandigbib.org/issues/3832
Adds display of result count after actual search result (cf. https://github.com/ding2/ding2/pull/1287)
Note: Scrutinizer complains about issues with linebreaks in template files, but these issues are not related to the code in this pull request.
=> 3832: Added result count after search result

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3991
When the P2b module is active, it assumes that all ticket-links are given by the P2b module, disallowing the possibility of manual inputting a link to tickets.
=> 3991 by Inlead: Do not let P2b overtake buy-button.

modules/ting/ting.field.inc
https://platform.dandigbib.org/issues/4121
The language suffix was never displayed, as `$entity->getType()` returned the type with an uppercase, whilst the `variable_get('ting_language_type_title_suffix', []);` array had lower case elements.
It adds the "(Norsk)":
=> 4121: Make sure that language suffix is displayed.

ding2.install
https://platform.dandigbib.org/issues/4050
Apparently the business also wants to ensure that ding_webtrekk is activated on existing installs.
=> 4050: Ensure ding_webtrekk is activated on existing installs

modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc, modules/ting_search/plugins/content_types/search_result.inc
https://platform.dandigbib.org/issues/3983
Moves old campaign to top of page and removes the "Records are sorted..." message.
=> 3983 search page order

modules/ding_contact/ding_contact.module
https://platform.dandigbib.org/issues/3860
Original message and copy message sent from contact form had different headers. This commit fixes this issue so now the original and copy messages have the same headers.
=> 3860 by Inlead: Make original and copy messages the same.

modules/fbs/fbs.module
Otherwise you will get a validation error when you try to update
other parts of your profile.
The current values are timestamps while new values are in string
format. Convert them to timestamps to make them comparable.
The error:
=> 3043: Do not validate onhold values when dates do not change.

modules/bpi/bpi.module, modules/bpi/bpi.push.inc
https://platform.dandigbib.org/issues/3638
Removed the visible requirement of a field, and moved it to error message upon push to BPI is clicked.
=> 3638 by Inlead: Validate image dropdown only on BPI push.

ding2.info, ding2.install, modules/ding_sections/ding_sections.install
https://platform.dandigbib.org/issues/1604
Enable ding_sections and ding_nodelist by default.
=> 1604 by Inlead: Default enable Nodelist and Section.

modules/ting_field_search/ting_field_search.module, themes/ddbasic/sass/base/standard.scss, themes/ddbasic/sass/components/header.scss, themes/ddbasic/sass/components/menu.scss, themes/ddbasic/scripts/menu.js, themes/ddbasic/template.php
If there are too many links in the main menu, so it breaks into two lines, we need to tell CSS to adjust.
See:
=> 3667: Support multi-lines in main menu.

modules/ting/ting.field.inc
https://platform.dandigbib.org/issues/4121#change-41165
The old code appears to always return true.
=> 4121: Fix check for language suffix.

modules/ding_place2book/ding_place2book.module
To maintain compatibility, and avoiding place2book showing events with ambersands and/or quotes, as `Some Concert with &quot;Peter Petersen &amp; Lars Larsen&quot;`, we need to not sanitize the field like this..
See this proof of concept:
```php
$xml = simplexml_load_string('<?xml version="1.0" encoding="UTF-8"?>
<data>
<el></el>
</data>
');
// See implementation of check_plain in Drupal https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/check_plain/7.x
$xml->el = htmlspecialchars("Text & Test", ENT_QUOTES, 'UTF-8');
echo $xml->asXML();
```
*Outputs:*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<data>
<el>Text &amp;amp; Test</el>
</data>
```
```php
$xml = simplexml_load_string('<?xml version="1.0" encoding="UTF-8"?>
<data>
<el></el>
</data>
');
$xml->el = "Text & Test"; …
```
=> 3729: Remove check_plain around event name

modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.admin.inc, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.install, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.module
https://platform.dandigbib.org/issues/2147 
Improves migration by adding pre-migration tests, migrations status and the ability to re-run the migration until it's approved by the new "Approve migration" button.
=> 2147 better p2b migration

modules/ding_campaign_plus/modules/ding_campaign_plus_auto/ding_campaign_plus_auto.module
https://platform.dandigbib.org/issues/4167
Fixed the default vs. saved configuration in campaign plus in the admin form for the auto-generated campaign settings.
No screenshot.
No comments.
=> 4167: Ensure campaign auto-generated config is build correctly

modules/ding_webtrekk/ding_webtrekk.js
https://platform.dandigbib.org/issues/3901
Apparently it's not supported to use variables in object literals.
As a consequence all of the webtrekk events handled client side were not
sending the correct wtk ID.
The easiest fix seemed to be to instantiate the object first and then use bracket notation with the variables.
=> 3901: Fix custom click parameters for several events

modules/ding_contact/ding_contact.strongarm.inc
https://platform.dandigbib.org/issues/4159
Ding Gate WAYF submits the login_block_form as part of it's login process. Which get's flags by antibot module as spam.
So NemID login succeeds, but drupal login fails and the user ends up at the registry as new user page.  
No screenshot.
No comments.
=> 4159: Antibot prevents WAYF login

themes/ddbasic/sass/p2/p2-list.scss
https://platform.dandigbib.org/issues/4036
Make the "add to list" star not overlap the search button.
=> 4036: Make star not overlap the search button

modules/ding_base/ding_base.install
ding_base_update_dependencies was wrongly named
ding_base_update_requirements. Rename it to make it work.
Scrutinizer error is not related to the change.
=> 3603: Ensure the right version of jQuery is used for update environments

modules/ting_search/ting_search.install
https://platform.dandigbib.org/issues/4136
This change-set prevents DBCs environment to fail upon deployment of **ddb_cp**-active clients.
Apparently `variable_delete()` is a function from within the `variable`-contrib modul and not Drupal core. Since the `variable` module is only used by the **ddb_cp** module, it was only reproducible on "Webmaster"-libraries.
This only solves the problem and does not prevent any future errors of similar kind in regards to deployment.
=> 4136 by Inlead: Use core function and not variable-contrib function.

themes/ddbasic/sass/components/header.scss
Discovered a typo in this otherwise very fine work :)
=> 3667: Fix typo resulting in wrong offset for admin bar with shortcuts

modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/4139
In working with ereolen.dk we had issues with ting object that contained content from other objects and cache misses after the first view (which should not happen as the first view populated the cache).
No screenshot
Linked to https://github.com/ding2/ting-client/pull/29
=> 4139: Minor changes to opensearch cache

modules/ting_search/plugins/content_types/search_result.inc
https://platform.dandigbib.org/issues/4170#note-13
Adds the prefix and suffix to "0-hits" block on search results pane.
=> 4170 by Inlead: Show search suggestions on 0-hits.

modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/4194
The uncached id's were always passed to setObjectIds(). As a result requests based on local ids will fail.
An example is when we translate local ids from the status lists to PID by finding the namespace after looking up the local ids in getObject. These will always end up here:
https://github.com/ding2/ding2/blob/master/modules/opensearch/includes/opensearch.search.inc#L631 
As a consequence we are currently using the wrong namespace for a lot of materials in status lists.
There were also some additional problems were wouldn't hit the cache, and the objects returned wasn't keyed by PID when local ids was used in the request.
I realize that I'm setting both setObjectIds() and setLocalIds() when TingObjectRequest doesn't actually support requests …
=> 4194: opensearch cache local ids

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/1404
I discovered this while testing the new integration module on our production database:
If something goes wrong communicating with p2b API when updating existing event that is sync'ed with p2b, the code will override the field data with empty array, destroying the the link between p2b and CMS.
This PR introduces some better handling of these situations.
=> 1404: Dont delete field data on p2b API error

modules/fbs/fbs.module
Ensure that the on-hold dates are convented correctly and only once.
No screenshot.
No comments
=> 3043: Ensure on-hold dates are converted correctly in validation

modules/ding_news/ding_news.views_default.inc
https://platform.dandigbib.org/issues/4282
This is an addition for https://github.com/ding2/ding2/pull/1276/files#diff-8ae6c63897cf337c6827a7082586be05L913
The issue outlines that news nodes that lack group/library are missing in the view for anonymous users. Since only the exposed filters that relied on relationships were removed in the PR above, abandoned relationships interfered with the view output.
The **4 super sjove billedbøger** news lacks both library and group, and shows fine both for admin and anon users. It was missing for anons previously.
None.
=> 4282 by Inlead: Remove stall relationships.

modules/ding_loan/js/ding_loan.js
https://platform.dandigbib.org/issues/4261
Something has changed so that using a click handler for these checkboxes
breaks the functionality of the select all renew checkbox and therefore
also the global select all renew button (which just reuses the select
all checkbox).
The problem was the triggering of click handler on the local select all
checkboxes, from the change event handler on the global select all. This
would simuluate a real click changing state of the checkbox and mess up
the logic in the click handler. For example, if we have just set the box status 
to checked with the prop method, it would immediately change it back in 
browser click handler, before invoking our change handler.
I don't know why this hasn't been a problem before, but I suspect the jquery
update have caused …
=> 4261: Fix renew all loans button

modules/ting_infomedia/includes/ting_infomedia.wrapper.inc, modules/ting_infomedia/ting_infomedia.module
https://platform.dandigbib.org/issues/4237
Infomedia throws exception as it tries to login to FBS without pin-code which is not available (and not at all available when using singe-sign-on services). Code removed was from 2011.
Also fixed error handling that was wrong (sorry for that one) which now is handled by exceptions. 
No comments.
=> 4237: Clean up in infomedia error handling

modules/ding_event/ding_event.admin.inc, modules/ding_event/ding_event.module, themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/4286
Fix the display of event price to work with the price field after it has been converted to a text field.
- If price is empty show "Free" text
- Only show currency if price is numeric.
=> 4286: Fix event price display

modules/ding_webtrekk/ding_webtrekk.module, modules/opensearch/src/OpenSearchTingObject.php
https://platform.dandigbib.org/issues/4270
Material audience is now tracked in the parameter `p_mat_audience` with the value from [dc:subject with scheme dkdcplus:genre](http://metadata.dk/DKABM_2011#dcterms:audience)
Material fiction/nonfiction is now moved to `p_mat_ficnonfic` from `p_mat_category`. Also tried to find a more clean a correct way to get the value.
Material genre is now tracked in the parameter `p_mat_category` with the value from [dcterms:audience](http://metadata.dk/DKABM_2011#dc:subject_med_scheme_dkdcplus:genre)
=> 4270: Add new webtrekk tracking parameters

themes/ddbasic/sass/components/menu.scss
https://platform.dandigbib.org/issues/4267
Fixes wrong offset for user menu in header. Screenshot of the problem in the issue above.
Also fixes wrong offset of the menu when admin menu with or without shortcuts are used. In these cases we don't need the extra height, since admin_menu itself adds an offset.
=> 4267: Fix offset for user menu in header

modules/p2/ding_entity_rating/ding_entity_rating.install, modules/ting_infomedia/ting_infomedia.install
https://platform.dandigbib.org/issues/4291
I have observed on two of my local test sites that one of the causes for the FacesExtendable exception can be a field instance in the DB, that is missing its field type definition.
There're a couple of cases where a field type definition has been removed, but any associated fields/instances has not been correctly removed from the DB. This PR ensures that this is done.
Se these notes for more info:
https://platform.dandigbib.org/issues/4291#note-8
https://platform.dandigbib.org/issues/4291#note-19
=> 4291: Delete left over fields and instances from DB

modules/ding_sections/modules/ding_sections_term_menu/ding_sections_term_menu.module
https://platform.dandigbib.org/issues/4279
By default on Section creation there is an option to create menu item in main menu. As it was required, this commit disables this action so by default checkbox will be unchecked.
=> 4279 by Inlead: Do not make menu default when creating Section.

ding2.info, ding2.install, ding2.make, ding2.profile, themes/ddbasic/sass/components/cookie.scss, themes/ddbasic/scripts/site.js, themes/ddbasic/templates/eu-cookie-compliance-popup-info.tpl.php
https://platform.dandigbib.org/issues/4207
This addresses a cross site scripting security issue:
https://www.drupal.org/sa-contrib-2019-033
The update is a major leap in versions where the functionality of the
module has been extended to take GDPR and other issues into account.
We do not have to do anything special regarding consent here so we
just need to configure the module to behave as it did previously.
With the new configuration options this boils down to:
1. Using the default consent method
2. Not showing any disagreement button
The updated module uses `I18n_variable` to store internationalized
settings. To provide a consistent configuration we also use this
module for new installs. Instead of defining all configuration
options we modify the defaults to work as we want to. This …
=> 4207: Update EU Cookie Compliance module to 1.28

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/ding_nodelist.install, modules/ding_nodelist/ding_nodelist.strongarm.inc, modules/ding_nodelist/js/video.js, modules/ding_nodelist/sass/ding_nodelist.scss, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.node_blocks.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.carousel.tpl.php
https://platform.dandigbib.org/issues/4168
Added support of Eresources CT content into nodelist module. This commit contains changes for clean installs/update for enabling Eresources support and templates for each type of widgets present in current distribution.
=> 4168 by Inlead: Add Eresource CT as supported Nodelist CT.

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_provider/ding_provider.loan.inc, modules/ding_provider/ding_provider.reservation.inc, modules/ding_reservation/ding_reservation.module, modules/ding_webtrekk/ding_webtrekk.module, modules/fbs/includes/fbs.loan.inc, modules/fbs/includes/fbs.reservation.inc
https://platform.dandigbib.org/issues/3936
In the latest versions a lot of libraries has experienced the "Error: unknown/missing/inaccessible record:" problem with materials on statuslists.
I have posted a pretty hacky attempt to fix this here: https://github.com/ding2/ding2/pull/1293, but it relies on a weird way of handling not-found object in opensearch getObject. We are in contact with DBC and they will update opensearch to handle it in a better way.
This should only be a problem with ILL loans/reservations since we should be able to always get an entity for materials in the libraries own catalog.
During analysis in https://platform.dandigbib.org/issues/3936 we have found out that we actually shouldn't try to make a request against opensearch at all for ILL, since the ID we recieve …
=> 3936: Fix missing titles for ILL on loan/reservation

themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/sass/components/node/group.scss, themes/ddbasic/sass/components/node/news.scss
https://platform.dandigbib.org/issues/3912
Adds underline to links in body on event, news and groups.
=> 3912: Underline links

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.module, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc, themes/ddbasic/template.node.php, themes/ddbasic/templates/node--ding-library.tpl.php
https://platform.dandigbib.org/issues/3046
Render closed days across the table to fill out with "closed" in relation to categories.
This is a re-roll of #881
=> 3046: Re-rolled patch from PR 881

modules/alma/alma.module, modules/ding_availability/ding_availability.field.inc, modules/ding_availability/js/ding_availability.js, modules/ding_carousel/js/ding_carousel.js, modules/ding_provider/connie/connie.module, modules/ding_reservation/ding_reservation.module, modules/ding_reservation/js/ding_reservation_reservability.js, modules/fbs/fbs.module, modules/opensearch/includes/opensearch.search.inc, modules/opensearch/opensearch.install, modules/opensearch/opensearch.module, modules/ting/ting.admin.inc, modules/ting/ting.install, modules/ting/ting.module, modules/ting_reference/js/ting_reference_ajax.js
https://platform.dandigbib.org/issues/1460
**Motivation**
The primary motivation for the changes in this PR, is to move the responsibility of checking reservability of materials from the ting module to the library provider layer
**Issues with current implementaion**
I have listed several issues with the current situation, where ting module decides reservability based on material types from the well, here: https://platform.dandigbib.org/issues/1460#note-48
**Disadvantage with the approach in this PR**
We need to do and additional look-up to check reservability, but we still need to make this look-ups anyway to check holdings/availability. (therefore, this could be solved with caching as explained below). To somewhat combat this, I have implemented the reservability check with AJAX-request, …
=> 1460: Reservation buttons overhaul

themes/ddbasic/sass/components/form/form-user-profile.scss
https://platform.dandigbib.org/issues/4329
The form description element needed a width and float to be correctly displayed
=> 4329: Fixed pincode description float

modules/ding_event/ding_event.info, modules/ding_event/ding_event.views_default.inc
https://platform.dandigbib.org/issues/4272
Reuses the "Library list" nodequeue on the the main event list' exposed library filter.
This enables administrators to control the order of libraries in the filter list shown to users.
The order of the "Library list" nodequeue is used to sort the library list and it makes good sense to use this order also on the filter list.
=> 4272: Nodequeue on event list exposed library filter

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4243
Wrapper on object view page overlap.
Before:
After:
No comments
=> 4243: Fixed overflow on object view

modules/ding_eresource/ding_eresource.views_default.inc, modules/ding_staff/ding_staff.views_default.inc
https://platform.dandigbib.org/issues/4233
The language of strings within the Eresources and Staff views are written in Danish. They should be written in English and then translated.
Please note that these strings should be translated, if they are not default in Drupal.
=> 4233 by Inlead: Use English values, not Danish.

modules/ding_ipe_filter/css/ding_ipe_filter.modal.css, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/4199
Configuration forms rendered in Ding IPE popup takes default site's theme, which is not adapted yet.
In this commit are added styles which are loaded when popup is opened, so those styles are not breaking anything else.
=> 4199 by Inlead: Nodelist styling changes.

modules/ting_search_carousel/plugins/content_types/carousel.inc
https://platform.dandigbib.org/issues/4197
Make carousel pane title configurable.
=> 4197: Make carousel title configurable again

modules/ding_ting_frontend/ding_ting_frontend.features.field_instance.inc, modules/ting/ting.field.inc, themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/4100
From #1361:
> For WCAG reasons, the elements within a carousel should use `<h3>` instead of `<h2>` for their titles.
This does it by extending the field formatter with configuration for which HTML element to use, and configure the teaser display to use it.
Supersedes #1361
=> 4100 carousel h2 to h3 take two

themes/ddbasic/sass/base/standard.scss
https://platform.dandigbib.org/issues/4196
Ensure that our fixed header elements doesn't overlap in-page anchors.
=> 4196: Ensure fixed header elements doesn't overlap in-page anchors

themes/ddbasic/sass/add-ons/genre-list.scss, themes/ddbasic/sass/components/ding-tabroll.scss, themes/ddbasic/sass/components/menu.scss, themes/ddbasic/sass/components/node/campaign.scss, themes/ddbasic/sass/components/node/group.scss, themes/ddbasic/sass/components/node/news.scss, themes/ddbasic/sass/components/node/page.scss, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/sass/configuration/_mixin.scss, themes/ddbasic/sass/configuration/_variables.scss
https://platform.dandigbib.org/issues/4095
A lot of the buttons on the website have poor color contrast, with very light font colors used on light backgrounds and vice versa
This looks to fixes this, whilst trying not to introduce any new colors.
Basically affects all buttons on the website, but if I have done my job correctly you wont notice the difference unless you compare directly.
=> 4095: Better accessability color contrast

modules/ding_ting_frontend/ding_ting_frontend.features.field_instance.inc, modules/ting_covers/ting_covers.theme.inc, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/template.php, themes/ddbasic/templates/material-item.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--collection-list.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--reference-teaser.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--search-result.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--teaser-no-overlay.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--teaser.tpl.php, themes/ddbasic/templates/ting_object/ting-object--view-mode--ting-reference-preview.tpl.php
https://platform.dandigbib.org/issues/4092
Adds title attribute to cover links.
First commit fixes the ting_cover field formatter.
The second re-activates the link on teaser display modes and removes the link generated by `ddbasic_process_ting_object()` and added to all ting_object teaser templates.
=> 4092 cover link title

modules/ding_frontend/plugins/layouts/site_template/ding2-site-template.tpl.php, themes/ddbasic/ddbasic.info, themes/ddbasic/sass/components/skip-link.scss, themes/ddbasic/templates/panel-layout/ding2-site-template.tpl.php
https://platform.dandigbib.org/issues/4091
This is a visually hidden link which skips to the main content of the page.
It's placed at the top of the page, and it's useful for screenreader-users as a way of skipping past any base layout, such as the header.
The styling which hides it visually is based on the same way that core themes usually do it.
=> 4091: Skip to content link.

themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/scripts/node/event.js
https://platform.dandigbib.org/issues/4089
Currently, the linkboxes does not show the hover effect when you keyboard-tab to them.
This fixes that.
It's these boxes we're talking about:
=> 4089: Make sure linkboxes have hovereffect on focus.

modules/ding_user/ding_user.module, themes/ddbasic/sass/components/form/form-user-login.scss, themes/ddbasic/scripts/menu.js
https://platform.dandigbib.org/issues/4088
- Makes sure the hidden login form is also hidden for screenreaders when it's closed, using aria-hidden
- When the login form is hidden, remove ability to tabbing to it
- When it is open, set focus on first element
=> 4088: Screenreader / focus tweaks for userlogin.

modules/ting_search/ting_search.module, themes/ddbasic/templates/search-block-form.tpl.php
https://platform.dandigbib.org/issues/4086
Screenreaders and SEO uses the role attribute to know that this is a search form. This means hidden headings are not necessary.
=> 4086: Replace search hidden heading with role attribute.

modules/ding_tabroll/js/ding_tabroll.js
https://platform.dandigbib.org/issues/4084
When there is keyboard focus within an animated tabroll, the tabroll should be paused as it is when you do mouse hover over.
=> 4084: Pause tabroll with keyboard focus.

modules/p2/ding_list/include/form.inc
https://platform.dandigbib.org/issues/4049
Within the sourcecode there is misspellings of "No mails sent", which is given as "No mails send". This string is presented/displayed to the user.
=> 4049 by Inlead: Fix misspelling.

themes/ddbasic/scripts/view.js
http://platform.dandigbib.org/issues/3974
At some point between the latest releases, the sorting/display of Events have changed.
**Release 29 (7.x-4.5.x):**
**Release 30 (7.x-4.6.x):**
The problem is not in the releases. This behavior occurs when 2 or more nodes in the view doesn't have images. It tries to stack them in a single column.
=> 3974 by Inlead: Sorting of Events is changed

modules/ding_event/ding_event.info, modules/ding_event/ding_event.strongarm.inc, modules/ding_news/ding_news.info, modules/ding_news/ding_news.strongarm.inc
http://platform.dandigbib.org/issues/3966
In https://github.com/ding2/ding2/pull/1095 the mobile viewing was enabled by default for News and Events.
However, the change did not include a definition that this configuration is part of the respective modules' configuration. It should be added to the info file of the modules so that we ensure that the configuration is not removed inadvertently through Feature Updates eg. https://github.com/ding2/ding2/pull/1266.
=> 3966 by Inlead: Define mobile flags for CTs.

modules/fbs/includes/fbs.availability.inc
https://platform.dandigbib.org/issues/3738 
The cause for this issue was also the cause for the issues reported in:
https://platform.dandigbib.org/issues/4178
https://platform.dandigbib.org/issues/4219
So this PR also fixes the examples from those cases.
There was two separate issues causing the reported cases:
1. There can be multiple 652 fields on a material and we need to use data
from the same 652 field that we got the classification number from.
2. The DK5 classification was missing in some cases where there was no
value in 'm', but 'o' had the correct value. Before we assumed it would
always be present in 'm', but apparently this is not the case for some
materials.
=> 3738: Fix incorrect shelfmarks for non-fiction

themes/ddbasic/sass/p2/p2-entity-buttons.scss
https://platform.dandigbib.org/issues/3320
This PR includes SCSS previously introduced in https://github.com/ding2/ding2/commit/2c94f4bdbfd151ee008fc5642d5c8ff932c8a640#diff-fc43d7933e2f5935cc2fec36d4251a9c but removed in PR https://github.com/ding2/ding2/commit/b478dea3d1a2d275d5fc51513b3d7c12e84678a9#diff-fc43d7933e2f5935cc2fec36d4251a9c
Cannot reproduce missing notification of adding already existing material to list
=> 3320: P2 list covered by header

modules/ding_event/ding_event.views_default.inc, themes/ddbasic/sass/components/panel/class-panel.scss
https://platform.dandigbib.org/issues/284
Event Target has been added to the Filtering options of the Event liste page (/arrangementer).
=> 284 by Inlead: Added event target as filtering option.

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/4319
Adds red asterisk to required p2b price fields. See screenshot.
The price field is only required if the event is **not** passive. Therefore we can't use the FAPI #required validation, since [it only cares about the initial field setting in backend](https://www.drupal.org/project/drupal/issues/2855139#comment-12472554).
To still take advangtage of the states API, we can manually theme the required marker in backend and keep our custom validate handler. Some additional logic is required though, since the fields should only be required for existing prices or if no prices currently exist for the event in p2b (we need at least one price for non-passive event for it to work correctly in p2b).
Also removed the notice about price is not deletable and …
=> 4319: Show red asterisk for required p2b fields

modules/ding_nodelist/templates/ding_nodelist_widget_promoted_nodes.tpl.php, themes/ddbasic/scripts/ddbasic.common.js
https://platform.dandigbib.org/issues/4266
Makes all "Promoted Nodes" Nodelist widget items clickable.
=> 4266 by Inlead: Complete Nodelist element should be clickable.

modules/ding_nodelist/ding_nodelist.module
https://platform.dandigbib.org/issues/4138
Events in the node in blocks widget show the previous date for the all day items.
=> 4138 by Inlead: Consider timezone for all day events.

modules/ding_carousel/js/ding_carousel.js, modules/ding_ipe_filter/css/ding_ipe_filter.css, modules/p2/ding_serendipity/ding_serendipity.module
https://platform.dandigbib.org/issues/4107
There was observed some logic and UI issues in process of using IPE functionality provided by ding_ipe_filter module.
This PR fixes described issues:
1. UX issue for editors: In Primary Content there is elemnts that is very hard to insert. It happens because the menu with options is sliding up "behind" the main menu, and therefore you can't see all elements.
2. It is impossible to Insert and Save the "Ding Serendipitet med TingObject (Materialer)" widget.
3. When saving, there is no indication what is going on and it can take several minutes for it to save - letting editors click other links in the waiting time. There should be an indication that panel is saving.
=> 4107 by Inlead: Improvements to IPE.

themes/ddbasic/sass/components/menu.scss
https://platform.dandigbib.org/issues/3962
Hide nested menu items on expandend li on third level menu. Display when parent li element is active.
=> 3962: Hide 4th level menu

ding2.install
https://platform.dandigbib.org/issues/3350
For some reason this got to sneak in. Remove it as it is a syntax 
error. We are already covered regarding translation updates.
=> 3350: Remove duplicate update hook

modules/ding_tabroll/ding_tabroll.views_default.inc
https://platform.dandigbib.org/issues/4256
The tabrolls are missing because of a bug that appears in a very specific setup with a non-required entity reference field used as a non-required relationship on a view:
https://www.drupal.org/project/drupal/issues/1349080
The reason why this error hasn't surfaced before is that the node_access table hasn't been rebuild after enabling view_unpublished and therefore still contains the global view all access record that the node module adds on install. On those sites where it's suddenly appearing something must have triggered a rebuild.
There's a patch provided for Drupal 7 in the issue, but it's a bit extensive and has some test fails. When reading through the comments in above issue, it doesn't seem like the Drupal 7 patches are tested and …
=> 4256: Fix missing tabrolls

themes/ddbasic/sass/components/menu.scss
https://platform.dandigbib.org/issues/4063
Add clearfix to 3rd level menu item - to display collapsed menu-items on mobile
=> 4063: Fixed 3rd level menu mobile

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/4380
It's currently not possible to get a working book button on place2book events, if p2b-sync is added to an existing event. This PR fixes that.
Also ensure that p2b-URL is removed when p2b-sync is, to avoid wrongfully showing a booking button.
=> 4380: Ensure p2b ticket URL is updated for existing events

modules/ding_campaign_plus/modules/ding_campaign_plus_basic/ding_campaign_plus_basic.module
https://platform.dandigbib.org/issues/4331
This PR contains two fixes to the matching in campaign plus basic search term trigger, which both prevent it from working it all.
1. There was a typo on the sub-type of basic campaign. For search term the key is `search_term` not `search_request`. This typo prevented the code from fetching the correct campaigns in the DB. Fixed in: 80f88146ca9536eb59091adb4c063d17c0cecd36
2. The mathing of the user entered search term and the matching value in the DB for the campaign was incorrect/the other way around. Instead of taking the comma-separated value from the DB and splitting into terms it took the user entered search. As a consequence, campaigns with several comma-separated terms was not working and also a single search term with several words was …
=> 4331: Campaign plus basic search term fixes

modules/ding_campaign_plus/js/ding_campaign_plus.js
https://platform.dandigbib.org/issues/4322
The default panel pane markup surrounding campaign plus panel panes
has styling. It will be rendered when using asynchronous loading
but only the content of the pane is replaced with actual content. If 
there are no campaigns to be shown in the panel pane this means that 
the surrounding markup remains. As it is styled with a padding and 
background color this leaves an empty grey box.
To avoid this we hide the entire wrapper by default and only show
it if any actual campaign markup has been loaded.
=> 4322: Do not display async empty campaign plus pane wrapper

modules/ding_campaign_plus/ding_campaign_plus.strongarm.inc, modules/ding_eresource/ding_eresource.info, modules/ding_eresource/ding_eresource.strongarm.inc, modules/ding_event/ding_event.strongarm.inc, modules/ding_groups/ding_groups.info, modules/ding_groups/ding_groups.strongarm.inc, modules/ding_library/ding_library.info, modules/ding_library/ding_library.strongarm.inc, modules/ding_news/ding_news.strongarm.inc, modules/ding_page/ding_page.info, modules/ding_page/ding_page.strongarm.inc, modules/ding_tabroll/ding_tabroll.info, modules/ding_tabroll/ding_tabroll.strongarm.inc, themes/ddbasic/template.node.php, themes/ddbasic/templates/node--ding-library.tpl.php, themes/ddbasic/templates/node--ding-page.tpl.php, themes/ddbasic/templates/node/node--ding-campaign-plus--image.tpl.php, themes/ddbasic/templates/node/node--ding-campaign-plus--text-and-image.tpl.php, themes/ddbasic/templates/node/node--ding-campaign-plus--text-with-image.tpl.php, themes/ddbasic/templates/node/node--ding-campaign-plus--text.tpl.php, themes/ddbasic/templates/node/node--ding-campaign.tpl.php, themes/ddbasic/templates/node/node--view-mode--search-result.tpl.php, themes/ddbasic/templates/node/node--webform.tpl.php, themes/ddbasic/templates/node/node.tpl.php
https://platform.dandigbib.org/issues/4094
Currently, some libraries have english pages.
The issue is that these pages, if read by a screen readers, or index by a search engine, will be treated as danish content, as the only `lang` property on the page is on `<html lang="da"`
Looking at the page, this is actually not the problem -  the content around the nodes are actually in danish, such as the menu and footer, so really we only want a `lang="da"` on the actual content.
This PR:
- Adds a selector to the node form, where the editor can choose a language:
- Based on the chosen language, it sets a `lang="[LANGCODE]"` on the relevant node content wrapper.
=> 4094: Langcode on node content.

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
https://platform.dandigbib.org/issues/3002
Consider the blocked days when in the widget that displays all opening hours today.
Continuation of https://github.com/ding2/ding2/pull/835.
=> 3002 by Inlead: Consider blocked dates in all opening hours.

modules/ting_material_details/ting_material_details.features.field_instance.inc, modules/ting_material_details/ting_material_details.field.inc
https://platform.dandigbib.org/issues/1941
Make the contributor-field a clickable link to search for creators, the subjects-field clickable to search for subjects and enclose the query within quotes to support strings with spaces.
=> 1941 by Inlead: Convert metadata to links.

tests/behat/features/01-Searching.feature
Allow lowercase letters when searching for ÆØÅ in tests
These cases may return search results with æøå (lowercase) which will 
currently not be accepted by the test case. However this is
acceptable behavior.
Update test case to allow lowercase versions of these letters.
=> Core: Allow lowercase letters when searching for ÆØÅ in tests

modules/ting_search_carousel/plugins/content_types/carousel.inc
https://platform.dandigbib.org/issues/4197
Removes the "description" field from carousels. It haven't been used for a long time.
=> 4197: Remove subtitle from ting_search_carousel

modules/fbs/fbs.module
Please add a link to the issue being addressed by this change.
An exception can be thrown if provider is down or if its not
configureed correctly. Since we call fbs_service directly, we
need to handle exception ourselves.
The reservability check should always be done asynchronously with AJAX and therefore should not be able to take the whole frontpage down. I havn't had time to investigate why this happens, but I can confirm this fixes the WSOD on frontpage, when issues with FBS-provider.
=> 4379: Catch exception when checking reservability

modules/ting_search_carousel/ting_search_carousel.module
https://platform.dandigbib.org/issues/4379
This PR fixes two issues with the current implementation of search carousels to prevent timeouts when retrieving carousel items:
1. Fix progressing through search result for carousel covers
2. Correct identification of search carousel offset/size mismatch 
Please check commit comments for additional details.
=> 4379: Prevent carousel timeouts

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/plugins/content_types/ding_nodelist.inc, modules/ding_nodelist/sass/ding_nodelist.scss, modules/ding_nodelist/templates/ding_nodelist.ding_event.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.node_blocks.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.promoted_nodes.tpl.php, modules/ding_nodelist/translations/da.po, modules/ding_nodelist/translations/general.pot
https://platform.dandigbib.org/issues/4166
General improvements to all the displays was done.
The "Width" of the Nodelist configuration as also removed, as it's not supported or used anymore.
=> 4166 by Inlead: Improve Nodelist displays.

.circleci/config.yml, tests/behat/behat.yml, tests/behat/composer.json, tests/behat/composer.lock
https://platform.dandigbib.org/issues/4378
This PR addresses a few annoyances when working with Behat tests locally:
1. Allow developers to define Chrome remote debugging url using params. It might not always be running on localhost.
2. Require newest version of Chrome Mink Driver for compatibility.
=> 4378: Improve behat setup

.scrutinizer.yml, phpcs.xml.dist
These changes doesn't affect site functionality, so I don't think it will be necessary with an issue on redmine?
An attempt at fixing scutinizer. 
Since #1478 every PR has been hanging at "Pending — Installing Code" for the Scrutinizer tests.
I contacted Scrutinizer support team and got following answer: https://github.com/ding2/ding2/pull/1480#issuecomment-513203525
Apparently the tools sections is not supported anymore. Third party analysis tools will have to be used directly under the build section. Also using separate codesniffer config file.
https://scrutinizer-ci.com/docs/configuration
https://github.com/pfrenssen/coder#store-settings-in-a-phpcsxmldist-file
If you have any …
=> Update Scrutinizer: Fix stuck on "Pending — Installing Code"

ding2.install
https://platform.dandigbib.org/issues/4428
Enabled i18n variable module if it is not. Fixed error in update hook that uses that module.
No screenshot.
No comments.
=> 4428: Enable i18n variable module

modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_adgangsplatformen/includes/ding_adgangsplatformen.admin.inc, modules/ding_provider/connie/connie.auth.inc
https://platform.dandigbib.org/issues/4467
This PR updates the Ding Adgangsplatformen module to support and use [single signout](https://github.com/DBCDK/hejmdal/blob/master/docs/single-logout.md).
A new endpoint is defined which should live up to the provided specification. The module will return status code 403 for users which should not support single signout because they have not authenticated via Adgangsplatformen. @vibjerg has nodded to this approach although it is not mentioned in the current documentation.
=> 4467: Adgangsplatformen single signout

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.install, modules/ding_place2book/ding_place2book.module, modules/ding_place2book/lib/p2b/P2b.php
https://platform.dandigbib.org/issues/4391
Once you have created an event and defined values in Maintain copy, Kultunaut export and Passive event as you wish, then it stores the event fine and correct. But if you edit the event, it sets the default values again even if you do not want it to change
**Example 1:**
I have in the standards for p2b under /admin/config/ding/place2book/defaults checked Maintain copy, Kultunaut export and Passive arrangement.
I create an event that I want there to be ticket to. So I remove the checkmark in "Passive".
I save the event.
I would like to edit the body-field of the event, so I edit the event.
I now notice that "Passive" is again marked in the standards.
If I accidentally save, the ticket link is gone, and I cannot undo to a non-passive event, and if …
=> 4391 by Inlead: Place2book: Default values are overriding given values.

modules/bpi/bpi.module
https://platform.dandigbib.org/issues/4001
Change the validation mechanism of imported bpi materials to use same logic as in the ting_reference field. This makes sure that there's no different logic when validating materials, therefore producing unexpected results. For example, when after syndicating content the form reports validation errors regarding bpi materials, when, in fact, these materials do exist.
None.
None.
=> 4001 by Inlead: Use validation as in ting_reference field.

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/4446
We have observed that some data is getting removed from p2b when updating event in CMS. Apparently p2b will remove some data if it's missing in the update request we send to API.
This PR ensures that no data is missing by merging original event and tickets with our updates.
=> 4446: Ensure no data is missing when updating tickets/events

themes/ddbasic/scripts/menu.js
https://platform.dandigbib.org/issues/4088#change-43789
Previously we used :focusable, which turns out to be a jQuery UI selector.
This replaces it to work with standard, vanilla jQuery.
=> 4088: Replace jQuery UI selector with native JS.

modules/opensearch/includes/opensearch.search.inc
https://platform.dandigbib.org/issues/4454
The first item in the array will have key = 0. So it will evaluate to
FALSE if we don't use strict, which means incorrect translation if it's
not a basis-post.
=> 4454: Use strict comparison when checking key

themes/ddbasic/scripts/node/event.js
https://platform.dandigbib.org/issues/4416
View class added to imagesLoaded function that triggers a resize event for event teasers.
No further comments.
=> 4416: Resize event called on view when images are loaded

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4415
Color changed for action button "reserve-button" and "button-see-online"
No further comments
=> 4415: Change color on button

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/4399
In the hook_node_presave() implementation (ding_place2book_node_presave) we set field_ding_ticket_link with sales link to P2b, if the event is synced with P2b. We should add a check here, so that we only set this if event is not passive.
This will work properly when the #1472 PR is merged. Since, on each node presave a PUT request is sent to p2b service.(See discussion in PR.)
=> 4399 by Inlead: P2b - Do not set ticket link if node is passive.

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/4319#note-18
A minor follow up from the changes in #1423  
Only show validation errors for price name and value and not also on sales period like before.
=> 4319: Only show validation errors for price name and value

modules/ding_app_content_rss/ding_app_content_rss.module
https://platform.dandigbib.org/issues/4285
This changes the output of **content-rss:arrangement-location** feed field. 
Values outputted: 'name_line', 'thoroughfare', 'postal_code', 'locality', 'country'.
=> 4285 by Inlead: Adjust ding_app_content_rss_location value.

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/4173
New sections must listen to default panel variant which is stored in database and not the one from code.
=> 4173 by Inlead: Use default panel variant from database.

ding2.make, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/4171
This is a proper fix for previous attempts of fixing the original issue.
See: https://github.com/ding2/ding2/pull/1434 and https://github.com/ding2/ding2/pull/1475
In fact, a ctools module upgrade is suggested.
=> 4171 by Inlead: Proper fix for ctools panel title override checkbox.

modules/ding_facetbrowser/ding_facetbrowser.admin.inc, modules/opensearch/opensearch.module
https://platform.dandigbib.org/issues/4169
Add the opensearch specific facet documentation link in a form alter in opensearch module instead of in ding_facetbrowser module.
Also make the link work for every version of opensearch by using the system's current opensearch_url.
As a side effect this splits up the description in two translatable strings which should be translated (doesn't look like the original string was translated by default):
- `t('Configure facets shown in the facetbrowser.')`
- `t('Supported facet names can be found at <a href="@url">DBC wiki</a> and is usually named <em>facet.something</em>.')`
If you have any further comments or questions for the reviewer them …
=> 4169: Add opensearch specific facet description

ding2.install, modules/p2/ding_entity_rating/ding_entity_rating.module, translations/da.po
https://platform.dandigbib.org/issues/4090
Adding a `title` tag to the rating option `<a>`'s. See screenshot for best explanation :)
Code + Hover text:
=> 4090: Add help text to rating buttons.

themes/ddbasic/sass/p2/p2-entity-buttons.scss
https://platform.dandigbib.org/issues/4114
Removed default padding on .button ul element, that breaked the alignment with p2 list buttons.
=> Fixed ding-list button padding

modules/ding_news/ding_news.install, modules/ding_page/ding_page.install, modules/ding_paragraphs/ding_paragraphs.module
Fixed LUG migration issues
* Wrong update dependencies number to ding2 install
* Fixed division by zero when not content of type exists
https://platform.dandigbib.org/issues/3021
There was an error running update hooks.
No screenshot
Re-used the old ticket form for this PR.
=> 3021: Fixed LUG migration issues

modules/ding_eresource/ding_eresource.features.field_base.inc, modules/ding_paragraphs/ding_paragraphs.module
https://platform.dandigbib.org/issues/3021
When running update hooks on an existing site two errors occurred which prevented the update process from completing. 
This PR addresses these errors. Please read commit comments for additional commentary.
=> 3021: Fix LUG migration errors

themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/sass/components/node/news.scss, themes/ddbasic/sass/components/node/page.scss, themes/ddbasic/sass/configuration/_typography.scss, themes/ddbasic/sass/p2/p2-entity-buttons.scss
https://platform.dandigbib.org/issues/2996
Changes to the scss to handle wider columns and larger base font
No comments
=> 2996: Wider columns and larger base font

modules/ding_paragraphs/DingParagraphsBPIHelper.php
https://platform.dandigbib.org/issues/3543
Materials shared via the BPI web service are validated when syndicating content, but apparently the signature of `bpi_validate_material` which is used for validation has been changed.
The doc block for `bpi_validate_material` (https://github.com/ding2/ding2/blob/master/modules/bpi/bpi.module#L952-L962) states that `$ting_object_id` should be a faust number (“the number after the colon” as I understand it). Is this correct?
It seems that a full object id, e.g. `870970-basis:03258351` is required.
=> 3543: Fixed argument for bpi_validate_material

modules/ding_user/ding_user.module, modules/ding_user_form/ding_user_form.module
https://platform.dandigbib.org/issues/4496
Set the old cache headers (to prevent browsers in caching user pages) by moving them from ding_user_form to ding_user.
Restore cache headers from before adgangsplatformen.
No screenshot.
No comments.
=> 4496: Ensure user page is not cached in browser

tests/behat/features/bootstrap/CreateNewsContext.php, tests/behat/features/bootstrap/Page/Common/CreateNewsPage.php, tests/behat/features/campaign_plus/05-create-auto-campaign.feature
Made behat test of auto campaigns/news compatible with paragraphs module
https://platform.dandigbib.org/issues/4479
Feature #3021 "LAYOUT UDEN GRÆNSER" changed the body field for nes from a ckeditor wysiwyg field to a paragraphs module based setup. This broke the the behat testing for campaign plus. 
This PR fixes and re-enables the test. 
N/A
N/A
=> 4479: Fixed behat test of auto campaigns/news

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/4394
We should only add reference to original price if the current price is
existing and have a price id in p2b. Otherwise our sync function will
try to update a non-existing price.
Note that we need to check for $price->id. It's not enough to verify
price is non-empty since it can be a clone which has data but no id.
=> 4394: Only add original price if price is existing and has id

modules/ding_base/ding_base.info, modules/ding_base/ding_base.install
https://platform.dandigbib.org/issues/4381
Autologout in combination with single signout from Adgangsplatformen
will log out the user from all platforms when inactive on one. That
is not helpful - especially in combination with platforms used for
passive media consumption.
We do not remove the module entirely as some libraries may want to
retain the autologout functionality. They will have to reenable it
themselves subsequently.
=> 4381: Disable Autologout once Adgangsplatformen is installed

modules/ding_entity/ding_entity.api.php, modules/ding_entity/ding_entity.module, modules/ding_provider/connie/connie.module, modules/ding_provider/connie/connie.reservation.inc, modules/ding_reservation/ding_reservation.module, modules/ding_reservation/js/ding_reservation_reservability.js, modules/fbs/fbs.module, modules/fbs/includes/fbs.reservation.inc, modules/opensearch/opensearch.module, modules/ting/ting.admin.inc, modules/ting_reference/ting_reference.module, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/1460
Continuation of the work in https://github.com/ding2/ding2/pull/1139
This PR contains changes requested in previous PR and some small corrections:
1. Optimization of reservability checks. Now checks multiple materials at once - both in frontend and backend.
2. Do not check reservability for periodical reserve buttons to avoid making unnecessary requests.
3. Handle FBS errors when checking reservability to prevent fatal PHP error. 
=> 1460: Reservation buttons overhaul Round 2

modules/ting_field_search/ting_field_search.module
https://platform.dandigbib.org/issues/4507
Ensure that the messages session variable is removed completely when removing errors to allow empty search with profile.
=> 4507: Ensure session variable is removed completely

modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_adgangsplatformen/includes/ding_adgangsplatformen.admin.inc
https://platform.dandigbib.org/issues/4494
Added option to add agency to the auth url to automatically select the library at adgangsplatformen.
Added setting to `/admin/config/ding/adgangsplatformen` allow this new setting.
No comments.
=> 4494: Add agency to SSO login url

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4095
See https://upgrade-fbs.ddbcms.dk/biblioteker
Currently not passing proper AAA contrast ratio:
My changes fixes it:
=> 4095: Improve contrast for opening hour toggle.

modules/ding_paragraphs/ding_paragraphs.module
https://platform.dandigbib.org/issues/3543
Paragraphs images are not added correctly to assets when pushing content to the BPI web service (using `+` rather than `array_merge` will potentially discard some paragraph images).
=> 3543: Fixed handling of paragraph assets in BPI content

modules/ding_place2book/ding_place2book.install
https://platform.dandigbib.org/issues/4399
In the [previous PR](https://github.com/ding2/ding2/pull/1482) we have ensured that we don't put the p2b sales URL in the ticket link field for passive events.
However, there still might be some existing passive events with ticket links, so in this PR we add an update function which find all these and ensure that the ticket link is removed. Since this can potentially result in several request to p2b API, we use the batch API to ensure no timeouts and to give partial updates after each batch.
=> 4399: Remove ticket links from existing passive events

modules/ding_nodelist/js/rolltab.js
https://platform.dandigbib.org/issues/4393 
The code in the handler needs the data attribute and if it's missing it
will redirect to /undefined. This happens if you have a ding_nodelist
rolltab and a normal rolltab on the same page. The normal rolltab
doesn't have the data-attribute and the tabs will redirect to
/undefined, because the selector also targets those.
=> 4393: Fix broken tabs in rolltab

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/4274
Removing pane widgets from IPE menu:
- ding_event-ding_event_list_frontpage
- ding_event-ding_event_simple_list
- ding_groups-ding_group_overview_simple
- ding_news-ding_news_frontpage_list
=> 4274 by Inlead: Adjust IPE menu items.

modules/ding_availability/ding_availability.module, modules/ding_availability/js/ding_availability_labels.js, themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/sass/p2/p2-entity-buttons.scss
https://platform.dandigbib.org/issues/3800
* Hides holdings when not available
* Styling for new button for interlibrary loans
* Shows a message when the material is available for interlibrary loan
Buttons looks a bit odd on my local environment, however, this problem shows up without any changes from the current master branch:
=> 3800: Interlibrary loans (changes to core for the ding_ill module)

modules/ding_nodelist/js/carousel.js
https://platform.dandigbib.org/issues/4523
Error thrown by ding_nodelist carousel on Slick functionality initialization was breaking Ding IPE js functionality execution.
=> 4523 by Inlead: Fix nodelist carousel slick initialization.

modules/ding_debt/plugins/content_types/debts/debts.inc, themes/ddbasic/sass/components/form/form-class.scss, translations/da.po
https://platform.dandigbib.org/issues/4161
Adds Terms of service active accept as required by EU-law. More information on redmine: https://platform.dandigbib.org/issues/4161#note-12 
There was no styling of disabled buttons in our main theme, so I had to add that also.
I added a translation of "I accept the terms of service". Should I trigger a translation import in an update hook or is that something we take care of once each release?
=> 4161: Implement TOS active accept

modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/3826
This is some-what a temporally hack to get around issues with pre-authenticate in FBS and allow all types of users to use adgangsplatformen. 
No screenshot.
Please not that this hack requires that we disable the access token as soon as it has been used. The side effect is that the token can not be used later on to make request to the open-platform etc. This is due to security considerations and the information that the token now gives access to.
=> 3826: Use pin-code during the SSO process

themes/ddbasic/sass/components/node/news.scss, themes/ddbasic/sass/components/node/paragraphs.scss
https://platform.dandigbib.org/issues/4524
Flexbox styling removed from ting-object in paragraph blocks. It didn't seem to do anything, but was causing problems.
Widths for .paragraphs-block--carousel and .paragraphs-block--materials-list are changed to use grid function from the grid library, so they don’t break out of the grid.
Redundant media queries have been removed.
No further comments.
=> 4524: Styling corrections for paragraphs

themes/ddbasic/sass/components/header.scss
https://platform.dandigbib.org/issues/4519
The navigation wrapper is currently positioned under the topper when
shortcuts are displayed. Move it down to display it fully.
Once that is moved we can keep the search pane in the current
position.
Current state:
After with shortcuts closed
After with shortcuts open
=> 4519: Adjust header positioning when admin shortcuts are displayed

modules/ding_user/ding_user.module, themes/ddbasic/sass/components/form/form-user-login.scss
https://platform.dandigbib.org/issues/4514
The is an alternative to #1526 
Some sites use single singon systems such as Adgangsplatformen to
authenticate patrons but use standard Drupal users for library
personel.
We do not want to prevent these users from logging in event though
the use ding_user_form module might also be enabled.
Preventing such two modules from being enabled at the same time is
cumbersome so instead we remove the code which prevents users
from accessing /user.
This will allow library personel to log into the site regardless of
which modules are enabled.
In the current state form items are floated left. There does not
seem to be a reason for this. They are already in a container which
uses floats for positioning and they are positioned directly above/
below each other. …
=> 4514: Do no prevent access to /user

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.install
https://platform.dandigbib.org/issues/4173
Added hook_update() to restore Section "base" panel page settings to defaults from code.
=> 4173 by Inlead: Make sure default panel is reverted upon change.

themes/ddbasic/sass/components/form/form-search-sort.scss, themes/ddbasic/sass/components/panel/class-panel.scss
https://platform.dandigbib.org/issues/4332
Adjusted the sort select element on search-results to align with top of ting-search-backend-engines-form.
Also changed the font weight to use the correct typography.
The commit fail on ci/circleci: behat_tests, but since the PR only includes small changes to 2 scss files - i dont see why this PR should fail?
=> 4332: Align search results

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4150
In some cases the field-group-format-wrapper has a zero height in the 'group-on-this-site' accordion section of a ting-object. This causes the accordion to fail. A simple clearfix on the element solves the issue.
=> 4150: Fixed ting-object accordion wrapper

modules/ding_popup/ding_popup.info, modules/ding_popup/ding_popup.module, modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity/js/ding_serendipity.js
https://platform.dandigbib.org/issues/4520
This is an alternate take on #1531 
AJAX commands in Ding Popup requires the existence of the Drupal AJAX
core library. This is not handled by the current definition in the
.info file.
Such an error can block the execution of other JavaScript code e.g.
the handling of the top menu.
To address this we declare the code in ding_popup a library and with the AJAX
library as a dependency.
We load the library is currently loaded for all HTML responses as we 
cannot establish exactly where popups are invoked.
By searching through the codebase it seems as if the AJAX command 
defined in ding_serendipity is not in use. Consequently we remove it.
The error:
=> 4520: Prevent JavaScript errors in administration interface.

themes/ddbasic/sass/components/messages.scss
https://platform.dandigbib.org/issues/4153
Removed border-bottom from messages li.
=> 4153: Removed messages border

.circleci/config.yml
Builds currently fail because of missing libpng files. Try to update
Package index before installing.
=> Core: Update packages before installing on CircleCI

modules/ding_adgangsplatformen/ding_adgangsplatformen.module
https://platform.dandigbib.org/issues/4573
Use CPR when exists as users may have both (CPR and card no.)  attached to their FBS user and both can then be used to login at  adgangsplatformen. But pre-authenticate can't use the card no.  so fallback to CPR if it's given.
No screenshot.
No comments
=> 4573: Fallback to CPR when it exists from adgangsplatformen

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/4569
Initially Sections term pane had to clone predefined term_view variant, but something had gone wrong and panel page wasn't cloned correctly.
=> 4569 by Inlead: Sections are created with another section's content.

modules/ding_user_frontend/ding_user_frontend.module
https://platform.dandigbib.org/issues/4574
The users ID can be displayed in URLs and send to webtrekk. This correct the match index and ensure the URL is renamed to `/user/me`.
No screenshot.
No comments
=> 4574: Fixed index in matches in rename to /user/me

modules/opensearch/opensearch.client.inc, modules/opensearch/opensearch.module
https://platform.dandigbib.org/issues/4568
When search the data-well that static cache in opensearch do not return the same result if you make the same request within the same execution.
The `collection` part of objects changes inside the static cache between calls.
Cache content on first call:
Cache content on second call:
I'm not sure why we need to deep clone when setting the `$response` into the cache as all return statements are doing clone. But if you don't do this the object still changes between calls. I have test in both php 7.0 and 7.2 it's the same, so it don't seam to be an php error.
=> 4568: Deep clone opensearch static cache

modules/ding_app_content_rss/ding_app_content_rss.views_default.inc
https://platform.dandigbib.org/issues/4567
The view of the Ding App Content module for the News list was re-exported after Paragraphs was added as a field and replaced with Body field in the RSS fee.
=> 4567 by Inlead: Replace Paragraphs field with Body field in News RSS.

themes/ddbasic/sass/components/field.scss, themes/ddbasic/sass/components/node/news.scss
https://platform.dandigbib.org/issues/4599
Change margin on right column
=> 4599: Fix margin on right column

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/4597
When "overlay" is disabled, ting object teasers use h2 instead of h3. This is wrong and makes the title huge.
Before:
After:
=> 4597: Make ting-object teaser h3 instead of h2.

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.module, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
https://platform.dandigbib.org/issues/4604
In the current form opening hours are not displayed correctly for some libraries if they:
1. Have not altered the weights of the opening hours category terms
2. Do not use categories
Issue 1 is caused by the fact that the code e.g. L125 uses weights for array entries. However Drupal weights are not unique. Terms will get a unique weight once reordered by an editor butby default the weight of all terms is 0.  This will cause opening hours for one category to override others.
We handle this by generating a unique "weight" for each category. Categories with same Drupal weights are assigned an increasing weight to avoid collisions. Any subsequent collisions are handled by increased more weights. This should result in the same order as before but with …
=> 4604: Improve handling of "Closed" text for opening hours

modules/ding_campaign_plus/ding_campaign_plus.install, modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/4598
We should replace "Relevant Campaign" with "Relevant Campaign Plus" on frontpage and ding_section default page..
=> 4598 by Inlead: Replace "Relevant Campaign" with "Relevant Campaign Plus"

modules/ding_user/ding_user.module, modules/ding_user_frontend/ding_user_frontend.module
https://platform.dandigbib.org/issues/4612
This prevents uids from being picked up in trackers which can lead
to linking of user identity to specific user behavior.
Before this change users could access urls in the /user/uid format.
If not logged in then this url would display “page not found”. If the
user was logged in then this url would work just as well as the
preferred /user/me format.
To avoid these urls from being tracked we redirect immediately to
the frontpage for user pages without access and for users seeing
their own profile then redirect to /user/me.
Uids will still show up in urls where an administrative user accesses
another user but that is acceptable.
The change needed here can cause a lot of redirect trouble. I have 
tried to test the following combinations:
Active user …
=> 4612: Improve redirection to /user/me from /user/uid in urls

themes/ddbasic/sass/components/ding-tabroll.scss
https://platform.dandigbib.org/issues/4595
I've previously fixed issues with constrast, but it was a bit too much.
DDB has asked me to revert it so they can find a better design solution.
Reverting back to what it was before (despite issues with contrast):
=> 4595: Undo removing gradient from 4095.

themes/ddbasic/sass/components/ding-carousel.scss, themes/ddbasic/sass/components/ding-tabroll.scss
https://platform.dandigbib.org/issues/4597
In relation to a recent (?) update, various elements have broken when you choose "disable overlay" in the DDBasic theme settings.
This aims to fix them, as best possible.
=> 4597: Fix CSS issues with disable-overlay.

themes/ddbasic/sass/components/ding-tabroll.scss
https://platform.dandigbib.org/issues/4595
Multiple people must have been fixing the tabroll styling, because for some reason, the text has gone white with no dark background.
This sets the text back to dark.
=> 4595: Set tabroll color to dark again.

modules/bpi/bpi.images.inc, modules/bpi/bpi.module
https://platform.dandigbib.org/issues/4625
This PR restores the original flow for pulling images during syndication of new content from BPI service. There is a long history for this logic to be broken and this is restored via this change-set. Images from title/list image fields are placed correspondingly during syndication along with inline images inserted into body via WYSIWYG.
Relying on https://github.com/ding2/bpi-client/pull/16.
=> 4625 by Inlead: Adopt with recent service changes.

modules/ding_paragraphs/ding_paragraphs.module
https://platform.dandigbib.org/issues/4625#note-20
When running this code from the BPI workflow, the paragraph objects are not fully loaded. Resetting the entity cache here seems to fix the issue.
=> 4625: Reset paragraphs items cache in BPI workflow

modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/4212
This change should be merged together with: https://github.com/ding2/ting-client/pull/31.
Now that we handle missing object errors and not returning errors as real objects, there is now a chance that an object request will return NULL in the current state of the code.
[Our caching logic doesn't like this](https://github.com/ding2/ding2/blob/master/modules/opensearch/opensearch.client.inc#L509).
This is very fragile and I think the best course of action is to make TingClientObjectRequest return empty array if nothing was found, which I have implemented in https://github.com/ding2/ting-client/pull/31. 
It's still expected that we return NULL from opensearch_execute() if nothing was found, so this check is now needed.
If your change affects the user …
=> 4212: Return NULL as expected if no objects was found

modules/ding_user_frontend/plugins/content_types/user_overview.inc
https://platform.dandigbib.org/issues/4600
Fixes wrong link on overdue loans block.
=> 4600: Fix wrong link on overdue loans block

modules/opensearch/opensearch.module
DDBCMS-46
https://platform.dandigbib.org/issues/4627
I forbindelse med Inter-Library Loans modulet ("bestil-knappen"), fjernes filtrering på agency, hvorved mængden af poster i søgeresultatet øges markant. Dette gør det endnu sværere at lave en hensigtsmæssig rankering.
Derfor tilføjer vi en mulighed for at booste på agency.
=> 4627: Allow agency filtering

modules/ding_adgangsplatformen/ding_adgangsplatformen.module
https://platform.dandigbib.org/issues/4633
Not all Adgangsplatformen clients are configured to return a CPR - 
not even as an attribute with a NULL value. The current state will 
cause such clients to fail because CPR will still be used anyway and 
generate notices because it is not defined.
This PR updates the code accordingly to make such clients work again.
Behat tests fail for whatever reason. I will try rerunning them.
=> 4633: Make Adgangsplatformen handle non-privileged clients

modules/ding_adgangsplatformen/ding_adgangsplatformen.module
https://platform.dandigbib.org/issues/4752?next_issue_id=4748&prev_issue_id=4753#note-23
We rely on redirect responses which will pass the user along to
Adgangsplatformen if she tries to perform an action while not logged
in.
If the CTools AJAX responder is not loaded then the responder will be
returned and loaded as a part of the response. 
This has two problems:
1. The user is not redirected to Adgangsplatformen immediately but
must try to perform the action again.
2. The user is not redirected to the correct path e.g. when trying to
make a reservation.
Being aware of this we originally intended to include the AJAX
responder with every anonymous response but a refactor broke the
hook name which should ensure this.
Rename the function `ding_page_build()` to …
=> 4752: Ensure AJAX responder is loaded when using Adgangsplatformen

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/4763
The notification classes were a part of the P2 project and are no
longer available. Make the user menu title use existing classes which
are also used for menu items.
These do not have types per use case so we switch to the
success/warning variants that we already have.
Before
After
=> 4763: Use menu item classes for debts, overdue loans and reservations

modules/ding_adgangsplatformen/ding_adgangsplatformen.install, modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_adgangsplatformen/includes/ding_adgangsplatformen.admin.inc
https://platform.dandigbib.org/issues/4756
We currently use a separate secondary Adgangsplaformen client for
retrieving tokens without access to sensitive information. These 
tokens are suitable for use in client side applications.
However the secondary client is potentially shareable between 
installations and thus cannot be configured with a single valid 
logout url. This means that Adgangsplatform cannot redirect to the
correct site.
To address this we instead revoke the access token manually and then
generare a unique access token for an anonymous user using the
primary client.
We can then pass this token to Adgangsplatformen when logging out and
it will allow redirect to the corresponding site.
=> 4756: Use Adgangsplatformen authentication client when logging out

ding2.vcl, ding2_v4.vcl
https://platform.dandigbib.org/issues/4761
Never cache `ding_react/user.js` in Varnish.
This file contains a unique per user specific token and should not
be cached. However [our current Varnish configuration treats all files
ending in .js](http://github.com/ding2/ding2/blob/master/ding2.vcl#L74-L74) as a static file and strips cookies [no matter what
headers we send](http://github.com/ding2/ding2/blob/master/modules/ding_react/ding_react.module#L277-L277).
This results in the file always returning as if accessed by the
anonymous user.
To fix this we update the Varnish configuration to bypass caching of
this file.
This PR is alternative take on that is also proposed in #1593.
=> 4761: Never cache ding_react/user.js in Varnish

ding2.install
The deployed version of the installation contains a patch where the
update hook ding2_update_7075 is defined and containing the code to
enable ding_registration.
To maintain the order and ensure that all necessary update hooks are
executed we must renumber the update hooks so the follow after
ding2_update_7075().
=> Core: Reorder Ding2.install update hooks

modules/ding_react/ding_react.module
https://platform.dandigbib.org/issues/4799
We currently have two ways of authenticating users from
Adgangsplatformen against FBS:
1. SSO login. This occurs for most users
2. Certain users without CPR. These get the user id and password
from Adgangsplatformen and perform a normal authentication.
Both approaches will result in a user getting a valid token to use
With React components. However for the second type of users
ding_user_is_logged_in_with_sso() will return false.
This results in an inconsistent state where
window.ddbReact.userAuthenticated is false while
window.ddbReact.setToken() is called with a valid token.
To address this situation and make React components work for both
types of users we base both userAuthenticated and setToken() solely
on the existence of a token.
If you …
=> 4799: Authenticate react users via token availability - not SSO login

modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/4739
Ensure that search engines doesn't index pages under /user/*. We
also add nofollow since the login page contains links to other
pages under /user that are disallowed in robots.txt.
=> 4739: Add noindex, nofollow robots metatag on /user/* pages

modules/ting_search_carousel/plugins/content_types/carousel.inc, themes/ddbasic/utils.inc
https://platform.dandigbib.org/issues/4562
Stop it from accidentally cutting up multi-byte characters, resulting
in invalid UTF sequences, which the browsers might ignore (haven't
checked) but json_encode certainly chokes on.
Pre-populating the first page from server-side means doing the
rendering (not too bad) and hitting the availability service to check
if the material is available (can be pretty bad for pages with many
carousels).
=> 4562 async carousels

modules/ting_search_carousel/plugins/content_types/carousel.inc
https://platform.dandigbib.org/issues/4175
As we're loading covers asynchronously anyway, there's no need to seed
the cache, it only slows down submission.
=> 4175: Don't pre-request covers

modules/ting_reference/ting_reference.module
https://platform.dandigbib.org/issues/4720
Fixes issues when nodes hosting material list paragraphs items are unpublished/deleted.
If they are deleted we will get a fatal error trying to use non-existing host entity. As described in the case, this could also happen when unpublishing nodes, but I've not been able to reproduce this. As far as I can see, the `ParagraphsItemEntity::hostEntity` uses `entity_load` without any `$conditions`, so they should be loaded regardless of `$node->status` value. Anyway if it's possible somehow, this fix protects against that too.
Also discovered that the entity was loaded twice, and we can just use the host entity loaded by `ParagraphsItemEntity::hostEntity`. The `$condition` array we passed to the manual `entity_load` call before, had no effect since [it …
=> 4720: Fix ting object view error when unpublishing/deleting related nodes

ding2.make, patches/split-up-regex-2739023-1.patch
https://platform.dandigbib.org/issues/4653
Back-ported patch found at https://www.drupal.org/project/oembed/issues/2739023 to the version that we are using. We are using the lasted tagged version, but it seams that the module have moved on without any new releases.
**Note**: This will not build as the link to the patch in `ding2.make` do not exists before this have been merged.
No screenshot.
No comments.
=> 4653: Patched oembed - regular expression is too large

modules/ding_loan/plugins/content_types/loans.inc
https://platform.dandigbib.org/issues/3290
Some loaners are getting confused by the "You currently have no loans"-message that can be shown on both regular and overdue loans status. Even though one of them is not empty the message can still be show on the other status page, leading some loaners to wrongfully conclude, that they have no loans.
In this PR we provide separate and more specific translatable empty messages for regular and overdue loans.
=> 3290: add more specific empty messages on loan status

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
https://platform.dandigbib.org/issues/4780
A follow up to the solution from #1560.
It's good that we now place the "Closed" text based on the categories in use on the instances of the current week. But if there are no instances, we have no categories, and it will result in empty display (see screenshot below).
It's pretty hard to make any assumptions about the way the categories are used on the site. We could look at all instances, but that would be pretty extensive and what if some categories are only used in some weeks.
I therefore think that the best solution is to check for empty instances in the current week and fallback to the "NULL-category" only. See screenshot below for result.
=> 4780: Fallback to default category when no instances

modules/ding_reservation/js/ding_reservation_reservability.js
https://platform.dandigbib.org/issues/4765
jQuery.data() will try to process the data value to an appropriate
type and this “00123” becomes 123.
That is not desirable for us and thus we fall back to using the
simpler jQuery.attr() function.
“Every attempt is made to convert the attribute's string value 
to a JavaScript value (this includes booleans, numbers, objects, 
arrays, and null) […] To retrieve a data-* attribute value as an unconverted string, use the attr() method.”
https://api.jquery.com/data/#data-html5
=> 4765: Use jQuery.attr() instead of data() in reservability checks

modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/4579
When login in at eReolen we need more information from the login form and from adgangsplatformen to preform the login at the provider. This allow us to send this information via the `$user_info['extra']`in the call to `ding_user_authenticate` and forward that to the active provider.
No screenshot.
No comments.
=> 4579: Added optional extra to provider login call

modules/opensearch/opensearch.module
https://platform.dandigbib.org/issues/4522
In opensearch 5.2 the boost weight value must now be a positive number and a decimal between 0 and 1 should now be used for down ranking. Hence we can not use element_validate_integer anymore.
Drupal's element_validate_number will validate float, but since we also
need to validate positive, this is not sufficient. Drupal does provide a
element_validate_integer_positive, but as the name suggest this only
works for integers. Hence we implement our own element validate callback
which does both.
In the current solution the decimal separator must be dot and not comma as requested in the case. The comma separator is a convention in Danish number formatting, but opensearch uses dot separator like all other systems. One solution would be to use …
=> 4522: Opensearch 5.2 boost configuration update

modules/fbs/includes/fbs.availability.inc
https://platform.dandigbib.org/issues/4444
#1390 has introduced a minor error in shelfmark for music materials. The order of the if-elseif is important here, since music is a special case and we don't need to check dk5 classification fields for these materials.
Also ensure that we use the special area codes defined by danMARC2 when translating code from 039.b.
See: http://www.kat-format.dk/danMARC2/felter03.htm
=> 4444: Fix music shelfmark

themes/ddbasic/sass/components/node/campaign.scss
https://platform.dandigbib.org/issues/4367
For the campaign type "text", the header length is changed to be longer and the min-height is removed. For the campaign type "text-on-image", the text width is changed to be longer.
No further comments.
=> 4367: Header lenght changed and min-height removed

modules/ding_user/ding_user.admin.inc, modules/ding_user/ding_user.module, modules/ding_user_form/includes/ding_user_form.admin.inc
https://platform.dandigbib.org/issues/3583
Ensure that rows in the session table for providers users is removed if they are older than the value set in `ding_user_provider_session_expire` variable.
These rows contains sensitive information about library users so it's important that the session is cleaned up periodically. Especially now where the autologout module has been removed the probability for stagnant rows session has increased.
The module will clear session on cron runs as default. If a more frequent cleaning is needed, a lightweight cron endpoint is provided which only clears sessions. It might not be appropriate to use the normal cron for this if it's too frequent since it performs a lot of other operations.  
An alternative approach would be to implement a drush-command and …
=> 3582: Expire inactive provider sessions on cron run

modules/ding_ting_frontend/ding_ting_frontend.features.field_instance.inc, modules/ding_ting_frontend/ding_ting_frontend.field_group.inc, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/4555
Ding Webtrekk was failing to attach tracking event in hook_entity_view() because reservation (and also see online) button was added manually in theme layer. This was probably done because only a some ding_entity buttons is wanted in teaser views and not all returned by ding_entity_buttons hook.
I think the correct approach is to add the buttons in field config as with other view modes, so that other module have a chance to know they are there. Then any unwanted stuff must then be hanlded in the theme layer after this.
=> 4555: Fix reservation webtrekk event on teaser view

.circleci/config.yml, modules/ding_user/ding_user.module
Please add a link to the issue being addressed by this change.
We run the site using PHP 7.0 but the sites are deployed using Aegir
running PHP 5.6. Code which is incompatible with PHP 5.6 causes
deployments to fail.
To raise awareness of this we add a separat step to our CI pipeline
which lints files using PHP 5.6.
With the update [we can identify the error](https://circleci.com/gh/reload/ding2/5612)
and provide a fix.
With this change I also seized the opportunity to update the package we use for linting. [The previous version was abandoned](https://packagist.org/packages/jakub-onderka/php-parallel-lint).
=> 4579: PHP 5.6 compatability

.circleci/config.yml
https://platform.dandigbib.org/issues/4826
The behat search tests was failing because it was still using 5.0 of the testsite, which is no longer available. I didn't see this at first because it was set again further down the pipeline, and not only during initial install.
This PR fixes the behat tests and does some additional cleanup:
- Use 5.2 of test site and only set opensearch variables once during initial install.
- Update autocomplete settings used in behat tests.
- Use newest version of infomedia in behat tests.
- Remove setting of p2 variables in behat tests.
=> 4826: Fix behat tests and some cleanup

modules/ding_base/ding_base.info, modules/ding_base/ding_base.module, modules/ding_content/ding_content.module, translations/da.po
https://platform.dandigbib.org/issues/4743
1. Prevent webform from sending user submitted data unencrypted in emails. We replace the submission values token with the submission URL token in `hook_mail_alter()` if it's present. The mail is then just a notification that a webform was submitted, and the administrator must visit submission URL to download/inspect the data.
2. Insert a translatable privacy notice on the bottom of every webform (see screenshot).
=> 4743: Webform GDPR

ding2.install, ding2.profile, modules/ding_user/ding_user.info, modules/ding_user/ding_user.module, modules/ding_user/plugins/consent_storage/provider.inc, modules/ding_webtrekk/ding_webtrekk.install, modules/ding_webtrekk/ding_webtrekk.js, modules/ding_webtrekk/ding_webtrekk.module, project.make, themes/ddbasic/sass/components/cookie.scss
https://platform.dandigbib.org/issues/3585
- Updates EU Cookie Compliance module (ECC) to get new GDPR functionality and fix an issue with jQuery cookie library (see commit messages).
- Enable opt-in model: we now block everything incl. webtrekk by default until the user accepts.
- Add needed Drupal cookies to whitelist. Otherwise they would be blocked be by default or it the user doesn't consent.
- Webtrekk integration: use webtrekkOptOut cookie to completely deactivate. Set opt-out cookie as default in opt-in model. Listen for ECC agreed status change and set/remove opt-out cookie accordingly. Also send opt-out event when agreed status change to not accepted. Also whitelists webtrekkOptOut cookie in ECC.
- Enable withdraw consent banner. The user is able to withdraw after accepting. See …
=> 3585: Enable EU cookie compliance GDPR functionality

modules/fbs/fbs.module
https://platform.dandigbib.org/issues/4811
PR #1603 has rendered this missing, since it was added to the now
removed provider holdings form.
We re-add it to the FBS provider form, where it's perhaps better
placed, since the configuration is specific to this provider.
=> 4811: Re-add missing holdings suffix configuration

modules/ting_reference/ting_reference.module
https://platform.dandigbib.org/issues/4720
Fix error when viewing materials that has been attached to deleted nodes in paragraphs material lists.
It's only the node's field cache that is cleared when a ting_reference field is deleted. The ting_object's field_cache data will keep pointing back to paragraph/node until next cache flush, which will give error. 
It could take long before next cache flush, so in this PR we also attempt to clear the related ting_object's field cache, when ting_reference field is deleted.
To be safe we will still keep the empty-checks in the field formatter, to ensure we could load the referenced entity.
If you have any further comments or questions for …
=> 4720: Fix error on deleted relation nodes

ding2.install, modules/ding_availability/ding_availability.module, translations/da.po
https://platform.dandigbib.org/issues/4614
A follow up to #1603.
- Do not attempt to render holdings row or show any other availability information if provider didn't return any holdings. Instead we show an alternate empty text that can be translated. (see screenshot below).
- Only show reserved text if there was any reservable.
- Add translations and update.
Instead of:
=> 4614: Periodical holdings - Follow up

modules/ding_contact/ding_contact.module
https://platform.dandigbib.org/issues/3659
1. Inserts a hardcoded privacy notice on contact form advicing users not the insert personal data.
2. Remove user cookies set by contact module (se commit message for details).
We can not prevent users from entering personal data, pin etc. and this getting send out unencrypted to various mail servers, but this should make them think twice before hitting that submit button :)
=> 3659: GDPR contact form

themes/ddbasic/scripts/ddbasic.common.js
https://platform.dandigbib.org/issues/4789
The click handler was getting the data-href from it's outer scope, resulting in it always using the value from the first matches. In case of multiple nodelist promoted nodes on one page, this would make them all point to items in the first one.
To solve this we get the data-href directly from the clicked itemwrapper in the click handler.
=> 4789: Nodelist promoted nodes link issue

modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/4707
Use separate query parameter for campaign click tracking.
=> 4707: Use separate query parameter for campaign click tracking

modules/ding_news/ding_news.info, modules/ding_news/ding_news.install, modules/ding_news/ding_news.strongarm.inc
https://platform.dandigbib.org/issues/4659
We currently have a variable set which marks news for publication in
app by default.
The current default is that content is not published by default.
Unset this variable to make news follow this default. Also clean up
after Features which managed this variable previously.
Behat tests involving searches currently fail. See #1628.
=> 4659: Do not publish news to app by default

modules/ding_ting_frontend/ding_ting_frontend.field_group.inc, modules/ting/ting.module, modules/ting_search_carousel/plugins/content_types/carousel.inc, themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/4622
Also see: https://platform.dandigbib.org/issues/4562
- Fix error in field group export.
- Fix missing reservation buttons in carousels.
- Only show "Other formats" button on entity path (explanation in commit message).
- Hide add to list button from in teaser views.
Since `hook_ding_entity_buttons()` shows all buttons, it's up to the implementer to ensure it's displayed correctly in the different view modes in frontend. Otherwise it will have to be removed in theming, like the approach in this PR.
=> 4622: Fix carousel material display

modules/ding_varnish/ding_varnish.module
https://platform.dandigbib.org/issues/4577
Minor issues with newer version of varnish (5 - can use the same VCL file). So always set the `X-Drupal-Roles` in responses to ensure that they are available in "back response" in varnish when using vary header to hash and cache.
Also clean up headers with " " so they are formatted the same as nginx and apache do.
No screenshot.
=> 4577: Always add x-roles header

ding2.install, modules/ding_contact/ding_contact.module, translations/da.po
https://platform.dandigbib.org/issues/4290
If a user is logged in and fills out the contact form, the username is not displayed in the body, only the user link.
This is not great for the workflow of the librarians, so this adds the email regardless.
See examples here of how it is right now:
=> 4290: Make sure contact email body shows user email.

modules/ding_content/ding_content.info, modules/ding_content/ding_content.install, modules/ding_frontend/ding_frontend.info, modules/ding_library/ding_library.info
https://platform.dandigbib.org/issues/4033
DDB CMS has very limited comment integration and the styling is currently all over the place (see screenshot below). To use it properly would require adjustments that webmasters are not able to make. It therefore makes sense to disable it as standard.
Another is issue that it's very easy to turn on comments by accident as described in the case.
The easiest approach is to make the comment module optional by removing dependencies and just disable it.
DDB CMS has some comment integration in ding_user and comment related strongarmed variables. We'll keep these, since they do not cause any issue with the comment module disabled, and if any library was actually using comments, they can just enable it again and everything will work as usual. 
If you …
=> 4033: Make comment module optional and disable

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4827#change-48140
Align action buttons on material
I see that the react component for the `Add to list` button/function does not use the class .action-button but tries to mimic the styles instead. This should be addressed in another issue since it does not follow the styleguide and it breaks in mobile view.
=> 4827: Align layout for action buttons

modules/ding_provider/connie_openplatform_token/connie_openplatform_token.module, modules/ding_react/ding_react.module, modules/ding_react/plugins/content_types/related_materials.inc, modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc, modules/ting/src/TingObjectInterface.php, themes/ddbasic/sass/components/ding-react.scss
https://platform.dandigbib.org/issues/4764
This PR adds a new React app displaying related materials for an object on the object page.
To make this work for anonymous users were we need to access OpenPlatform without a token for an authenticated user we pull in support for agency tokens for #1617. Note that if that PR is updated and merged this will likely result in conflicts for us as well.
Scrutinizer comments are either "imported" through 6f1f54b or contradictory.
=> 4764: Related materials

project.make
https://platform.dandigbib.org/issues/4864
There was an missing `t` in the directory name for the TUI color picker in the `project.make` file. So the library is never load and the image editor fails loading doing to the new missing dependency.
No comments
=> 4864: Updated TUI color picker directory name in makefile

modules/ding_libs/ding_libs.module, project.make
https://platform.dandigbib.org/issues/4864
During code review etc. the path in ding_libs do not match the one in the makefile.
No screenshot.
No comments.
=> 4862: Updated upload php client libraries path

modules/ding_react/ding_react.admin.inc, modules/ding_react/ding_react.module, modules/ding_react/plugins/content_types/checklist.inc, modules/ding_react/plugins/content_types/related_materials.inc
https://platform.dandigbib.org/issues/4793
This PR allows the React components to use the new version of the Cover service.
The change in itself has multiple dependencies:
- The React components themselves were updated to support the new Cover Service version with danskernesdigitalebibliotek/ddb-react#97. This change is included in the `latest` version of the package and an upcoming version 2.0 which will be tagged when tagging the next release of this project.
- The new version of the Cover service requires authentication. This has been implemented in danskernesdigitalebibliotek/ddb-react#96 as well as in #1630 were we need it to provide library level authentication against services for unauthenticated users.
The actual changes related to the issue is thus only related to bringing the …
=> 4793: Use Coverservice v2 for React components

.platform/routes.yaml, ding2.install, ding2.profile
https://platform.dandigbib.org/issues/3585
When users are logging in their consent should be migrated from the 
anonymous user to the current user.
Currently this does not seem to occur in testing environments due to 
configuration problems related to the cookie compliance module. 
The values we set in the default configuration must include all values
expected when reading the configuration again. The module will not
provide any sane defaults. This may result in warnings as well as
errors.
If the cookie_name variable is not set then we will not be able to
migrate cookie consent from an anonymous user to the authenticated
user on login.
To test this on Platform.sh we have to disable the HTTP cache as it will
strip cookies - even for the POST requests that are used during login.
This …
=> 3585: Fix migration of cookie consent when logging in

modules/ting_smart_search/extras/parse_auto_data.php, modules/ting_smart_search/includes/ting_smart_search.admin.inc, modules/ting_smart_search/ting_smart_search.module
https://platform.dandigbib.org/issues/4362
Three small fixes. A lower limit on the number off clicks we use in automatic boosting. A bug fix off sometimes wrong order off automatically boosted materials and a help text under the view local smart search records in the admin page.
=> 4362: Small fixes to ting_smart_search

ding2.vcl, ding2_v4.vcl
https://platform.dandigbib.org/issues/3585#note-84
This will prevent any Varnish processing of the request including
stripping of any cookies which contain information about the
consent id of the user.
If the cookie containing the consent id is stripped then it cannot
be migrated from an anonymous user to the authenticated user during
login.
=> 3585: Pipe Adgangsplatformen callbacks through Varnish

modules/ting_search/plugins/content_types/search_backends.inc
https://platform.dandigbib.org/issues/4764#note-26
Some characters may be valid CQL and thus work when searching for
materials but cause problems when used for CMS content search. One
example of such a character is ‘. When included in the search keys
a database error will occur such as:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an
error in your SQL syntax; check the manual that corresponds to your
MySQL server version for the right syntax to use near '%' AS w0,
t.word LIKE '%potter'%' AS w1 FROM
search_api_db_default_multiple_ind' at line 1
```
Tracing this error goes deep into the Drupal database layer and
without a proper fix.
The simplest way to address this seems to be to just strip the
characters.
Before the change the following error was shown: …
=> 4764: Strip certain characters from keys before performing DB search

modules/ding_react/plugins/content_types/related_materials.inc, themes/ddbasic/sass/components/ding-react.scss
https://platform.dandigbib.org/issues/4764#note-33
If there are no subjects then we have very little data to work with
when trying to retrieve relevant materials. Consequently the
suggested materials will not seem very relevant.
=> 4764: Do not show related materials for objects without subjects

modules/ding_react/plugins/content_types/related_materials.inc
https://platform.dandigbib.org/issues/4764#note-47
Separate multiple values passed to React components using , instead of wrapping in '. This matches updated component argument handling and other components.
=> 4764: Related materials update query

modules/ding_app_content_rss/ding_app_content_rss.views_default.inc, modules/ding_event/ding_event.module
https://platform.dandigbib.org/issues/3916
The motivation for the changes in this PR started with the goal to support including multi day events in the app feed. 
In https://github.com/ding2/ding2/pull/871 the ability to show multi day events on the frontpage and on the event list was added. Normally events are only shown when start date is less than or equal to current date. But in above PR a settings was added to ding_event content type, that gives administrators the ability to show these events also when end date is less than or equal to current date.
Unfortunately, this was implemented in a way that is dependent on the order of the views filters from the view UI. Several issues with this has been reported. For example see: https://platform.dandigbib.org/issues/3442. I also found out …
=> 3916: Refactor event list filter to be independent of filter order

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/4813
https://platform.dandigbib.org/issues/4792
https://platform.dandigbib.org/issues/3047
Adds preprocess image function that checks for alt attribute and sets an empty one if none exists. All images go through this function before being rendered so we cover all instances of missing alt image with 5 lines of code.
=> 4813: Added image preprocess function

themes/ddbasic/templates/node/node--view-mode--search-result.tpl.php
https://platform.dandigbib.org/issues/4400
The $node_url variable has already been passed through Drupal's url function in template_preprocess_node(), which means it has been passed through rawurlencode once. So instead of using that, we manually construct the node uri and pass that to l-function.
=> 4400: Avoid double rawurlencode on "Read more"-link

modules/ding_frontend/ding_frontend.pages_default.inc, modules/ding_library/ding_library.features.field_instance.inc, modules/ding_library/ding_library.pages_default.inc, themes/ddbasic/sass/components/node/eresource.scss, themes/ddbasic/templates/node/node--webform.tpl.php
https://platform.dandigbib.org/issues/4193
Fixes the main header on libraries, webforms and e-resources to be a H1 and properly styled.
=> 4193 headlines

modules/ding_campaign_plus/modules/ding_campaign_plus_search/ding_campaign_plus_search.module
https://platform.dandigbib.org/issues/1519
Spurious query errors show up on sites. Turns out that ding_campagin_plus_search does a search where it takes the existing query and wraps it in double quotes before adding it's own extesnions. But this fails horribly when the query already
contains double quotes. Change to parenthesises.
=> 1519: Fix ding_campagin_plus_search's query munging

modules/ding_campaign_plus/modules/ding_campaign_plus_search/ding_campaign_plus_search.module, modules/opensearch/opensearch.client.inc
https://platform.dandigbib.org/issues/1519
Makes user visible errors from opensearch translatable. Goes together with https://github.com/ding2/ting-client/pull/33
Different errors are categorized by ting-client into syntax or internal errors depending on error message. This PR adds generic translatable error messages for these types. Also, it only shows each error message once.
And a bit of code style cleanup.
=> 1519 translatable errors

modules/ding_nodelist/ding_nodelist.module, modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/4913
Fix sloppy code, comparing DateObject to timestap, and missing parameters to `ding_user_is_provider_user()`, which all causes notices.
=> 4913 fix notices

project.make
https://platform.dandigbib.org/issues/4854
Add patch to make opening_hours clean up opening hours when nodes are deleted. Has an update hook that cleans out orphaned opening hours.
=> 4854: Clean up opening hours for deleted nodes

modules/ding_user_form/js/ding_user_form.js
https://platform.dandigbib.org/issues/4772
For some reason the current version uses nested behaviors: `open_login`
is defined within `ding_user_form()`. This means that `open_login` is
only attached after `open_login` has been attached.
This is unnecessary and we might just as well expand the selector 
from `open_login` to the current selector in `ding_user_form`.
=> 4772: Fix action links triggering login form for anonymous users

modules/ding_mobilesearch/ding_mobilesearch.module
https://platform.dandigbib.org/issues/4762
Fix tags with NULL value in mobilesearch export.
When using `field_get_items()` it will only return the term ID. To get the name of the term we need to load the full term object with `taxonomy_term_load()`. See the changes here: https://github.com/ding2/ding2/pull/1665/commits/952f82cf45cd66ba279dd00efe58a48026f7a28b
Also fixes some potential `Invalid argument supplied for foreach` Warnings in the export code.
=> 4762 mobilesearch null tags

project.make
https://platform.dandigbib.org/issues/4592
Global redirect uses the wrong variable when checking for maintenance mode, which has resulted in an error that was very hard to debug.
Also, if the module checks the wrong variable it will redirect in mainetenance mode which is shouldn't.
Additionally, by updating to latest version, we can remove a patch in make-file since these changes are included in the latest version.
The module contains a new configuration option to redirect comment URL's to their parent node. Since we're not using comments, we will just use the default value which is off.
=> 4592 update globaleredirect

modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc, modules/ting_search/plugins/content_types/search_help.inc
https://platform.dandigbib.org/issues/4493
Replaces custom content with a content type that translates strings.
=> 4493: Make search help translatable

modules/ding_loan/plugins/content_types/loans.inc
https://platform.dandigbib.org/issues/4814
The loan list should be cached in session cache, but currently the cache key is stored under a not used key.
This actually stores the list in cache.
No screenshot.
No comments.
=> 4814: Fixed loan list cache

themes/ddbasic/sass/components/node/eresource.scss
https://platform.dandigbib.org/issues/4800
Styles the tags on eresources.
Before: 
After:
=> 4800: Fix eresource tags styling

themes/ddbasic/sass/components/field.scss
https://platform.dandigbib.org/issues/4116#change-49550
Add `padding: 0` to the `ul` element. The default styling adds some padding for the bullets we don't use.
=> 4116: Remove padding from "on the site"

project.make
https://platform.dandigbib.org/issues/4783
Update CKEeditor JavaScript libraries to v4.14.0
The problem existed in CKEditor module for Drupal, not in JavaScript libraries with the same names, so it's not critical.
- [x ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
=> 4783: update CKEditor to 4.14.0

ding2.install, ding2.profile
https://platform.dandigbib.org/issues/4917
- Ensure popup agree button message can be changed.
- Update default text on popup agree and disagree buttons.
=> 4917: Update cookie popup agree and disagree buttons text

tests/behat/features/bootstrap/Page/ObjectPage.php
https://platform.dandigbib.org/issues/4975
We see multiple failures where a cover cannot be found even though
the subsequent screenshot shows the cover as expected. However Covers
may be loaded asynchronously and may not yet be ready when the test
is conducted.
Consequently we wait a bit. This is the same approach taken on the
search page.
Note that even if this test passed there is no guarantee that it actually fixes the issue. Not all tests are affected by the problem.
=> 4975: Wait up to 5 seconds when checking for object covers.

themes/ddbasic/sass/base/form.scss
https://platform.dandigbib.org/issues/4397
Change the way we style checkbox and radiobuttons
This is a generel solution to issues with non accessible checkbox and radio form elements.
=> 4397: Change styling for checkboxes and radiobuttons

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/js/node_blocks.js, modules/ding_nodelist/sass/ding_nodelist.scss, themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/scripts/node/event.js, themes/ddbasic/scripts/node/news.js, themes/ddbasic/scripts/ting-object/ting-object.js
https://platform.dandigbib.org/issues/4896
The combination of CSS hover effects and JS driven hover effects
causes odd behaviour.
Remove the JS hover effect, the CSS one is just fine.
=> 4896: Remove JS hover class

modules/ding_paragraphs/ding_paragraphs.features.field_instance.inc, themes/ddbasic/sass/components/node/paragraphs.scss, themes/ddbasic/scripts/ting-object/ting-object.js
https://platform.dandigbib.org/issues/4638
Make the material overlay for full width materials move to the left, and not quite so much, so it should stay in
the viewport.
=> 4638: Fix single material overlay

modules/ddb_cover_upload/css/ddb_cover_upload.css, modules/ddb_cover_upload/ddb_cover_upload.module
https://platform.dandigbib.org/issues/4866
Remove button on frontpage carousel
=> 4866: Add css to hide coverupload button on carousel

.circleci/config.yml
https://platform.dandigbib.org/issues/4915
These do not use HTTPS so we cannot use “SameSite=None”.
Setting an empty variable is tricky with drush so we have to use
eval instead.
=> 4915: Do not use samesite for tests

themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/scripts/view.js
https://platform.dandigbib.org/issues/4983
Fix JS syntax error and properly style events and news pages checkboxes. Apparently the latter was `display: none` until someone decided to do it properly for facets but forgot to check other pages.
=> 4983 bugfixes

modules/ding_tabroll/js/ding_tabroll.js
https://platform.dandigbib.org/issues/4803
Mobile browsers leaves the focus hanging on the button after
clicking (really, desktop browsers ought to too?), which means that
the rolltab will stay paused after pressing play. Fix it but ensuring the 
handlers aren't added to the play/pause button.
=> 4803: Don't pause tabroll on pause button focus

modules/ding_react/ding_react.module
https://platform.dandigbib.org/issues/4996
Change default URL for material list and follow searches to use productions URL's.
Removed the old PROD/TEST/STAGE constants for the URL's and just use one for each.
=> 4996: Change default URL for material list and follow searches

modules/ding_app_content_rss/ding_app_content_rss.rules_defaults.inc, modules/ding_app_content_rss/ding_app_content_rss.views_default.inc, modules/ding_event/ding_event.features.field_instance.inc, modules/ding_event/ding_event.views_default.inc
https://platform.dandigbib.org/issues/3916
For old events the event list filter might not be set at all. For some reason this filters them out of event feed even when mobile flag is set.
Turns out we can fix this by adding a not null check filter to second views filter group, before the filter that actually checks the value. Otherwise it must give some query error resulting in the whole row being discarded. See screenshot below.
Additionally the feature export also includes some cleanup:
1. Remove body field from news rss feed views export. This was not
done in #1540.
2. Some rules config and other export was refactored. Better keep it as
features exported it to avoid getting overriden status.
=> 3916: Add event list filter not null check to views filter

modules/ding_base/ding_base.module
https://platform.dandigbib.org/issues/4989
Just discovered this when doing a `drush fra -y` and thought I would provide a quick solution.
The object passed will not an instance `Entity` but `stdClass`.
=> 4989: Remove type hint causing issues

modules/ting_subsearch/ting_subsearch.module, modules/ting_subsearch/ting_subsearch_suggestions/ting_subsearch_suggestions.module
https://platform.dandigbib.org/issues/4991
Add subsearch overview page as default tab.
Also change suggestions admin settings form to normal tab, so that
it doesn't stand out compared to the other subsearch modules.
=> 4991: Add subsearch overview page as default tab

modules/ding_contact/ding_contact.pages_default.inc, modules/ding_event/ding_event.pages_default.inc, modules/ding_library/ding_library.pages_default.inc, modules/ding_library/plugins/content_types/menu_title.inc, modules/ding_news/ding_news.pages_default.inc, themes/ddbasic/templates/panel/panels-pane.tpl.php
https://platform.dandigbib.org/issues/4964
Fixes heading levels on pages and blocks (from `h2` to `h1`) on 
* `/biblioteker`
* `/contact`
* `/nyheder`
* `/arrangementer`
=> Issue 4964: Heading levels

modules/ding_contact/ding_contact.module
https://platform.dandigbib.org/issues/4559
Update the From and Sender mail headers sent from the contact form. It appears that some mail clients have issues with the current format.
Old:
Sender: SITENAME
From: "SUBJECT via SITENAME" \<SITEMAIL\>
New:
Sender: SITEMAIL
From: "SITENAME" \<SITEMAIL\>
=> 4559: Update mail headers contact from

modules/ding_react/plugins/content_types/related_materials.inc
https://platform.dandigbib.org/issues/4976
The getAudience() method can return FALSE if there's no data, giving a fatal error on the example presented in the case, because of the type hint.
Seems instance of OpenSearchTingObject doesn't follow the doc of TingObjectInterface and can both return array or false where
as the doc for the interface says string is returned. We therefore cannot count on data being an array.
I suggest to change to formatting function to handle all cases and remove type hint.
=> 4976: Fix related materials carousel error

modules/ding_availability/ding_availability.field.inc, modules/ding_availability/ding_availability.module, modules/ding_availability/js/ding_availability.js, modules/ding_reservation/ding_reservation.module
https://platform.dandigbib.org/issues/4969
The changes from #1603 has resulted in some potential errors when making periodical reservations. Since periodical holdings is now pulled in async via AJAX, we now have to take extra care that everything is done right, since these holdings can now contain 'use-ajax' - reservation links:
1. Ensure Drupal AJAX script is loaded when holdings field is rendered on initial page request. We cannot do this in the AJAX-callback.
2. Call `drupal.attachBehaviors()` when recieving holdings HTML. This was not done before, but since holdings can now contain 'use-ajax' links it has consequences.
Additional I've removed all unneeded HTML IDs in periodical holdings HTML. For some periodicals with many issues it could result in a lot HTML IDs being posted back in …
=> 4969: Fix periodical reservation issue

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/4283
Remove empty "add one more" place2book ticket on the field widget.
=> 4283: Remove empty "add one more" place2book price

project.make
https://platform.dandigbib.org/issues/5010
For some reason ECK fails after a clean install - currently seen on
Platform.sh. The issue is hard to track down but based on the
community patching the module seems to be the way to go for now.
=> 5010: Patch ECK to avoid PDOException

.circleci/config.yml, tests/behat/docs/p2/services-mock.md, tests/behat/features/bootstrap/LibContext.php
oss-services.dbc.dk has been shut down. This causes our tests to
fail.
=> Core: Run tests on opensearch.addi.dk

modules/ding_webtrekk/ding_webtrekk.js
https://platform.dandigbib.org/issues/4912
Uses no cookie tracking with Mapp if:
1.  Opt-in model and user hasn't agreed.
2. Opt-out model and user hasn't disagreed.
Ofcourse we have to use opt-in model, but I thought it was good to keep support for opt-out - at least for demonstrative purpose.
Also removes the old method of blocking Mapp tracking with webtrekkOptOut cookie. I have kept the optOut cookie in the ECC whitelist though to keep support for the old method.
=> Switch to no cookie tracking

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/5005
When adding terms, the new variants wasn't properly cloned, resulting in sections sharing content.
Try cloning like `page_manager_handler_clone_submit()` does it instead.
=> 5005: Clone page handler properly

tests/behat/features/searching/01-searching.feature
This start failing as search results containing works are sorted by
objects which are not immediately visible from the search result
page. The current implementation of the test checks on years on the
search page and thus fail.
Temporarily disable the test while we figure out whether the current
behavior is intentional.
=> Core: Disable test of sorting search results by publication date

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/5031
Don't disable field_term_page on section forms.
It caused the term page to be disabled on second save. Why one would
want to disable it in the first place is unknown.
=> 5031: Don't disable field_term_page

.platform.app.yaml
https://platform.dandigbib.org/issues/5035
This ensures that permissions in the environment always reflect what
is defined in the codebase.
The procedure should match the deployment procedure in production
environments.
=> 5035: Rebuild permissions when deploying to PR environments

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_session_cache/ding_session_cache.module
https://platform.dandigbib.org/issues/5061
After changes to the session cache set in loans list (https://github.com/ding2/ding2/pull/1618) so loans are cached. A cache key is used with set that is not available when clearing cache. So wildcard clear is added in this PR.  
No screenshot.
=> 5061: Added support for wildcard session cache clear

modules/ting_subsearch/ting_subsearch_bibdk/ting_subsearch_bibdk.module
https://platform.dandigbib.org/issues/5068
This PR fixes two issues with the bibdk subsearch mechanism:
1. Since opensearch tries to predict cache by putting collections
from the search result in cache, the bibdk subsearch would result
in full bibdk collections later being shown to the user. As a
solution we implement hook_opensearch_cache_key_alter() and alter
the cache key if bibdk subsearch is currently being performed.
2. We currently turn off bibdk subsearch immediatly after the
subsearch is performed. This means that collections will be
fetched without bibdk agency and profile. This actually relied
on bug 1. to work, but when it's fixed the bug manifests by
displaying empty collections. The solution is turn off bibdk
subsearch after we have fetched collections.
Also refector the …
=> 5068: Fix bibdk subsearch

modules/ding_place2book/ding_place2book.module, modules/ding_place2book/lib/p2b/P2b.php
https://platform.dandigbib.org/issues/4582
Before every option not found on event node that was not 'name' was
incorrectly using the address field to look for phone number on library
node. Therefore the phonenumber was never actually send to p2b API, but
instead the translated value of 'None'.
This PR changes the logic so that we used the correct field_name. 
Also ensure that we send empty string if we can't find value as expected by the p2b API.
It looks like we have never send the phone number, regardless of whether it's set on library phone field, and p2b API have just started to react on this now. I have verified this by looking at what is send from our production site, which is still using last release:
```
[address1] => Willy Sørensens Plads 1
[address2] =>
[postal_code] => 7100 …
```
=> 4582: Ensure we use correct field to get phone number

modules/ting_covers/ting_covers.module
https://platform.dandigbib.org/issues/5054
Cache bin was set to false, which is just wrong.
=> Remove wrong bin argument

themes/ddbasic/sass/components/header.scss
https://platform.dandigbib.org/issues/4953
Right now, the search bar is hidden by a combination of z-index and absolute positioning. I have added visibility: hidden to the class: extended-search-is-not-open
No screenshots
No comments
=> 4953: added visibility hidden to search-is-not-open

modules/ding_user/plugins/content_types/profile2/profile2_form.inc
https://platform.dandigbib.org/issues/4936
Attempt to prevent browser from auto filling the password update fields  as this can cause unnecessary issues with form validation, which might confuse users.
=> 4936: Prevent auto fill on password confirm elements

translations/da.po
https://platform.dandigbib.org/issues/5106
Drupal uses button texts to determine which button was clicked.
This leads to problems when multiple buttons have the same text.
Drupal cannot figure out which button was clicked and will choose 
whatever.
This leads to problems which can be experienced on the Webform
components page. Here you cannot add more components than one as it
contains both an Add and a Save button. Both are translated to Gem.
Consequently Drupal always acts as if the Save button was clicked.
Actually the translation of Add is a duplicate so we just remove it.
The problem only seems to occur for newly installed sites so there
is no reason to run an update hook.
=> 5106: Remove duplicate translation of string to "Gem"

modules/ding_content/ding_content.info, modules/ding_content/ding_content.module, modules/ding_frontpage/ding_frontpage.info, modules/ding_ipe_filter/ding_ipe_filter.module, modules/ding_nodelist/plugins/content_types/ding_nodelist.inc, modules/ding_sections/plugins/content_types/ding_sections.inc, modules/ting_search_carousel/plugins/content_types/carousel.inc
https://platform.dandigbib.org/issues/5073
Add some modification to panels configure forms, when they are added directly in frontend with Panels IPE.
The goal is to promote better accessibility by requiring title and nudging administrators to provide a better more specific one. Also enforce h2 tag for title.
Administrators with access to page manager backend will still have all options to omit title and use different title tag.
There is a minor issue with using required on the title field: if title field is empty the ajax button to add a carousel tab will fail silently. We therefore insert the panel's content type's default title (with ctools %title token) as default value to minimize to chance of this happening. Using the default title when title field is empty is also the current …
=> 5073: Enforce h2 and panel titles when using IPE

ding2.install, ding2.profile
https://platform.dandigbib.org/issues/5026
Again we make a backup of existing cookie page to avoid deleting anything added by administrators.
Also add new Add `ding2_update_cookie_page()` function.
=> 5026: Update default text on cookie page

themes/ddbasic/templates/node/node--ding-news--view-mode--teaser.tpl.php
https://platform.dandigbib.org/issues/4931
For better accessibility we add aria-labelledby to news list article elements, pointing to the title of the element.
Screenshot of code and enabled Wave extension.
=> 4931: Add aria-labelledby to news list article elements

modules/ding_react/ding_react.admin.inc
https://platform.dandigbib.org/issues/4774
Remove user openlist status check in admin interface
This is no longer needed as we expect most users to be migrated by
now.
=> 4774: Remove user openlist status check in admin interface

modules/ting_field_search/ting_field_search.module, modules/ting_subsearch/ting_subsearch.module
https://platform.dandigbib.org/issues/4126
**THIS PR WILL NOT WORK WITHOUT** : https://github.com/ding2/ting-client/pull/30
Ting field search needs to take care only to alter targeted requests in `opensearch_pre_execute()` implementation. For search pages that is all search requests performed in the `search_result` pane and for material views (ting_object/ting_collection) we want to target the request for the main object of the page.
This PR introduces two mechanism for controlling this:
1. A new `hook_ting_field_search_alter_request($request)` which modules can implement to help decide whether request should be altered by returning a boolean. If anyone returns FALSE the request will not altered. If none returned FALSE and at least one returns TRUE request will be altered.
2. A static …
=> 4126: Alter request hook

modules/ding_availability/ding_availability.field.inc, modules/ding_availability/js/ding_availability_labels.js
https://platform.dandigbib.org/issues/3437
Fixes ding availabilty types display. 
When there are online types in the collection all types will currently be displayed as online.
The main problem is in frontend where it will always use the `js-online` container if it's present.
But there was also an incorrect assumption made in backend, where all entities of a type in a collection would be considered online if the first one was.
This PR fixes both issues and also some cleanup.
Check commit and code comments for details.
This PR is closely related to #1750, so we might have som conflicts.
**Before fix**
**After fix**
=> 3437: Fix availability types for collection with online entities

modules/ding_mobilesearch/ding_mobilesearch.module
https://platform.dandigbib.org/issues/4762#note-23 (follow-up issue)
Paragraphs are now also added to the export mapping in
ding_mobilesearch export hook implementation.
Also move the field data extraction code for common fields to a
separate function and use that for both node and paragraphs_item
entities. It was the easiest way to reuse all the special handling for
each wiget type.
```
"id": "6007741d841d44231cf93ae3",
"nid": 41,
"agency": "763000",
"type": "ding_news",
"fields": {
"ding_news_groups_ref": {
"name": "Groups",
"value": [
"Faglitteratur - uhmm!"
],
"attr": []
},
"field_ding_news_lead": {
"name": "Lead",
"value": "Curabitur eu nibh ac purus sagittis molestie consectetur nec dolor. Nunc sed scelerisque dolor. LOL",
"attr": []
},
"field_ding_news_list_image": {
"name": "List …
```
=> 4762: Ding mobilesearch paragraph export to CMS content

.platform.app.yaml, modules/ding_config_import/README.md, modules/ding_config_import/ding_config_import.info, modules/ding_config_import/ding_config_import.module, modules/ding_config_import/example.config.yml, modules/ding_libs/ding_libs.module, project.make
https://platform.dandigbib.org/issues/4925
Import configuration via YAML file upload (with/without flattening the arrays, mostly for readability for PL's). The modules comes with an YAML example file and readme about the modules usage.
=> 4325: Config import (yaml)

modules/ding_debt/ding_debt.admin.inc, modules/ding_debt/ding_debt.install, modules/ding_debt/ding_debt.module, modules/ding_debt/plugins/content_types/debts/debts.inc, modules/ding_provider/ding_provider.debt.inc, modules/ding_user_frontend/ding_user_frontend.pages_default.inc, modules/fbs/includes/classes/FBSFakeHttpClient.php, modules/fbs/includes/classes/FeesResponse.json, modules/fbs/includes/fbs.debt.inc, modules/fbs/tests/DebtProviderTest.php, themes/ddbasic/sass/components/form/form-class.scss, themes/ddbasic/sass/components/form/form-status.scss, themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/sass/components/ting-object/material-item.scss, themes/ddbasic/template.php, themes/ddbasic/utils.inc, translations/da.po
https://platform.dandigbib.org/issues/5059
Refactors debs to be split in on-site and off-site payments, with a separate section for each type. Much moving about and cleaning up.
User page:
Admin:
=> 5059: off-site payments

modules/ding_webtrekk/ding_webtrekk.install
https://platform.dandigbib.org/issues/5151
Removing the cookie from ECC whitelist is the most convenient of achieving this without writing any frontend code to handle this ourselves.
It was left there to keep support of opt-in/out with cookie-based tracking, but in current situation it's preffered to just remove
it.
This is the successor of #1776 with a bit more cleanup of obsolete functions. This would normally happen in a review but I have taken over work on the issue.
=> 5151: Ensure optOut cookies are removed from users browsers 

modules/ding_availability/ding_availability.module, modules/fbs/includes/fbs.availability.inc
https://platform.dandigbib.org/issues/1370
We are currently sorting each periodical "volume", but not the issues in each volume. This PR fixes that.
Additionally we swicth to using PHP's natural sort in both cases, since we can't know how the provider keys the periodical arrays. For example FBS uses both the volume and volume-number returned by the API to form a string as key for each issue. Ding availability also makes no assumptions about what the provider uses as keys for each volume. FBS uses years but it could be anything. Since we don't know if we can sort numerically, natural sort is a good solution since it will order the numbers correct in the string: http://sourcefrog.net/projects/natsort/.
If we determine that every issue (or volume of issue) is keyed by month name, we instead …
=> 1370: Improve periodical sorting

modules/ding_debt/ding_debt.admin.inc, modules/ding_debt/plugins/content_types/debts/debts.inc
https://platform.dandigbib.org/issues/5139
Ensure debt form always has a button. This is required to ensure accessibility.
Adding the button role to the external payment url should be
sufficient for assistive technologies to determine its relevance.
We also have to ensure that either form of payment button is enabled.
Otherwise there will actually be no buttons. Restructuring the form
to handle such a setup will be quite tedious and probably not a
relevant usage scenario. Consequently we do not accept such a
configuration.
=> 5139: Ensure debt form always has a button

modules/ding_debt/plugins/content_types/debts/debts.inc
https://platform.dandigbib.org/issues/5137
Add underline to links in WYSIWYG text on debts page to improve accessibility.
For ancient reasons the default display of links is without
decoration. Consequently we have to add it on a per-case basis.
By adding a class ending with -body we get the decoration we want.
It is not pretty but it works.
=> 5137: Add underline to links in WYSIWYG text on debts page

themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/sass/components/ting-object/material-item.scss
https://platform.dandigbib.org/issues/5136
Improve layout of material item information elements
Currently we rely on dynamic resizing based on content. This results
in an uneven rhythm where you are not guaranteed that the same info
aligns vertically across items in a list.
Introduce a shared grid where each info has the same width - 33% on
desktop and 50% on mobile. Clear accordingly to avoid overlapping
infos.
Note that the original issue deals with debts but this actually
targets all material item lists.
Also make debt totals align with other infos in material list. This goes for both spacing (margin + padding) and fonts.
=> 5136: Debt layout

modules/fbs/includes/fbs.debt.inc
https://platform.dandigbib.org/issues/5133
Reason message is a free text field where library employees can enter
whatever. This does not go well with the design. Instead use the type
field.
We expect the type field to be restricted regarding allowed values
but official documentation of actual values is nowhere to be found.
Consequently we reference types which can be found in examples like
https://platform.dandigbib.org/issues/5059 and fall back to a generic
“other” for the rest.
=> 5133: Map readable FBS dept type to Ding dept type

modules/ding_user_frontend/ding_user_frontend.pages_default.inc, themes/ddbasic/templates/panel/panels-pane--debts.tpl.php
https://platform.dandigbib.org/issues/5129
Update the panel pane configuration to use H1 for the title.
For this to work we also have to update the template to respect the 
selected title tag.
=> 5129: Use h1 for debt pane headline to improve accessibility

modules/ding_nodelist/plugins/content_types/ding_nodelist.inc
https://platform.dandigbib.org/issues/5013
Shouldn't be necessary, ctools should handle the override_title
elements, but apparently there's so much mucking about in the nodelist
form that it get's confused.
=> 5013: Fix overriding title

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/4927
Changes section titles to always be displayed as `h1` elements.
This may be considered a hack, but doing it in the template is even more hackish …
=> 4927: Set top-level heading on section titles

modules/ding_registration/templates/ding-registration.tpl.php
https://platform.dandigbib.org/issues/4895
Changes registration page title be displayed as an h1 element.
=> 4895: Set top-level heading on registration page title

modules/fbs/fbs.features.field_instance.inc, project.make
https://platform.dandigbib.org/issues/4101
Add english source for on hold description
This will make it translatable via the field translate module.
Note that we also need to update Token module for this to work.
Version 1.7 contains a fix to the following issue:
https://www.drupal.org/node/2474403
Since 1.8 contains additional bug fixes we might as well upgrade
to the newest version.
=> 4101: Add translatable FBS on hold field description

themes/ddbasic/sass/components/ting-subsearch.scss
https://platform.dandigbib.org/issues/5080
Since we use "text on secondary" for bibdk external search button color, we also have to use secondary color as background.
Also add better hover effect.
New background color (notice default visual is changed):
Hover effect:
=> 5080: Fix bibdk button background color

modules/ding_base/ding_base.module, modules/ding_content/ding_content.views_default.inc
https://platform.dandigbib.org/issues/4733
Add event date field, an sort by it before node submitted date. As other node types doesn't have an event date, they'll get null values in that column, which makes it fall back on submitted date.
=> 4733: Sort events by event date on tags pages

modules/ding_nodelist/js/node_blocks.js, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.node_blocks.tpl.php, themes/ddbasic/ddbasic.info, themes/ddbasic/sass/add-ons/nodelist.scss
https://platform.dandigbib.org/issues/4276
You can use nodelist to display nodes in blocks. Each node has a
teaser text and read more link in the form of a button. This is shown
when the user hovers node. 
However when the truncated teaser spans the entire last line then the
read more button will overlap with the teaser text.
To prevent this we increase the size of the teaser when hovered. This
provides more space for the button which will no longer overlap with
the text.
Before as seen on https://upgrade-fbs.ddbcms.dk/section/sektion:
https://user-images.githubusercontent.com/73966/112604923-04272b80-8e17-11eb-9b41-869fc1416445.mp4
After:
https://user-images.githubusercontent.com/73966/112604948-0c7f6680-8e17-11eb-8a16-65a76f4d6dd1.mp4
=> 4276: Prevent overlap between teaser and button in nodelist + blocks

themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/5155
After replacing the checklist button we have to update the CSS rule 
which hides it on teaser views. This was missing when implementing
#1766.
Currently the styling does not support displaying the button in a
good way here. Consequently we hide it.
When implementing this I have searched through the codebase and I cannot find any other references to the `add-to-checklist` button.
=> 5155: Hide checklist button from teasers

modules/ting_das/includes/ting_das.admin.inc
https://platform.dandigbib.org/issues/2175
There is no reason to reference the developer version instead of the
production version in the text.
=> 2175: Update example url in ting_das module

modules/ding_sections/ding_sections.install, modules/ding_sections/ding_sections.module, modules/ding_sections/modules/ding_sections_custom_css/ding_sections_custom_css.features.field_base.inc, modules/ding_sections/modules/ding_sections_custom_css/ding_sections_custom_css.features.field_instance.inc, modules/ding_sections/modules/ding_sections_term_menu/ding_sections_term_menu.module, modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.install, themes/ddbasic/sass/components/ding-sections.scss, themes/ddbasic/templates/taxonomy/taxonomy-term--section.tpl.php, themes/ddbasic/templates/view/views-view-fields--ding-sections--ding-sections-groups.tpl.php
https://platform.dandigbib.org/issues/5193
Ding Sections are supports to create a new panels variant for each
section page where editors can decide what panes to use for the
specific term/page. This is controlled by the term page field which
is set by default.
In #1756 the weight for the section tab which places
the field in the vertical tabs section was set in order to move the
section to the bottom of the section form.
Unfortunately for some reason this did not result in moving the
section down. Instead the term page field is removed from the form
entirely. This means that is does not have a value. Due to the way
the module is constructed this will instead result in editing the
general panels variant for sections.
This makes it seem as if new sections copy the old ones instead of …
=> 5193: Fix section panels template being overriden

modules/ding_registration/includes/ding_registration.acceptance.inc
https://platform.dandigbib.org/issues/5092
Simply catch the `DingProviderUserExistsError` exception and carry on.
=> 5092: Log in existing users trying to register

modules/ding_debt/ding_debt.module, modules/ding_debt/plugins/content_types/debts/debts.inc, modules/ding_debt/templates/ding_debt_external.tpl.php
https://platform.dandigbib.org/issues/5139
The issues exists when you only have external debts payments and the first part of the form is empty. Then the form do not have any submit buttons.
Fixed by not rendering external inside the form, but in it's own theme function.
No screenshot
No comments
=> 5698: Moved external debts into own theme function

themes/ddbasic/sass/base/standard.scss
https://platform.dandigbib.org/issues/5123
I have removed `text-decoration:none `from links in standard.scss. 
Failed behat test is not related to changed styling
=> 5123: removed text-decoration none in standardscss

themes/ddbasic/sass/components/cookie.scss
https://platform.dandigbib.org/issues/5109
In some installations the button is not visible due to a fallback to a black text color.
This pull request addresses that by adding styling to the `.find-more-button`. Also that element is not a child of `#popup-buttons` hence we have moved the styling of it.
Default:
With `:hover`:
=> 5109: Styling popup find-more-button

themes/ddbasic/sass/components/node/event.scss
https://platform.dandigbib.org/issues/4510
Removes text overflow on event labels.
- [ x ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ x ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ x ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
=> 4510: Changed styling for event labels

modules/opensearch/src/OpenSearchTingObject.php
This reverts commit 5fb344f7db1f4e0145f79c822a8d6310a2b3c77e.
https://platform.dandigbib.org/issues/5225
Check relations before dcterms:URI.
=> 5225: Revert "4877: Check dcterms:URI before fetching relations"

.platform.app.yaml
Without this it can be difficult to know whether a configuration
change has been implemented properly as it is up to the tester to
revert features using admin access.
This way features are reverted automatically which also matches the
deployment procedure on staging and production environments.
This problem has been identified during the test of #1804.
=> Core: Revert features when deploying on Platform.sh

themes/ddbasic/sass/base/standard.scss
https://platform.dandigbib.org/issues/5261?issue_count=2&issue_position=1&next_issue_id=4602
Underline links in content areas
This PR reverts some styling introduced in https://github.com/ding2/ding2/pull/1809
=> 5261: Add underline to links in content areas.

themes/ddbasic/sass/components/panel/account.scss
https://platform.dandigbib.org/issues/5259
Remove unwanted space
=> 5259: Remove space between reservation buttons

themes/ddbasic/sass/components/ting-object/material-item.scss
https://platform.dandigbib.org/issues/5211
Remove ul width, as it seems to be the problem.
=> 5211: Fix material-item styling

modules/fbs/includes/fbs.user.inc
https://platform.dandigbib.org/issues/5092
Throw `DingProviderUserExistsError` exception when FBS returns statusCode 409 at user create request.
No screenshot.
Scrutinizer error exists because I followed the used convention in the file.
=> 5092: Added user exists exception when status 409 is returned

modules/ting_das/css/ting_das.css, modules/ting_das/includes/ting_das.admin.inc, modules/ting_das/ting_das.module
https://platform.dandigbib.org/issues/5292?next_issue_id=5291&prev_issue_id=5293
The texts in the form where not showing if the admin page had not been saved. That was because the default settings were in the admin page. The default setting is now moved to a function so it works out off the box. Also minor css styling fixes.
=> 5292 das text

modules/ding_base/ding_base.install, project.make
https://platform.dandigbib.org/issues/5315
The SameSite Cookie module tries to ensure that
samesite_cookie_boot() executes as early as possible by implementing
hook_module_implements_alter(). However as far as I can tell this
does not work in practice.
hook_boot implementations are called from bootstrap_invoke_all() -
never from module_invoke_all(). As far as I can tell
bootstrap_invoke_all() calls modules ordered by module weight - not
in any way that involves invocations of module_implements_alter
hooks. Consequently the code in
samesite_cookie_module_implements_alter() has no effect.
This can cause problems when there are other modules working with the
global conf array. One such example is Variable Realm.
Consequently we should use module weight instead of
module_implements_alter to …
=> 5315: Fix cookie compatibility with older browsers e.g. iOS 12/Safari

project-core.make
We currently see problems during site updates relating to a conflict between Drupal 7.83 which introduces a changed column to users and the Entity Cache module:
WD php: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown[error]
column 'base.changed' in 'field list': SELECT base.uid AS uid,
[base.name](http://base.name/) AS name, base.pass AS pass, base.mail AS mail, base.theme
[...]
in EntityCacheControllerHelper::entityCacheLoad() (line 100 of
/var/aegir/platforms/ddb650beta1/profiles/ding2/modules/contrib/entitycache/entitycache.module).
To address this we roll back to the previous version of Drupal Core for now.
This reverts ding2/ding2#1859
=> Core: Revert "5325: update Drupal to v7.86"

modules/ding_debt/plugins/content_types/debts/debts.inc
https://platform.dandigbib.org/issues/5332
Always display intro text on debts page.
No comments
=> 5332: Ensure payment intro text is always shown

modules/ding_debt_easy/ding_debt_easy.module
https://platform.dandigbib.org/issues/5117
When loading the retries counter from the database it is a string and during strict comparison with a max retries count that is an int fails.
No comments.
=> 5117: Fixed retries type in easy payment retries

themes/ddbasic/scripts/menu.js
https://platform.dandigbib.org/issues/5331
The menu on mobile devices do on slide up/down when clicked.
No comments
=> 5331: Fixed event query selection in menu expansion script

modules/ting_infomedia/ting_infomedia.module
-------
https://platform.dandigbib.org/issues/5284
Infomedia button only worked on second click. Apparently the JS needed
for the ajax response to work only got loaded on the first click,
requiring another to trigger the redirect. So explicitly add the
ctools `ajax-responder` library.
=> 5284: Attach JS needed for Infomedia button

modules/ding_place2book/ding_place2book.fields.inc
https://platform.dandigbib.org/issues/5240
This PR deals with a error that I have not been able to reproduce. The errors shows up as event_id and event_maker_id get set to 1 and the event loses connection to its counterpart in place2book service. This PR introduces som definsive programming and logging if the error occurs. It hinders the page from saving invalid event_id and event_maker_id to the database. And it changes to place moste likely to cause this errors to a more robust code. It also changes message text that would otherwise be confusing to users.
=> 5240 place2book returns error

modules/ding_registration/includes/ding_registration.acceptance.inc, modules/fbs/includes/fbs.user.inc
https://platform.dandigbib.org/issues/5092
When trying to register, redirect existing users to their profile edit
page.
Includes #1833.
=> Redirect existing users in registration

project.make
https://platform.dandigbib.org/issues/5316
https://www.drupal.org/sa-contrib-2022-003
Opdateret:
projects[wysiwyg] -> 2.9
libraries[ckeditor] -> CKEditor 4.17.1
=> 5316: Update WYSIWYG and CKEditor modules

modules/bpi/bpi.module
https://platform.dandigbib.org/issues/4935
The getobject method in opensearch was used to validate the existence of materials locally on BPI imports. That method doesn't not check whether the library has holdings locally or not. Only search does. So the validation method was changed to use a search instead. The paragraphs module expects the bpi_validate_material to exist so that method was retained. 
=> 4935 bpi material list

modules/fbs/includes/fbs.availability.inc
https://platform.dandigbib.org/issues/5339
This pull request modifies the output of the fbs availability provider, so that periodical-holdings are enriched with material numbers and availiability status. This change is a prerequisite for an upcoming IMS-module that will modify the output of the fbs availability provider and add in detailed placement info acquired from IMS. The IMS-module will be developed as a stand alone module outside of ding2.
Note that a pull request regarding this issue has previously been accepted: https://github.com/ding2/ding2/pull/1851
The difference between the two is that this one enriches periodical-holdings while 1851 enriches holdings of monographies.
The change has no visible result
=> 5339: Add materials to result for periodica

themes/ddbasic/sass/components/form/form-status.scss
https://platform.dandigbib.org/issues/5333
* Removed float
* Hide disabled checkbox
https://user-images.githubusercontent.com/332915/157677827-2860093d-8a61-4c0a-8ccf-aea45492621f.mp4
=> Placement fo renew-all bar

modules/ting_das/css/ting_das.css
https://platform.dandigbib.org/issues/5307
The problem was that the form was still there which made the confirmation page extra long and scrolled down to the bottom. Fixed by not displaying the form on confirmation page.
=> 5307: Fixed confirmation message styling

modules/ding_base/ding_base.install
https://platform.dandigbib.org/issues/5291
Disables the progresbar by default in webforms.
=> 5291: Disable progressbar by default in webforms

themes/ddbasic/sass/components/cookie.scss
https://platform.dandigbib.org/issues/5290#change-55324
Change link hover color to inherit the text color, and use opacity to distinguish the state.
Based on case where secondary color was dark, and therefore unreadable on a also dark background.
Resting:
Hover:
=> 5290: Change link hover color to inherit

themes/ddbasic/sass/components/ting-object/material-item.scss, themes/ddbasic/templates/material-item.tpl.php
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5288)
Position messages in flow with content instead of absolute, wich resulted in content being hidden behind.
=> 5288: New placement for material-item messages

modules/ding_carousel/js/ding_carousel.js
https://platform.dandigbib.org/issues/5263
Changed aria-hidden values to false in order to fix siteimprove report error. Took next and previous buttons out of tab order.
=> 5263: Tab sequence changes

themes/ddbasic/sass/components/menu.scss
https://platform.dandigbib.org/issues/5257#change-55296
Preserve white text color on 2. level menu items when black on primary is configured.
=> 5257: Inherit white color on 2. level menu items

themes/ddbasic/sass/components/messages.scss
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5269?issue_count=40&issue_position=1&next_issue_id=5263)
Use a darker red for better contrast
Contrast check: https://webaim.org/resources/contrastchecker/?fcolor=A11515&bcolor=F1F1F2
=> 5269: Apply dark-red on form-required asterisk

modules/ding_debt_easy/ding_debt_easy.install, modules/ding_debt_easy/ding_debt_easy.module, modules/ding_debt_easy/includes/easy.payment.inc, modules/ding_debt_easy/lib/Nets/Easy/Checkout.inc, modules/ding_debt_easy/lib/Nets/Easy/Notification.inc, modules/fbs/includes/fbs.debt.inc
https://platform.dandigbib.org/issues/5362
Enabled callback using webhooks for payments. When paying with mobil payment (mobilpay) the user may not always be redirect back to the library site.
No screenshot
No comments
=> 5362: Working on using web-hooks as callbacks in nets-easy

modules/ting/ting.field.inc
https://platform.dandigbib.org/issues/5360
Comparing language strings in lowercase because both upper and lowercase can happen in the data..
=> 5360: Compare strings lowercase

modules/ding_debt_easy/ding_debt_easy.module
https://platform.dandigbib.org/issues/5362
The wrong array key was used in hook_menu (`access arguments` vs `access callback`).
No screenshot.
No comments.
=> 5362: Fixed access callback for easy web-hooks

modules/ding_webtrekk/ding_webtrekk.js, modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/5354#note-17
Mapp parameters need to be a string in order to be sent.
=> 5354: cast parameters to string

project-core.make
Reverts ding2/ding2#1879
The previous merge causes test to fail.
.
=> Revert "Revert "Core: Revert "5325: update Drupal to v7.86"""

modules/ting_reference/ting_reference.module
https://platform.dandigbib.org/issues/4935#note-46
Handles the issue that nodes with materials imported from BPI which the library does not have cant be saved. That happens because the validation function does not allow it. The solution is another check so the function does not validate materials which are not in the libraries holdings.
=> 4935: Dont validate materials which the library does not have

modules/ting_fulltext/js/ting_fulltext.js, modules/ting_fulltext/ting_fulltext.module
https://platform.dandigbib.org/issues/5445
This is a part off the Seo project. It moves the text for lektørudtalelser into the object page for Seo purposes. It is done via ajax for performance reasons.
=> 5150: Shows fulltext for lektørudtalelser on object pages

themes/ddbasic/sass/components/header.scss
https://platform.dandigbib.org/issues/5282
Scrolling of a big menu was not working on mobilephone when they where horisontal. Needed a little tweak of the height. There is a bigger problem with the combination of using fixed position and high zindex in the menu which causes problems with scrolling. But thats outside the scope of this issue.
=> 5282: Changed height to work on horisontal phones

themes/ddbasic/sass/components/webform.scss
https://platform.dandigbib.org/issues/5244
Remove float on webform components. Somethings clearly missing in order to layout-by-float, and default block layout looks okay.
=> Remove float on webform elements

modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_user_frontend/ding_user_frontend.module
https://platform.dandigbib.org/issues/3750
When user arent logged in on user status pages. Eg. /user/me/loans they are sent automatically to a login page. In order not to create dependency this is done with a hook. There is a reguirement that page parameters are preserved in the process. See PR: https://github.com/ding2/ding2/pull/1855 for discussion.
=> 3750 log in page hook

patches/cookieinformation-downgrade-php-requirements.patch, project.make
https://platform.dandigbib.org/issues/5448
Downgrade the requirement for PHP 7.1
No screenshot
No comment
=> 5448: Patch cookie informations module to downgrade PHP requirements

modules/ding_debt_easy/ding_debt_easy.module
https://platform.dandigbib.org/issues/5465
In rare cases the same debt id is charged twice. This is what happens:
Some users close the browser window during payment process before  _ding_debt_easy_callback() has finished.
Thereby their debt list in DDB CMS isn't updated and it contains already paid debts. Some users access the stale list and try to pay the same debt ids once more. That causes a negative response from FBS-provider, and the payment is transferred to the error handling system, where it is charged.
We need a check if the negative response from FBS is caused by the fee already being payed.
=> 5465: Easy double charge bug

themes/ddbasic/sass/base/table.scss
https://platform.dandigbib.org/issues/5490
The cookieinformation service puts a bit of css into the page which includes a general styling of tables. In order to make our own css styling work it needed to be a bit more specifik.  
=> 5490: Make table definition css more specific

modules/ding_content/ding_content.info, modules/ding_content/js/ding_content.cookie_consent.js, modules/ding_content/templates/media-vimeo-video--cookieinformation.tpl.php, modules/ding_content/templates/media-youtube-video--cookieinformation.tpl.php, modules/ting_oembed/ting_oembed.module, themes/ddbasic/sass/components/class.scss
Tell the user they have to accept cookies to view the video,
https://platform.dandigbib.org/issues/5448
Add cookie banner placeholders on videos that tell the user they have to accept cookies to view the video.
=> 5448: Add cookie banner placeholders on videos

themes/ddbasic/sass/base/table.scss
Reverts ding2/ding2#1908
These Changes to CSS are no longer relevant as the original problem in the Infomedia CSS has been fixed.
=> Revert "5490: Make table definition css more specific"

ding2.install
During rollout of release 7.x-6.6.0-beta5 we are seeing warnings due to missing columns in the user table when accessed by the entity cache. This is happening when running update hook  ding2_update_7102 where importing translations also clears the cache.
To avoid this we mark ding2_update_7102 as being dependent on user_update_7020 - the update hook responsible for adding the  additional columns.
=> Core: Order update hooks to avoid conflicts

modules/ting_oembed/ting_oembed.module
https://platform.dandigbib.org/issues/5448#note-42
Method calls to Domdocument used php 8 naming so they failed. Converted to php 7 naming.
=> Changed function names to php 7

modules/ding_webtrekk/ding_webtrekk.js
https://platform.dandigbib.org/issues/5448#note-30
There is problem that cookies don't get removed on pages with a subdomain. The cookie is registered to the root domain but windows.location.hostname returns the full hostname.  This solution is based on code from the eu cookie complience modules and iteratets over all the domains and attempts to remove the cookies.
Note this can't be properly tested. In order to test this we need a domain which includes a subdomain which is registred with KPI index as a domain to test Mapp on. My local dev domain is bur contains only a root domain. Upgrade-fbs can be used..
If you have any further comments or questions for the reviewer them …
=> 5448: Handles removing cookies from sub domains

themes/ddbasic/sass/components/node/node.scss
https://platform.dandigbib.org/issues/5448#note-45 issue b.
Styling of the video placeholder which is sat when the user hasn't given consent to cookies.
=> 5448: added background and styling to placeholder

modules/ding_base/ding_base.strongarm.inc, modules/ding_webtrekk/ding_webtrekk.js, modules/ting_oembed/ting_oembed.module
https://platform.dandigbib.org/issues/5448#
Changed data-category to marketing for ekurser. Puts cookieinformation_enable_popup intom strongarm. And adds a check for if the Cookieinformation javascript is loaded.
=> Changed data-category to marketing for ekurser
