drupal.make
Updated drupal core.
See http://platform.dandigbib.org/issues/859
=> Issue #859 - Updated drupal core to 7.34

ding2.make
Changed eu-cookie-compliance with eu_cookie_compliance.
=> Fixed wrong project name in make file

ding2.vcl
Fixed issue with drupal_set_message not being displayed for not logged in users.
See http://platform.dandigbib.org/issues/845
=> Issue #845 - Added secure session to varnish config file

ding2.profile, translations/da.po
Reverts ding2/ding2#18
This change has not been approved for the next release. It will be reintroduced at a later point in time.
=> Revert "Feature/feature257 opensuggestion"

ding2.profile, translations/da.po
Reverts ding2/ding2#20
This change has been reviewed and approved. It should be merged when it fits into the release plan.
=> Reintroduce "Feature/feature257 opensuggestion""

drupal.make
This updates the Drupal core to newest release.
=> Drupal core update to 7.39

ding2.install, ding2.profile
Changed popup disagree button message to "Læs mere".
http://platform.dandigbib.org/issues/1383
=> Bug #1383 by bartvig: Changed Danish popup disagree button message

ding2.make
=> Issue #777 by JrgenGNielsen: add ask_vopros to makefile

modules/ting/ting.field.inc
Logic got munged in last change, fix and clean up a bit.
=> Issue #1514 by xendk: Fix material title link.

modules/ding_event/ding_event.views_default.inc
http://platform.dandigbib.org/issues/333
=> Issue #333 by Inlead: Remove library linkage requirement for events.

modules/ding_event/ding_event.views_default.inc
=> Revert "Issue #333 by Inlead: Remove library linkage requirement for events."

modules/ding_ekurser/ding_ekurser.module
Remove ALL facets from the eKurser sidebar. Unless the facet "subject"
is unavailable for building a custom menu. In that case, show all
available facets instead.
=> Issue #1517 by bibchi: Handle added or removed facets

ding2.make
The format for the patch is  not valid.
=> Issue #1342 by kasperg: Fix oembed patch

modules/bpi/bpi.push.inc
http://platform.dandigbib.org/issues/1544
=> Hotfix by Inlead: Handle second variant of data's structure.

modules/ding_example_content/modules/ding_example_content_events/ding_example_content_events.features.node_export_features.inc
http://platform.dandigbib.org/issues/1590
=> Issue #1590 by Inlead: Update Event CT dates.

ding2.make
https://www.drupal.org/node/2209775
=> Issue #1538 by xendk: Fix ctools regression.

modules/ding_tabroll/ding_tabroll.views_default.inc
http://platform.dandigbib.org/issues/1429
=> Issue #1429 by bartvig: Changed sorting order of nodequeue to descending.

modules/ting/ting.module
http://platform.dandigbib.org/issues/1361
=> Issue #1361 by bartvig: Added dk5 classification and subject to boost.

modules/ding_event/ding_event.features.field_instance.inc
Changed event date increments from 15 minutes to 5 minutes.
http://platform.dandigbib.org/issues/820
=> Issue #820 by bartvig: Changed event date increments to 5 minutes.

modules/ding_library/ding_library.features.field_instance.inc, modules/ding_library/ding_library.field_group.inc, modules/ding_library/ding_library.info
http://platform.dandigbib.org/issues/684
=> Issue #684 by Inlead: Rename fieldgroup label.

modules/ding_groups/ding_groups.features.field_instance.inc, modules/ding_groups/ding_groups.pages_default.inc, modules/ding_groups/ding_groups.strongarm.inc
Added search_result view mode for ding_groups and set it to show list image, category, and lead.
http://platform.dandigbib.org/issues/600
=> Issue #600 by bartvig: Added search_result view mode for ding_groups.

modules/ding_base/ding_base.module
http://platform.dandigbib.org/issues/472
=> Issue #707 by Inlead: Adds recommendation text to image fields.

modules/ding_availability/ding_availability.module, modules/ding_availability/templates/ding-holdings.tpl.php
http://platform.dandigbib.org/issues/465
=> Issue #465 by Inlead: Waiting time when no items available.

modules/ding_gatewayf/ding_gatewayf.module, modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.module
We have found some issue during tests that has been introduced during the code review process.
This PR handle these.
=> Issue #659: Corrected attribute filtering and self registration

README.md
Update README with a link to latest release. This should be easier to use for people who just want to get started with the project.
=> Reference latest release

circle.yml
=> Update node version on Circle CI to match frontend pipeline requirements

modules/bpi/bpi.module
Merge of https://github.com/ding2/ding2/pull/53 broke something from https://github.com/ding2/ding2/pull/55 (cf. http://platform.dandigbib.org/issues/1630).
=> Issue #1630 by rimi-itk: Fixed asset syndication popup

modules/ding_ting_frontend/ding_ting_frontend.install, modules/ding_ting_frontend/ding_ting_frontend.local_config.admin.inc, modules/ding_ting_frontend/ding_ting_frontend.module, modules/ting/ting.module
original commit by Morten Bartvig
469: Fix errors found by Scrutinizer
469: Fix errors found by Scrutinizer
=> 469 : Add option for admin to configure holdings display

ding2.info, modules/ding_page/ding_page.strongarm.inc
http://platform.dandigbib.org/issues/556
=> Issue #556 by Inlead: Add pagepreview module as ding2 dependency.

modules/ding_reservation/ding_reservation.module
http://platform.dandigbib.org/issues/1629
=> Issue #1629 by Inlead: Decode item title when reserving.

translations/da.po
http://platform.dandigbib.org/issues/1660
=> 1660: Update translations

ding2.install, translations/da.po
Without the hook_update the translations are not imported.
=> 1660: Update translations on update.

ding2.make
http://platform.dandigbib.org/issues/1653
=> Issue 1653: Bumped memcache to version 1.5

modules/ting_search/ting_search.module
http://platform.dandigbib.org/issues/1450
=> Issue 1450: Remove sort options specific for rank_frequency if relevant

modules/bpi/bpi_features/bpi_features.views_default.inc
http://platform.dandigbib.org/issues/1661
=> Issue #1661 by holt83: Fix permission on admin content view.

modules/bpi/bpi.module, modules/bpi/bpi.syndicate.inc
This fixes Issue 1758 [http://platform.dandigbib.org/issues/1758] by moving the hook into the module file.
=> Issue 1758: Move hook into proper location

ding2.make
Ask_vopros has moved and gotten a new version.
=> 1755: Update ask_vopros

modules/ting_search/plugins/content_types/search_result.inc
http://platform.dandigbib.org/issues/1695
=> 1695: No sort used message, if sort is selected

modules/ding_webtrends/ding_webtrends.module
http://platform.dandigbib.org/issues/1732
=> Issue #1732 by holt83: Use Webtrends metatags to track onsite search.

modules/ting/ting.field.inc, modules/ting_material_details/ting_material_details.field.inc
http://platform.dandigbib.org/issues/1666
Change searchcode from dkcclterm.em to phrase.subject
=> 1666: Alter subject search searchcode

modules/ting_reference/ting_reference.module
Redo code from gielfeldt on new codebase.
=> 1662: Reapply pseudo delta support for relations

README.md, drupal.make
Issue: http://platform.dandigbib.org/issues/1638
=> Issue #1638 by kasperg: Update Drupal Core to 7.43

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_reservation/ding_reservation.module
Allows form_alters to examine the loan/reservation.
=> Issue #1622 by xendk: Add loan and reservations to forms

modules/ting_material_details/ting_material_details.field.inc
Formats a field as a link to search for the value in the configured
search index.
See http://platform.dandigbib.org/issues/1620
=> Issue 1620 by xendk: Implement generic search field formatter

modules/ding_provider/ding_provider.module, modules/ding_user/ding_user.module
Also makes the previously private ding_provider_function() public (it was just too useful to be private).
=> Issue 1617 by xendk: Add hooks to allow provider to add fields to login form

modules/ding_facetbrowser/ding_facetbrowser.admin.inc, modules/ding_facetbrowser/ding_facetbrowser.module, modules/ding_facetbrowser/js/ding_facetbrowser.js
http://platform.dandigbib.org/issues/1595
=> Issue #1595 by Inlead: Corrected typos.

modules/ding_library/plugins/content_types/library_list.inc
http://platform.dandigbib.org/issues/1591
=> Issue #1591 by Inlead: Removing 'Show' button for library filtering.

modules/ding_frontend/ding_frontend.info, modules/ding_frontend/ding_frontend.pages_default.inc, modules/ting_search/ting_search.module
Improve performance of the search block form redirect, by posting to a blank page and doing nothing but form related stuff.
http://platform.dandigbib.org/issues/1546
=> Enhancement #1546 by holt83: Improve performance of search form redirect

ding2.make
http://platform.dandigbib.org/issues/1425
=> Issue #1425 by Inlead: Updated workflow module.

modules/ding_staff/ding_staff.views_default.inc
http://platform.dandigbib.org/issues/1374
=> Issue #1374 by Inlead: Replace 'Delete item' with 'Cancel user account' in Users VBO.

modules/fbs/includes/fbs.reservation.inc
http://platform.dandigbib.org/issues/1363
=> Issue #1363 by xendk: Handle reservation results.

ding2.install
http://platform.dandigbib.org/issues/1195
=> 1195: Disable overlay module

modules/ting_material_details/ting_material_details.field.inc, modules/ting_relation/includes/ting_relation.field.inc, modules/ting_relation/ting_relation.module
http://platform.dandigbib.org/issues/1109
=> Issue #1109 by Inlead: Correcting isPartOfManifestation relation.

modules/ding_frontend/ding_frontend.install
New pull-request on issue 1104 - accidently deleted old branch
=> Issue 1104: fix scrutinizer message

modules/alma/alma.features.field_base.inc, modules/openruth/openruth.features.field_base.inc, translations/da.po, translations/fields_da.po
http://platform.dandigbib.org/issues/976
=> Issue #976 by Inlead: Add support for 24 months interest period.

modules/alma/includes/alma.reservation.inc, modules/ding_base/templates/material_item.tpl.php, modules/ding_provider/ding_provider.module, modules/ding_reservation/ding_reservation.module, modules/ding_user/ding_user.module
http://platform.dandigbib.org/issues/605
=> Issue #605 by Inlead: Configuration to disable Interest period for users.

modules/ting/ting.field.inc
http://platform.dandigbib.org/issues/594
=> Issue #594 by Inlead: Display language on non-Danish fiction items.

modules/ding_staff/ding_staff.features.field_instance.inc, modules/ding_staff/ding_staff.field_group.inc
http://platform.dandigbib.org/issues/550
Re-added a Pull Request previously added by @bartvig:
https://github.com/bartvig/ding_staff/commit/c77540a459b1a44557129e65294f11026bd68bd0
=> Issue #550 by bartvig: Department link changed to hidden.

modules/alma/includes/alma.reservation.inc, modules/alma/lib/AlmaClient/AlmaClient.class.php, modules/ding_provider/ding_provider.reservation.inc
http://platform.dandigbib.org/issues/489
=> Issue #489 by Inlead: Display reservation messages from DDE.

modules/ting/ting.module
http://platform.dandigbib.org/issues/466
=> Issue #466 by Inlead: Redirect directly to object if only 1 item of that type.

modules/ding_campaign/ding_campaign.admin.inc, modules/ding_campaign/ding_campaign.info, modules/ding_campaign/ding_campaign.module
http://platform.dandigbib.org/issues/287
=> Issue #287 by Inlead: Fixes to ding_campaign module.

modules/alma/includes/alma.reservation.inc
http://platform.dandigbib.org/issues/534
Re-added a Pull Request previously added by @pjohans:
https://github.com/ding2tal/alma/commit/5d17f10363e392b0c08f49c2b930c5d7e83db849
=> Issue #534 by pjohans: use correct interest_period.

modules/alma/alma.module
http://platform.dandigbib.org/issues/838
=> Issue #838 by Inlead: Deleting of email does not get deleted in ALMA.

modules/ding_user/ding_user.module
http://platform.dandigbib.org/issues/839
=> Issue #839 by Inlead: Role validation on user create.

modules/ding_mobilesearch/README.md, modules/ding_mobilesearch/ding_mobilesearch.api.php, modules/ding_mobilesearch/ding_mobilesearch.info, modules/ding_mobilesearch/ding_mobilesearch.install, modules/ding_mobilesearch/ding_mobilesearch.module, modules/ding_mobilesearch/includes/admin.inc, modules/ding_mobilesearch/includes/trigger.inc, modules/ding_mobilesearch/lib/NationalStorageComponent/GenericStorage.class.inc, modules/ding_mobilesearch/lib/NationalStorageComponent/NationalStorage.class.inc, modules/ding_mobilesearch/lib/bootstrap.inc, modules/ding_mobilesearch/plugins/rest.inc
http://platform.dandigbib.org/issues/1588
=> Issue #1588 by Inlead: Transfer ding_mobilesearch to Core.

docs/release_process.md
This should help more people being able to create a release.
=> Initial version of release proces

modules/alma/alma.module
See http://platform.dandigbib.org/issues/1767
=> Issue #1767: Fixed unused $path varible in alma

ding2.install
se http://platform.dandigbib.org/issues/1764
=> Issue #1764: Switch to P2 modules

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/functions.handler.inc
No issue was reported as this is a security hot fix
=> Hotfix: Script injection on ding_list issue.

ding2.make
Ref http://platform.dandigbib.org/issues/1845
=> 1845: Update admin_views to 1.6

modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1901
=> #1901: Added the wayf blocks to the p2 site template

ding2.make
http://platform.dandigbib.org/issues/1653
This has been pushed previously in https://github.com/ding2/ding2/pull/206, but reverted in https://github.com/ding2/ding2/pull/208.
=> Issue #1653: Bumped memcache to version 1.5

modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1922
=> 1922: Changed perms to provider role

modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1907
=> 1907: Tag panels config and PDO err fixed.

modules/p2/ding_sharer/ding_sharer.module
http://platform.dandigbib.org/issues/1900
Follow up on http://platform.dandigbib.org/issues/287 , where this P2 module declares function name that already exist.
=> Issue #1900 by Inlead: Fixing already declared function name.

modules/p2/ding_list/css/ding-list-view.css, modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/1870
=> Fixed 1870: Button style på links

modules/ting_search/js/ting_search.js, modules/ting_search/js/ting_search_overlay.js
http://platform.dandigbib.org/issues/278
=> Issue #278 by Inlead: Remove overlay when ESC is pressed.

modules/ding_frontend/plugins/content_types/taxonomy_menu.inc, modules/ding_library/plugins/content_types/library_list.inc
http://platform.dandigbib.org/issues/1591
=> Issue #1591 by Inlead: Remove "Show" button for library filtering

modules/bpi/bpi.install
See http://platform.dandigbib.org/issues/1798
=> 1798: Ensure admin view is disabled on fresh installations

ding2.install, modules/ding_ekurser/ding_ekurser.install
There might be more to this one, but at least we need an update hook
See http://platform.dandigbib.org/issues/1655
=> Issue 1655: Update hook to set as active search module

ding2.info, ding2.install, ding2.make, ding2.profile, modules/ding_base/ding_base.strongarm.inc, modules/ding_permissions/ding_permissions.module
http://platform.dandigbib.org/issues/1100
=> Issue #1100 by Inlead: Implement administration_menu.

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/functions.inc
http://platform.dandigbib.org/issues/1857
=> 1857: Title removed

modules/p2/ding_list/css/ding-list-add-button.css
http://platform.dandigbib.org/issues/1854
=> 1854: Styled more button

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/1925
=> 1925: Sharing of lists improved

modules/p2/ding_list/include/form.inc, modules/p2/ding_list/plugins/content_types/edit_list.inc, modules/p2/ding_list/plugins/content_types/list_followers.inc, modules/p2/ding_list/plugins/content_types/list_info.inc, modules/p2/ding_list/plugins/content_types/lists.inc, modules/p2/ding_list/plugins/content_types/share_list.inc, modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/1892
=> Fixed #1892: Translation fixed

modules/p2/ding_list/plugins/content_types/lists.inc, modules/p2/ding_list/theme/theme.inc, modules/p2/ding_notifications/plugins/content_types/notifications_top_menu.inc, modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1867
http://platform.dandigbib.org/issues/1871
http://platform.dandigbib.org/issues/1869
=> Fixes #1867, #1869 and #1871 The old userprofile panel is removed 

modules/p2/ding_sharer/ding-sharer.css, modules/p2/ding_sharer/ding-sharer.js, modules/p2/ding_sharer/plugins/content_types/sharer_pane.inc
http://platform.dandigbib.org/issues/1859
=> 1859: Fixed styling and sharing

modules/p2/ding_list/plugins/content_types/add_list.inc
http://platform.dandigbib.org/issues/1858
=> 1858: Button removed from anons

modules/p2/ting_openlist/ting_openlist.admin.inc
platform.dandigbib.org/issues/1937
=> 1937: Added statistics to provider admin form

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/js/ding_entity_rating.js
http://platform.dandigbib.org/issues/1873
=> #1873: Page reloads with login opened

ding2.make
=> 38: Add services_views module

modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/1879
=> 1879: Language filter added to author serendipity

modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/1856
=> 1856.b: Link to public-lists

modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/1781
=> 1781: Added empty list check to serendipity

modules/p2/ding_message/ding_message.js, modules/p2/ding_message/ding_message.module, modules/p2/ding_notifications/ding_notifications.module
http://platform.dandigbib.org/issues/1889
=> Fixed #1889: Recent content marked with stars fixed

modules/p2/ding_serendipity/plugins/content_types/serendipity_ting_object.inc, modules/p2/ting_carousel/ting_carousel.module
http://platform.dandigbib.org/issues/1782
=> 1782: Carousels can coexist

modules/p2/ding_list/css/ding-list-view.css, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/plugins/access/user_list.inc
http://platform.dandigbib.org/issues/1860
=> 1860: Added a drupal message to access denied

modules/ding_permissions/ding_permissions.module, modules/p2/ding_p2_installer/ding_p2_installer.module
http://platform.dandigbib.org/issues/1795
=> 1795: Moved secure permissions

modules/alma/includes/alma.reservation.inc
http://platform.dandigbib.org/issues/1606
=> Issue #1606 by Inlead: Change the interestperiod change logic.

ding2.make, themes/ddbasic/template.php, themes/ddbasic/templates/node--ding-library.tpl.php
http://platform.dandigbib.org/issues/1654
=> Issue #1654 by Inlead: Fix issue with duplicated opening_hours block.

modules/alma/alma.module, modules/alma/lib/AlmaClient/AlmaClient.class.php
http://platform.dandigbib.org/issues/1917
=> #1917.a: Added patronAllow to the get_patron_info() function

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_interests/ding_interests.admin.inc, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/js/ding_list_tabledrag.js, modules/p2/ding_list/plugins/content_types/list_menu.inc
http://platform.dandigbib.org/issues/1875
And a small unrelated bug
=> Fixed 1875: Sort order fixed on dragndrop

modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1888
=> Fixed 1888: Removed more button for anons

ding2.install, ding2.make, modules/ding_dibs/ding_dibs.email_reports.inc, modules/ding_dibs/ding_dibs.info, modules/ding_dibs/ding_dibs.install, modules/ding_dibs/ding_dibs.module
http://platform.dandigbib.org/issues/805
=> Issue #805 by Inlead: Notification upon DIBS-unusualness.

modules/ding_contact/ding_contact.info, modules/ding_event/ding_event.info, modules/ding_frontend/ding_frontend.info, modules/ding_groups/ding_groups.info, modules/ding_library/ding_library.info, modules/ding_news/ding_news.info, modules/ding_staff/ding_staff.info, modules/ding_ting_frontend/ding_ting_frontend.info, modules/ding_user_frontend/ding_user_frontend.info, modules/ding_user_frontend/ding_user_frontend.pages_default.inc
http://platform.dandigbib.org/issues/1516
Now also adds denpendencies for Metatag panels to ensure it's activated on a fresh install
=> Enhancement #1516 by holt83: Remove all occurences of current user name

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/plugins/content_types/list_menu.inc
http://platform.dandigbib.org/issues/1890
=> 1890: Added share operation. Limited sharing.

ding2.make
Update ask_vopros to latest version.
=> 1755: Update to ask_vopros 1.5

modules/p2/ding_serendipity/ding_serendipity.module
http://platform.dandigbib.org/issues/1877
=> 1877: Prefix cache with uid and wipe on listupdates

modules/ding_place2book/ding_place2book.install, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.admin.inc, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.info, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.module
http://platform.dandigbib.org/issues/1404
=> Issue #1404 by Inlead: Handle OG references and port old settings.

modules/p2/ding_list/ding_list.install, modules/p2/ding_list/ding_list.module
http://platform.dandigbib.org/issues/1916
=> 1916: import bookmarks and disable ding_bookmarks

modules/p2/ding_p2_installer/ding_p2_installer.pages_default.inc
http://platform.dandigbib.org/issues/1923
=> 1923: Frontpage panes config

modules/ting_covers/ting_covers.install
http://platform.dandigbib.org/issues/1671#change-19017
=> 1671: Ensure ting_covers_addi is activated on fresh install

modules/alma/includes/alma.reservation.inc
http://platform.dandigbib.org/issues/605
=> 605 by Inlead: Check for set interest date.

modules/ding_base/ding_base.install
http://platform.dandigbib.org/issues/1018
=> 1018: Ensure critical variables for expire is set correctly

modules/ding_provider/ding_provider.user.inc, modules/fbs/fbs.field.inc, modules/fbs/includes/fbs.reservation.inc
=> 1527: Misc FBS wayf fixes

ding2.info, modules/ding_permissions/ding_permissions.module
http://platform.dandigbib.org/issues/1997
=> 1997 by Inlead: Enable toolbar for some roles.

modules/p2/ding_list/plugins/content_types/lists.inc
http://platform.dandigbib.org/issues/1869
=> 1869: Fix reservations

modules/ding_place2book/css/ding_place2book_fields.css, modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module
http://platform.dandigbib.org/issues/2043
=> Issue #2043 by Inlead: Make table responsive.

modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/plugins/content_types/lists.inc
http://platform.dandigbib.org/issues/2041
=> 2041: Access to loan history list

modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2035
=> 2035: Fixed titles in serendipity info

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/ding_list_installer/ding_list_installer.pages_default.inc, modules/p2/ding_list/include/form.inc, modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/plugins/content_types/list_menu.inc
http://platform.dandigbib.org/issues/2025
2025.b
=> 2025: Only owners can delete lists

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/plugins/content_types/popular.inc
http://platform.dandigbib.org/issues/2022
=> 2022: Toggler for popuplar on frontpage

modules/p2/ding_entity_rating/ding_entity_rating.serendipity.inc, modules/p2/ding_list/include/functions.handler.inc, modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity_fallback/ding_serendipity_fallback.module, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2023
=> 2023: Remove incorrect anon lists

modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/2021
=> 2021: Note on share list form

modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/plugins/access/user_list.inc
http://platform.dandigbib.org/issues/2019
=> 2019: Show shared lists when token given

modules/p2/ding_list/ding_list.module
http://platform.dandigbib.org/issues/2017
=> 2017: Always show username on public lists

modules/ding_user_frontend/ding_user_frontend.info, modules/ding_user_frontend/ding_user_frontend.pages_default.inc
http://platform.dandigbib.org/issues/2016
=> 2016: Added profile information

modules/fbs/includes/fbs.reservation.inc
http://platform.dandigbib.org/issues/2007
Original commit:
https://github.com/ding2/ding2/commit/f6e05762
=> 2007 by Inlead: Missing argument from commit f6e05762.

modules/p2/ding_user_consent/ding_user_consent.features.inc, modules/p2/ding_user_consent/ding_user_consent.info, modules/p2/ding_user_consent/ding_user_consent.module, modules/p2/ding_user_consent/ding_user_consent.strongarm.inc
http://platform.dandigbib.org/issues/2003
=> 2003: Added default consent messages

modules/fbs/fbs.install
http://platform.dandigbib.org/issues/2001
=> 2001 by Inlead: Remove field 'interests period' completely.

modules/fbs/fbs.module, modules/fbs/includes/fbs.user_consent.inc, modules/openruth/includes/openruth.user_consent.inc, modules/openruth/openruth.module
http://platform.dandigbib.org/issues/1992
=> 1992: Add user_consent to openruth and fbs

modules/p2/ding_list/plugins/access/user_list.inc, modules/p2/ding_list/plugins/content_types/lists.inc
http://platform.dandigbib.org/issues/1943
=> 1943: Changed Loans overdue link

modules/p2/ding_list/plugins/content_types/list_menu.inc
http://platform.dandigbib.org/issues/1867
=> 1867: Anchor on To your lists link

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/menu_callbacks.inc, modules/p2/ding_list/plugins/content_types/private_share.inc
http://platform.dandigbib.org/issues/1859
=> 1859: Share of private list flow

themes/ddbasic/template.php
http://platform.dandigbib.org/issues/1380
=> Issue 1380: Fix PHP 5.4 compatibility

modules/p2/ding_list/include/functions.handler.inc
http://platform.dandigbib.org/issues/1892
=> 1892: Removed check on list save

modules/p2/ding_entity_rating/plugins/content_types/popular.inc, modules/p2/ding_serendipity/ding_serendipity.module
http://platform.dandigbib.org/issues/2033
=> 2033: Remove local missing materials from serendipity

modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/2011
=> 2011: Translate allowed values

ding2.info, ding2.make, drupal.make
They were added by mistake in https://github.com/ding2/ding2/pull/331
=> Remove version numbers

modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2065
=> 2065: serendipity adhr output

modules/p2/ding_list/ding_list.module
http://platform.dandigbib.org/issues/2064
=> 2064: Reverse bookmarks import order

modules/p2/ding_interaction/ding_interaction.strongarm.inc
http://platform.dandigbib.org/issues/2061
=> 2061: Interaction defaults

modules/p2/ding_p2_installer/ding_p2_installer.install
http://platform.dandigbib.org/issues/2055
=> 2055: Removed install argument

ding2.install
http://platform.dandigbib.org/issues/1997
=> 1997 by Inlead: Re-enable toolbar module.

modules/ding_content/ding_content.features.wysiwyg.inc, modules/ding_redirect/ding_redirect.admin.inc, modules/ding_redirect/ding_redirect.module, modules/ting/ting.admin.inc, modules/ting_search/js/ting_search_overlay.js, modules/ting_search/ting_search.info, modules/ting_search/ting_search.module
http://platform.dandigbib.org/issues/1919
=> Issue #1919 by Inlead: Various optimisation.

modules/p2/ding_list/plugins/content_types/private_share.inc
http://platform.dandigbib.org/issues/1890
=> 1890: Private sharer checks list permissions

modules/p2/ding_list/ding_list_installer/ding_list_installer.pages_default.inc
http://platform.dandigbib.org/issues/1859
=> 1859: Updated list installer features

modules/ding_availability/js/ding_availability.js, modules/ding_availability/js/ding_availability_labels.js, modules/fbs/fbs.info, modules/fbs/fbs.module, modules/fbs/includes/classes/FBS.php, modules/fbs/includes/classes/FBSAuthenticationHandler.php, modules/fbs/includes/fbs.availability.inc, modules/fbs/includes/fbs.debt.inc, modules/fbs/includes/fbs.loan.inc, modules/fbs/includes/fbs.reservation.inc, modules/fbs/includes/fbs.user.inc
http://platform.dandigbib.org/issues/1747
=> Issue #1747 by Inlead: Gracefully handle FBS problems.

modules/fbs/includes/fbs.reservation.inc
http://platform.dandigbib.org/issues/2047
=> 2047 by Inlead: Use the FBS prefered branch on reservation update.

modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc
http://platform.dandigbib.org/issues/1888
=> 1888: Remove more button for anonymous

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating_loan_history/ding_entity_rating_loan_history.module, modules/p2/ding_interaction/ding_interaction.admin.inc, modules/p2/ding_interaction/ding_interaction.module, modules/p2/ding_interaction_manual/ding_interaction_manual.module, modules/p2/ding_list/ding_list.module, modules/p2/ding_user_consent/ding_user_consent.admin.inc, modules/p2/ding_user_consent/ding_user_consent.module
http://platform.dandigbib.org/issues/2075
=> 2075: Add help page creation and links

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating_loan_history/ding_entity_rating_loan_history.module, modules/p2/ding_interaction/ding_interaction.admin.inc, modules/p2/ding_interaction/ding_interaction.module, modules/p2/ding_interaction_manual/ding_interaction_manual.module, modules/p2/ding_list/ding_list.module, modules/p2/ding_user_consent/ding_user_consent.module
http://platform.dandigbib.org/issues/2020
=> 2020: Ding interaction improvements. Fixed b and c

modules/ding_event/ding_event.install, modules/ding_place2book/ding_place2book.admin.inc, modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module, modules/ding_place2book/lib/p2b/P2b.php, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.module, themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2063
Fixes:
- Converts field_ding_event_price to string in order to define multiple prices for lists.
- Adds help text to field_ding_event_price field.
- Makes field_ding_event_price field required.
- Makes the module support various currencies.
- Makes sure that "Free" is shown if price is "0".
- Converts price value to kroner instead of ører.
- Disable migration module after migration has been run.
- Displays the postal code in the frontend.
=> 2063 by Inlead: Various fixes for p2b.

modules/p2/ding_list/ding_list.install, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/2019
=> 2019: Ding list support new mail system

ding2.make
http://platform.dandigbib.org/issues/430
=> 430: Fix search_api warnings and notices

ding2.make
http://platform.dandigbib.org/issues/430
=> 430: Fix patch on wrong module

modules/ding_place2book/ding_place2book.module, modules/ding_place2book/js/ding_place2book.js, themes/ddbasic/template.php, themes/ddbasic/templates/node--ding-event.tpl.php
http://platform.dandigbib.org/issues/1404
=> 1404 by Inlead: Fixes displaying of prices and of reserve button.

modules/p2/ding_entity_rating/plugins/content_types/popular.inc
http://platform.dandigbib.org/issues/2022
=> 2022: Set default popular frontpage

themes/ddbasic/color/color.inc
http://platform.dandigbib.org/issues/2108
=> 2108 by Inlead: Replace proper css file on color change.

modules/p2/ding_entity_rating/ding_entity_rating.serendipity.inc, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2109
=> 2109: Serendipity links

modules/p2/ding_list/ding_list.module
http://platform.dandigbib.org/issues/2116
=> 2116: Reply to header

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/plugins/content_types/popular.inc
http://platform.dandigbib.org/issues/2112
=> 2112: Get average rating from openlist

modules/p2/ding_entity_rating/ding_entity_rating.features.field_instance.inc, modules/p2/ding_entity_rating/ding_entity_rating.module
http://platform.dandigbib.org/issues/2129
=> 2129: Remove rating average

modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.module
http://platform.dandigbib.org/issues/1404
=> 1404 y Inlead: Change function for saving nodes on migration.

modules/fbs/includes/fbs.user.inc
http://platform.dandigbib.org/issues/1750
=> 1750 by Inlead: Added missing clear cache that is called after DIBS payment is accepted.

modules/ding_facetbrowser/js/ding_facetbrowser.js
Ensure that multiple Drupal.attachBehaviors doesn't add more and more
buttons.
Also fix up style.
=> 1686: Idempotent facetbrowser

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/lib/p2b/P2b.php
http://platform.dandigbib.org/issues/2138
=> 2138 by Inlead: Remove space and changing logic on update action.

modules/p2/ding_interaction/css/ding_interaction.css, modules/p2/ding_interaction/plugins/content_types/interaction_pane.inc
http://platform.dandigbib.org/issues/2134
=> 2134: Styled interaction for lazy pane

modules/p2/ding_serendipity/plugins/content_types/serendipity_ting_object.inc
http://platform.dandigbib.org/issues/2022
=> 2022: Serendipity frontpage

modules/ding_gatewayf/ding_gatewayf.module
This commit depends on an updated gatewayf - gatewayf now holds a hostlist with a salt for each host. Also gatewayf returns a checksum from selected attributes which are recreated and compared on login
=> Issue2164 gatewayf

ding2.info, ding2.install
http://platform.dandigbib.org/issues/2185
=> 2185 by Inlead: Enable Campaign module per default.

ding2.install, modules/alma/alma.install, modules/alma/alma.module
http://platform.dandigbib.org/issues/2192
=> 2192 by Inlead: Make TLS the standard SSL version for ALMA.

modules/ding_permissions/ding_permissions.module
http://platform.dandigbib.org/issues/2184#note-18
=> 2184: Change admin_menu fix to use permissions

ding2.make, themes/ddbasic/template.php
Upgrade field_groups module (security update), and fix ddbasic to deal with it.
=> 1905: Update field_groups module

modules/ting_search_autocomplete/includes/ting_search_autocomplete.ajax.inc
http://platform.dandigbib.org/issues/1887
=> 1887 by Inlead: Support the facetSpell method.

modules/ting_search/ting_search.module
http://platform.dandigbib.org/issues/1913
=> 1913 by Inlead: Add alter allowing modification of query.

ding2.make
http://platform.dandigbib.org/issues/2072
=> 2072: Fix metatag version in make

modules/fbs/includes/fbs.loan.inc
Dig out the title from the right place.
http://platform.dandigbib.org/issues/1270
=> 1270: Fix ill titles

modules/p2/ding_list/ding_list_installer/ding_list_installer.features.field_base.inc
http://platform.dandigbib.org/issues/2055#change-20516
=> 2055: Fixed updb warning

modules/fbs/fbs.module, modules/ting/ting.admin.inc, modules/ting/ting.client.inc, modules/ting/ting.install
http://platform.dandigbib.org/issues/1721
=> 1721: Move filter by holding logic to request class

modules/p2/ding_serendipity/ding_serendipity.admin.inc
http://platform.dandigbib.org/issues/2124
=> 2124: Removed serendipity key overview

modules/p2/ding_list/plugins/content_types/list_followers.inc
http://platform.dandigbib.org/issues/2119
=> 2119: Remove loan history sharing

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/1939
=> 1939: List share message

modules/p2/ding_entity_rating/css/ding_entity_rating.css, modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/js/ding_entity_rating.js
http://platform.dandigbib.org/issues/1920
=> 1920: Rating clear button

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/1946
=> 1946: Anonymous more button

modules/alma/includes/alma.loan.inc, modules/alma/lib/AlmaClient/AlmaClient.class.php, modules/ding_loan/plugins/content_types/loans.inc, modules/ding_provider/ding_provider.loan.inc, modules/fbs/includes/fbs.loan.inc
Cleanup as mentioned in http://platform.dandigbib.org/issues/761#note-25
Openruth not updated.
=> Renewal status cleanup

modules/p2/ding_list/ding_list_installer/ding_list_installer.views_default.inc
http://platform.dandigbib.org/issues/2091
=> 2091: Public lists sort order

modules/p2/ding_serendipity/ding_serendipity.admin.inc, modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2163
=> 2163: Validate CQL in serendipity

modules/ding_campaign/ding_campaign.admin.inc, modules/ding_campaign/ding_campaign.module, modules/ding_campaign/js/ding_campaign_scripts.js
http://platform.dandigbib.org/issues/2295
=> 2295 by Inlead: Typos in ding_campaign module.

ding2.make
Release 1.5 contains [a security vulnerability](https://www.drupal.org/node/2437905).
We want to get the most recent version as Entity API is a module 
which is used by other modules e.g. workflow and we do not want to
restrain out possibilities for using and updating such modules.
There are no changes to configuration, permissions or texts between 
the two versions.
=> 2311: Update Entity API to 1.8

modules/ding_mobilesearch/ding_mobilesearch.install, modules/ding_mobilesearch/ding_mobilesearch.module
http://platform.dandigbib.org/issues/2294
=> 2294 by Inlead: Various optimisation for ding_mobilesearch.

modules/p2/ding_entity_rating/plugins/content_types/popular.inc
http://platform.dandigbib.org/issues/2256
=> 2256: Fixed use libcode in popular

modules/p2/ding_user_consent/ding_user_consent.module
http://platform.dandigbib.org/issues/2127
=> 2127: User consent response

modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc, modules/ting/plugins/arguments/ting_collection_id.inc, modules/ting/ting.client.inc, modules/ting/ting.entities.inc
http://platform.dandigbib.org/issues/1773
=> 1773: Improve holdings display for FBS

modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc, modules/ting/plugins/arguments/ting_collection_id.inc, modules/ting/ting.entities.inc
http://platform.dandigbib.org/issues/2048
=> 1773 by Inlead: Improve holdings display.

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc, modules/p2/ding_list/plugins/content_types/list_followers.inc, modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/2120
=> 2120: User lists UX

modules/p2/ding_list/ding_list.module, modules/ting/ting.client.inc
Precache materials on the public_lists page, and attempt to fix ting caching.
=> 2258: Ting caching

modules/p2/ting_openlist/ting_openlist.admin.inc, modules/p2/ting_openlist/ting_openlist.install
http://platform.dandigbib.org/issues/2370
=> 2370: Openlist prefix and default url

modules/ding_ting_frontend/ding_ting_frontend.info, modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc
http://platform.dandigbib.org/issues/2303
=> 2303: Lazy load on related serendipity pane

ding2.profile
=> 1625: Add FBS to installer

modules/ding_provider/ding_provider.module, modules/fbs/includes/fbs.debt.inc, modules/fbs/includes/fbs.loan.inc, modules/fbs/includes/fbs.reservation.inc, modules/ting/ting.module
http://platform.dandigbib.org/issues/2048
This PR includes the changes from:
https://github.com/ding2/ding2/pull/485
=> 2048: Find correct namespace in user status

modules/ding_provider/ding_provider.module, modules/fbs/includes/fbs.reservation.inc, modules/ting/ting.module
http://platform.dandigbib.org/issues/2048
=> 2048 by Inlead: Adjust object fetching on userStatus.

modules/ding_availability/js/ding_availability.js
Hide reservation button on periodicals with issues.
=> 1460: reserve button on periodicals

modules/fbs/fbs.field.inc, modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc, modules/fbs/includes/fbs.reservation.inc, modules/fbs/src/ExternalCatalogApi.php
=> 1618: branches blacklist

modules/ding_place2book/ding_place2book.module
Checks that the place2book ticket button should be render before modifying node content. 
PR: https://github.com/ding2/ding2/pull/610
=> 2221: Ensured that place2book is only shown in selected view modes

modules/ding_availability/ding_availability.field.inc
http://platform.dandigbib.org/issues/2553
=> 2553: Ensure holdings is shown for all types and sources

modules/p2/ding_entity_rating/ding_entity_rating.serendipity.inc, modules/p2/ding_serendipity/ding_serendipity.admin.inc, modules/p2/ding_serendipity_fallback/ding_serendipity_fallback.module, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module, modules/p2/ding_serendipity_site/ding_serendipity_site.module, modules/p2/ding_serendipity_taxonomy_term/ding_serendipity_taxonomy_term.module, modules/p2/ding_serendipity_ting_entity/ding_serendipity_ting_entity.module
http://platform.dandigbib.org/issues/2092
=> 2092: Translations and settings added

modules/ding_availability/js/ding_availability.js
http://platform.dandigbib.org/issues/2337
=> 2337 by Inlead: Add new condition for ding_availability.

modules/alma/includes/alma.user.inc, modules/ding_loan/plugins/content_types/loans.inc
http://platform.dandigbib.org/issues/2404
=> 2404 by Inlead: Title is missing on the user status loan page.

modules/p2/ding_serendipity_lists/ding_serendipity_lists.module, modules/p2/ding_serendipity_ting_entity/ding_serendipity_ting_entity.module
http://platform.dandigbib.org/issues/2429
=> 2429: Handle language facet better

modules/ding_loan/plugins/content_types/loans.inc
http://platform.dandigbib.org/issues/2490
Includes the changes from #641
=> 2490: Improve display of loan left time

modules/ding_varnish/ding_varnish.module
=> 2083: Don't cache pages with messages in varnish

modules/ding_staff/ding_staff.views_default.inc
Here are exported changes for the next issues:
- http://platform.dandigbib.org/issues/2005
- http://platform.dandigbib.org/issues/2014
=> 2005 by Inlead: Remove providers from Staff list.

modules/ting_search/ting_search.module, themes/ddbasic/sass/components/header.scss
http://platform.dandigbib.org/issues/2468
=> 2468: Fixed JS error for extended search

themes/ddbasic/template.node.php
http://platform.dandigbib.org/issues/1918
=> 1918: Fixed. Use theme('image_style')

ding2.install, modules/ding_mobilesearch/ding_mobilesearch.module, modules/ding_mobilesearch/plugins/rest.inc, translations/da.po
http://platform.dandigbib.org/issues/2565
=> 2565 by Inlead: Various changes to Mobilesearch module.

modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity/plugins/content_types/serendipity_ting_object.inc, modules/p2/ding_serendipity_lists/ding_serendipity_lists.module
http://platform.dandigbib.org/issues/2526
=> 2526: Serendipity frontpage settings

themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/sass/p2/p2-serendipity.scss
http://platform.dandigbib.org/issues/2450
=> 2450: Fixed line styling on ting object

themes/ddbasic/sass/components/panel/pane-ding-facetbrowser.scss
http://platform.dandigbib.org/issues/2406
=> 2406: Fixes display of show less facet

modules/ding_mobilesearch/ding_mobilesearch.module, modules/ding_mobilesearch/plugins/rest.inc
http://platform.dandigbib.org/issues/2555
=> 2555 by Inlead: Limit the opening hours pushed to 10 weeks from now.

modules/ding_event/ding_event.module
http://platform.dandigbib.org/issues/2587
=> 2587: Group by NID in event list

modules/ding_event/ding_event.features.field_instance.inc, modules/ding_event/ding_event.field_group.inc, themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/templates/place2book_ticketsinfo.tpl.php
http://platform.dandigbib.org/issues/2440
=> 2440: Fixed. Styling of place2book field. Help text

themes/ddbasic/sass/base/form.scss, themes/ddbasic/sass/components/form/form-class.scss, themes/ddbasic/sass/components/form/form-user-profile.scss, themes/ddbasic/sass/layout/panel.scss
http://platform.dandigbib.org/issues/2375
=> 2375: Fixed general layout styling for pages with no panels

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_provider/ding_provider.module, modules/p2/ding_entity_rating/ding_entity_rating.module
ding_provider_build_entity_id() needed some more work.
http://platform.dandigbib.org/issues/2048
=> 2048: Better handling of unsearchable faust in build_entity_id()

modules/p2/ding_interaction/plugins/content_types/interaction_pane.inc
http://platform.dandigbib.org/issues/2605
=> 2605: Removed old interaction frontpage check

modules/ding_frontend/ding_frontend.features.menu_links.inc, modules/ding_frontend/ding_frontend.info
http://platform.dandigbib.org/issues/2604
=> 2604: Fixed. Opening hours menu-link added.

themes/ddbasic/ddbasic.info, themes/ddbasic/sass/base/form.scss, themes/ddbasic/sass/components/form/form-class.scss, themes/ddbasic/sass/components/modal-content.scss, themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2566
=> 2566: B) Fixed styling of elements in modal-content and multi select

modules/ting_field_search/ting_field_search.module, modules/ting_search/includes/ting_search.admin.inc, modules/ting_search/ting_search.module, themes/ddbasic/sass/components/header.scss, themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2549
=> 2549: Removed extended search

modules/ding_permissions/ding_permissions.module, modules/p2/ding_serendipity/ding_serendipity.module
http://platform.dandigbib.org/issues/2547
=> 2547: Administier serendipity panes permission

modules/p2/ding_list/plugins/content_types/lists.inc
http://platform.dandigbib.org/issues/2543
=> 2543: My account list order

themes/ddbasic/template.node.php
http://platform.dandigbib.org/issues/2448
=> 2448: Fixed. Hide library info when event has location

modules/fbs/includes/fbs.availability.inc
http://platform.dandigbib.org/issues/1773
=> 1773: Ensure that we can fetch the entity

modules/ding_staff/ding_staff.pages_default.inc, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/ding_list_installer/ding_list_installer.views_default.inc, modules/p2/ding_list/include/functions.handler.inc, modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/plugins/content_types/add_list.inc, modules/p2/ding_list/plugins/content_types/lists.inc, modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/2171
=> 2171: Staff lists

modules/p2/ding_list/ding_list_installer/ding_list_installer.pages_default.inc
http://platform.dandigbib.org/issues/2473
=> 2473 by Inlead: Lazy load public lists pane.

themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2598
=> 2598: Translate menu links

themes/ddbasic/sass/base/standard.scss, themes/ddbasic/sass/components/header.scss
http://platform.dandigbib.org/issues/2596
=> 2596: Move header and content down when using toolbar

modules/p2/ting_openlist/ting_openlist.admin.inc, modules/p2/ting_openlist/ting_openlist.install, modules/p2/ting_openlist/ting_openlist.module
http://platform.dandigbib.org/issues/2581
=> 2581: Openlist authkey setting added

ding2.install
http://platform.dandigbib.org/issues/2565
=> 2565 by Inlead: Typos on MS variable setting hook.

translations/da.po
http://platform.dandigbib.org/issues/2609
=> 2609: Fixed. Correction for string translation

modules/ding_tabroll/ding_tabroll.views_default.inc
http://platform.dandigbib.org/issues/2594
=> 2594: Fixed. Override title option added to view-pane

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
http://platform.dandigbib.org/issues/2588
=> 2588: Fixed wrong class for notice

modules/ding_campaign/ding_campaign.module, themes/ddbasic/sass/components/node/campaign.scss
http://platform.dandigbib.org/issues/2580
=> 2580: Fixed. Text color and link check

themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/menu.scss, themes/ddbasic/sass/p2/p2-class.scss, themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2539
=> 2539: Arrow added to user item in topmenu

modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/2538
=> 2538: Title on add element form

modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/2525
=> 2525: Fixed link/button text for follow search

themes/ddbasic/template.node.php, themes/ddbasic/templates/node/node--ding-news--view-mode--alternative-layout-full.tpl.php, themes/ddbasic/templates/node/node--ding-news.tpl.php
http://platform.dandigbib.org/issues/2418
=> 2418: Fixed date format and removed changed info

themes/ddbasic/templates/node/node--view-mode--search-result.tpl.php
http://platform.dandigbib.org/issues/2374
=> 2374: Fixed. Extra title removed

themes/ddbasic/sass/p2/p2-rating.scss
http://platform.dandigbib.org/issues/2253
=> 2253: Secondary color for own ratings

themes/ddbasic/sass/p2/p2-rating.scss
http://platform.dandigbib.org/issues/1920
=> 1920: Hide rating clear

modules/p2/ding_user_consent/ding_user_consent.module
platform.dandigbib.org/issues/2554
=> 2554: User consent popup feedback

modules/ding_event/ding_event.views_default.inc
http://platform.dandigbib.org/issues/2529
=> 2529: Added location name to event search

themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/sass/components/node/news.scss
http://platform.dandigbib.org/issues/2528
=> 2528: Bolded event and news lead

modules/p2/ding_list/plugins/content_types/list_followers.inc
http://platform.dandigbib.org/issues/2510
=> 2510: Removed doublicate follower count

modules/ding_user_frontend/ding_user_frontend.info, modules/ding_user_frontend/ding_user_frontend.module, modules/ding_user_frontend/ding_user_frontend.pages_default.inc, modules/p2/ding_notifications/ding_notifications.module, themes/ddbasic/template.php, themes/ddbasic/utils.inc
http://platform.dandigbib.org/issues/2541
=> 2541: User menu cleanup

modules/ding_user/ding_user.module, themes/ddbasic/sass/components/form/form-user-login.scss, themes/ddbasic/sass/configuration/_animation.scss
http://platform.dandigbib.org/issues/2600
=> 2600: Login feedback

modules/ding_loan/plugins/content_types/loans.inc
http://platform.dandigbib.org/issues/2490
=> 2490 by Inlead: Add 1 day to loan left time.

modules/ding_permissions/ding_permissions.module
http://platform.dandigbib.org/issues/2676
=> 2676: Media permissions for local

modules/ding_news/ding_news.views_default.inc
http://platform.dandigbib.org/issues/2546
=> 2546: grid-medium class added to view

themes/ddbasic/template.php, themes/ddbasic/templates/view/views-view-unformatted--ding-event.tpl.php
http://platform.dandigbib.org/issues/2687
=> 2687: Remove masonry classes from frontpage event view

modules/ding_mobilesearch/ding_mobilesearch.module
http://platform.dandigbib.org/issues/2693
=> 2693 by Inlead: Push event date as timestamp.

themes/ddbasic/sass/components/header.scss, themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2681
=> 2681: Class and styling for extended search with profiles

modules/p2/ding_entity_rating/ding_entity_rating.module, themes/ddbasic/sass/components/ting-object/material-item.scss
http://platform.dandigbib.org/issues/2679
=> 2679: Fixed styling for material item on mobile

themes/ddbasic/sass/components/form/form-class.scss, themes/ddbasic/sass/components/panel/account.scss
http://platform.dandigbib.org/issues/2673
=> 2673: Fixed submit-button overflow

modules/p2/ding_interaction_manual/ding_interaction_manual.features.field_base.inc, modules/p2/ding_interaction_manual/ding_interaction_manual.features.field_instance.inc, modules/p2/ding_interaction_manual/ding_interaction_manual.features.inc, modules/p2/ding_interaction_manual/ding_interaction_manual.info
http://platform.dandigbib.org/issues/2698
=> 2698: Ding interaction access to radio

themes/ddbasic/sass/components/node/news.scss
http://platform.dandigbib.org/issues/2583
=> 2583: Fixed styling for multiple libraries on news

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/js/ding_entity_rating.js
http://platform.dandigbib.org/issues/2256
=> 2256: Get ratings from openlist

modules/ding_popup/ding_popup.js, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc, modules/p2/ding_list/include/menu_callbacks.inc, modules/p2/ding_list/js/ding-list-private-sharer.js, modules/p2/ding_list/plugins/content_types/private_share.inc, modules/p2/ding_sharer/ding-sharer.js
http://platform.dandigbib.org/issues/2122
=> 2122: List sharing

themes/ddbasic/sass/p2/p2-rating.scss
http://platform.dandigbib.org/issues/2253
=> 2253: Different color for own ratings

modules/ding_loan/plugins/content_types/loans.inc
http://platform.dandigbib.org/issues/2455
=> 2455: Periodical issues on renewals

modules/ting_covers_addi/lib/addi-client/AdditionalInformationService.php, modules/ting_covers_addi/ting_covers_addi.install
http://platform.dandigbib.org/issues/2582
=> 2582: Update to moreinfo 2.9

modules/ting_covers_addi/lib/addi-client/AdditionalInformationService.php, modules/ting_covers_addi/ting_covers_addi.module
http://platform.dandigbib.org/issues/2551
This is dependant on the changes from #724
=> 2551: Fetch covers by PID

themes/ddbasic/sass/components/view/view.scss
http://platform.dandigbib.org/issues/2700
=> 2700: Sass refactoring

modules/bpi/bpi.images.inc, modules/bpi/bpi.preview.inc, modules/bpi/js/bpi.scripts.js
http://platform.dandigbib.org/issues/1678
=> 1678: Changed BPI popup to ctools modal

modules/ding_event/ding_event.module
http://platform.dandigbib.org/issues/2755
=> 2755: Events order

modules/p2/ding_list/ding_list.module
http://platform.dandigbib.org/issues/2585
=> 2585: Don't create lists during install

modules/p2/ding_list/theme/theme.inc
http://platform.dandigbib.org/issues/2122
=> 2122: Added public lists link to profile

modules/ding_base/ding_base.module, modules/ding_base/js/lazy-pane-fix.js, modules/p2/ding_serendipity_ting_entity/ding_serendipity_ting_entity.module
http://platform.dandigbib.org/issues/2684
=> 2684: Remove empty lazy pane panes

modules/ding_loan/plugins/content_types/loans.inc, modules/p2/ding_list/plugins/content_types/lists.inc, themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/form/form-loans.scss
http://platform.dandigbib.org/issues/2714
=> 2714: Anchor on loan link

modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc
http://platform.dandigbib.org/issues/2682
=> 2682: Text changed in help pane for search

themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/scripts/misc.js
http://platform.dandigbib.org/issues/2680
=> 2680: Collapsed removed from opening-hours

modules/ding_user/ding_user.module, modules/fbs/fbs.module, themes/ddbasic/sass/components/form/form-user-profile.scss
http://platform.dandigbib.org/issues/2456
=> 2456: SMS help text moved

modules/ding_campaign/ding_campaign.features.field_base.inc
http://platform.dandigbib.org/issues/2722
=> 2722: Added old ding campaign settings

modules/ting_field_search/plugins/ting_field_search_ctools_export_ui.inc, modules/ting_field_search/ting_field_search.module
http://platform.dandigbib.org/issues/2756
=> 2756: Use accessionDate instead of aquisitionDate for new materials

modules/p2/ding_serendipity/ding_serendipity.admin.inc
http://platform.dandigbib.org/issues/2092#note-17
=> 2092: Removed module names as group headers in config

modules/p2/ding_list/plugins/content_types/list_followers.inc
http://platform.dandigbib.org/issues/2119
=> 2119: Specific loan history list info

modules/ding_mobilesearch/plugins/rest.inc
http://platform.dandigbib.org/issues/2826
Since we made `update_hook()` in https://github.com/ding2/ding2/pull/648 there is not need to rely on the `ting_agency` variable.
=> 2826 by Inlead: Do not rely on ting_agency.

modules/ding_event/ding_event.features.field_instance.inc
http://platform.dandigbib.org/issues/2448
=> 2448: Library field set to required

themes/ddbasic/sass/components/field.scss
http://platform.dandigbib.org/issues/2241
=> 2241 by Inlead: Consider links in search message.

modules/ting_search/plugins/content_types/search_result.inc
http://platform.dandigbib.org/issues/2241
This hook is a prerequisite for the implementation of subsearch modules. Those modules need to do additional searches and set messages.
=> 2241: New hook in search_result.inc

modules/ding_mobilesearch/plugins/rest.inc
http://platform.dandigbib.org/issues/2691
=> #2691 by Inlead: Fix link to MS configration.

modules/ding_user/ding_user.module, modules/ding_user/plugins/content_types/profile2/profile2_form.inc
Also fixed notice errors on staff profile page.
See: https://platform.dandigbib.org/issues/2838
=> 2838: Ensured profile2 submit handler is available

modules/ding_ipe_filter/ding_ipe_filter.strongarm.inc, translations/da.po
http://platform.dandigbib.org/issues/2671
=> #2671 by Inlead: Fix the feature revert of IPE elements.

modules/ding_groups/ding_groups.pages_default.inc
https://platform.dandigbib.org/issues/2840
=> b2840: Grid class added to panel

modules/ding_event/ding_event.pages_default.inc, modules/ding_frontend/ding_frontend.views_default.inc, modules/ding_news/ding_news.pages_default.inc
https://platform.dandigbib.org/issues/2843
=> 2843: Pane-title added to related content panel

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/2841
=> 2841: Wrong variable name changed.

ding2.install, ding2.profile
http://platform.dandigbib.org/issues/2675
=> 2675 by Inlead: Adjustments to the ding_eresource module.

themes/ddbasic/template.php
http://platform.dandigbib.org/issues/2542
=> b2542: Wrong variable-name fixed

modules/p2/ding_entity_rating/ding_entity_rating.module
http://platform.dandigbib.org/issues/2171
=> 2171: Staff rate materials

modules/ding_mobilesearch/ding_mobilesearch.module
https://platform.dandigbib.org/issues/2555
=> 2555 by Inlead: Push opening hours from last monday.

modules/fbs/fbs.module
http://platform.dandigbib.org/issues/2836
=> 2836 by Inlead: Invert blacklist search logic

modules/ding_user_frontend/ding_user_frontend.pages_default.inc
https://platform.dandigbib.org/issues/2878
=> 2878: Menu type changed to tab in user reservations page

modules/ding_user_frontend/plugins/content_types/user_overview.inc
https://platform.dandigbib.org/issues/2873
=> 2873: Changed reservations ready link

themes/ddbasic/sass/components/panel/class-panel.scss
https://platform.dandigbib.org/issues/2520
=> 2520: Hide IPE actions on frontend

modules/ding_loan/plugins/content_types/loans.inc, modules/ding_user_frontend/plugins/content_types/user_overview.inc
https://platform.dandigbib.org/issues/2714
=> 2714: Fixed anchor name and added to loan link

modules/fbs/fbs.module
https://platform.dandigbib.org/issues/2836
=> 2836 by Inlead: Consider library name.

modules/ting_reference/ting_reference.module
https://platform.dandigbib.org/issues/2869
=> 2869: Only published nodes in ting references

modules/p2/ding_entity_rating/ding_entity_rating.module
https://platform.dandigbib.org/issues/2872
=> 2872: Include ui.widget in entity ratings

themes/ddbasic/sass/components/view/view.scss
https://platform.dandigbib.org/issues/2860
=> 2916: Masonry-view always visible on mobile

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/2919
=> 2919: Added currency postfix

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/2904
=> 2904: Title in search results

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/2906
=> 2906: Method for detecting panel-page changed

modules/p2/ding_list/ding_list_installer/ding_list_installer.info, modules/p2/ding_list/ding_list_installer/ding_list_installer.views_default.inc
https://platform.dandigbib.org/issues/2575
=> 2575: Pager on lists

modules/ding_news/ding_news.views_default.inc
https://platform.dandigbib.org/issues/2860
=> 2860: Link display url changed on ding news groups list view

ding2.install
https://platform.dandigbib.org/issues/2915
=> 2915 by Inlead: Do not override existing key value.

modules/ding_webtrends/ding_webtrends.module, modules/ding_webtrends/js/webtrends_add.js
https://platform.dandigbib.org/issues/1748
=> 1748: Track when materials is added to lists

modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.install
https://platform.dandigbib.org/issues/2907
=> 2907: Set signup link in update

modules/ding_availability/ding_availability.field.inc, modules/ding_availability/js/ding_availability_labels.js
https://platform.dandigbib.org/issues/2928
=> 2928: Only remove empty holding info

modules/ding_mobilesearch/ding_mobilesearch.module
https://platform.dandigbib.org/issues/2693
=> 2693 by Inlead: Push event dates as ISO-8601.

modules/ding_event/ding_event.views_default.inc
https://platform.dandigbib.org/issues/2923
=> 2923: Remove filter on end date from two views

modules/ding_user_frontend/ding_user_frontend.pages_default.inc
https://platform.dandigbib.org/issues/2934
=> 2934: Access rule added to User my library page

modules/fbs/fbs.install, modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc
https://platform.dandigbib.org/issues/2920
=> 2920: Make shelf mark default

ding2.make
https://platform.dandigbib.org/issues/2925
=> 2925: New patch for manualcrop

modules/p2/ding_list/plugins/content_types/list_menu.inc, themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/3007
=> 3007: Link href changed. Styling for link in sub-menu-title changed

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
https://platform.dandigbib.org/issues/3002
=> 3002: Exclude blocked dates in opening hours

modules/ding_campaign/ding_campaign.features.field_instance.inc, modules/ding_frontend/ding_frontend.features.inc
https://platform.dandigbib.org/issues/2993
=> 2993: Two crops removed from ding_campaign. Image style changed

modules/ding_user/ding_user.install, modules/ding_user/ding_user.module, modules/p2/ting_openlist/ting_openlist.module
https://platform.dandigbib.org/issues/2699
=> 2699: add ding_get_private_key function

modules/ding_event/ding_event.pages_default.inc
https://platform.dandigbib.org/issues/3031
=> 3031: Taxonomy term menu added to Library events page

modules/ding_content/ding_content.features.filter.inc, themes/ddbasic/sass/components/field.scss, themes/ddbasic/templates/file--image.tpl.php
https://platform.dandigbib.org/issues/2995
=> 2995: Styling for images in field-type-text-long

themes/ddbasic/sass/components/node/eresource.scss, themes/ddbasic/template.node.php, themes/ddbasic/templates/node/node--ding-eresource.tpl.php
https://platform.dandigbib.org/issues/3001
=> 3001: Login button added. Plus minor tablet correction

themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/form/form-class.scss
https://platform.dandigbib.org/issues/3023
=> 3023: Style reserve button in reserve form

modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc
See https://platform.dandigbib.org/issues/2836
=> 2836: Filter holdings based on fbs_user_branches_blacklist

modules/ding_loan/ding_loan.module, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/3003
=> 3003: Changes to user menu

modules/ding_user_frontend/ding_user_frontend.pages_default.inc
https://platform.dandigbib.org/issues/2541
=> 2541: More precise reservations title

modules/ding_staff/ding_staff.features.field_instance.inc, modules/ding_staff/ding_staff.field_group.inc, themes/ddbasic/sass/components/user.scss
https://platform.dandigbib.org/issues/3026
=> 3026: Add name and to profile staff

modules/ding_frontend/ding_frontend.views_default.inc, themes/ddbasic/sass/components/view/view.scss
https://platform.dandigbib.org/issues/3032
=> 3032: Classes changed on Ding-node-search view

modules/ding_tabroll/js/ding_tabroll.js, modules/ding_tabroll/js/jquery-ui-tabs-rotate.js
See https://platform.dandigbib.org/issues/2671
=> 2671: Change tabroll to use drupal behaviors

modules/p2/ding_entity_rating/ding_entity_rating.install, modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/plugins/content_types/popular.inc
PR: https://platform.dandigbib.org/issues/3034
=> 3034: Variable check removed from popular panel

ding2.info, ding2.install
https://platform.dandigbib.org/issues/3027
=> 3027: Enable ding_ddbasic module during install

modules/ding_loan/plugins/content_types/loans.inc
https://platform.dandigbib.org/issues/3061
=> 3061: Fix loan lists cache

modules/ting_search/js/ting_search.js, modules/ting_search/js/ting_search_overlay.js, themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/2983
=> 2983: Fixed search-circle missing in Explorer

modules/ding_varnish/ding_varnish.module
https://platform.dandigbib.org/issues/2083
=> 2083: Improve timing of drupal_set_messages() check

modules/ting_search/ting_search.module
http://platform.dandigbib.org/issues/731
=> #731 by Inlead: Add new sort criteria for opensearch v4.3 or higher.

modules/ding_permissions/ding_permissions.module
http://platform.dandigbib.org/issues/356
=> 356: Remove environment indicator permissions for provider

modules/p2/ding_list/theme/theme.inc
https://platform.dandigbib.org/issues/2376
=> 2376: Hide purge notifications on empty

modules/p2/ding_list/ding_list_installer/ding_list_installer.views_default.inc
http://platform.dandigbib.org/issues/2331
=> 2331: Removed type filter on public lists

modules/ding_event/ding_event.module
https://platform.dandigbib.org/issues/3087
=> 3087: Added group by date to event lists

ding2.make
https://platform.dandigbib.org/issues/3085
=> 3085 by Inlead: Added l10n_client to make file.

ding2.make, patches/menu_block-2x-ctools_exportables-693302-163.ding2.patch
https://platform.dandigbib.org/issues/3042
=> 3042: add custom menu_block patch

modules/ding_dibs/ding_dibs.admin.inc, modules/ding_dibs/ding_dibs.install, modules/ding_dibs/ding_dibs.module
Hardcode DIBS capture URL to avoid moneyloss in the future.
=> 2819: fix dibs capture

modules/fbs/includes/fbs.debt.inc
http://platform.dandigbib.org/issues/2364
=> 2364 by Inlead: Catch error properly.

themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/field.scss
https://platform.dandigbib.org/issues/3077#change-29398
=> 3077: Fixed embedded video

ding2.make
http://platform.dandigbib.org/issues/2055
=> 2055: Update ECK

modules/ding_provider/ding_provider.admin.inc, modules/ding_provider/ding_provider.install, modules/ding_provider/ding_provider.module
http://platform.dandigbib.org/issues/2002
=> 2002 by Inlead: Cleanup inactive users.

modules/ting_search/plugins/content_types/search_backends.inc
http://platform.dandigbib.org/issues/629
=> 629 by Inlead: Display amount of results.

themes/ddbasic/sass/components/panel/account.scss
https://platform.dandigbib.org/issues/3070
=> 3070: Action button sizes

modules/ding_user_frontend/ding_user_frontend.info, modules/ding_user_frontend/ding_user_frontend.pages_default.inc
https://platform.dandigbib.org/issues/3063
=> 3063: Fixed overdue loans title

ding2.install
https://platform.dandigbib.org/issues/3060
=> 3060: Set toggle_name

modules/ding_eresource/ding_eresource.features.field_instance.inc
https://platform.dandigbib.org/issues/3039
=> 3039: Format changed for files field

modules/ding_staff/ding_staff.pages_default.inc
https://platform.dandigbib.org/issues/3016
=> 3016: Removed library list from staff

modules/fbs/fbs.module
https://platform.dandigbib.org/issues/2875
=> 2875: Fixed - Email + Phone validation and rebuild on submit

modules/p2/ding_list/plugins/content_types/list_menu.inc
https://platform.dandigbib.org/issues/2837
=> 2837: List wording and link update

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/form.inc
http://platform.dandigbib.org/issues/2486
=> 2486: Locking title on lists

modules/ding_campaign/ding_campaign.module, modules/ding_campaign/plugins/content_types/campaign.inc
http://platform.dandigbib.org/issues/2367
=> 2367 by Inlead: Show campaigns with selected Taxonomy term.

modules/ding_groups/ding_groups.views_default.inc
http://platform.dandigbib.org/issues/2361
=> 2361 by Inlead: Only show nodes actually in the queue.

modules/p2/ding_message/ding_message.module
http://platform.dandigbib.org/issues/2196
=> 2196: Clear notifications on link click

modules/ding_frontend/ding_frontend.pages_default.inc
http://platform.dandigbib.org/issues/2167
=> 2167 by Inlead: Use multiple search view.

modules/alma/includes/alma.reservation.inc
http://platform.dandigbib.org/issues/1944
=> 1944 by Inlead: Disable availability caching.

ding2.make, modules/ding_event/ding_event.info, modules/ding_event/ding_event.module, modules/ding_event/ding_event.pages_default.inc, modules/ding_event/ding_event.views_default.inc, themes/ddbasic/sass/components/panel/class-panel.scss
http://platform.dandigbib.org/issues/280
=> 280 by Inlead: Convert event-list to AJAX filtering.

themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/2813
=> 2813: Fixed styling mobilvisning

modules/ding_event/ding_event.views_default.inc
https://platform.dandigbib.org/issues/2742
=> 2742: Event list, search in location

themes/ddbasic/sass/components/panel/account.scss
https://platform.dandigbib.org/issues/3067
=> 3067: Mobile renew button

modules/ding_dibs/ding_dibs.admin.inc, modules/ding_dibs/ding_dibs.email_reports.inc, modules/ding_dibs/ding_dibs.module
http://platform.dandigbib.org/issues/1998
=> 1998 by Inlead: Cleanup DIBS transactions.

modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/3076
=> 3076 by Inlead: Track empty internal search results.

modules/ding_ting_frontend/ding_ting_frontend.info, modules/ding_ting_frontend/ding_ting_frontend.install, modules/ting_search_ortograf/includes/ting_search_ortograf.admin.inc, modules/ting_search_ortograf/includes/ting_search_ortograf.ajax.inc, modules/ting_search_ortograf/js/ting_search_ortograf.js, modules/ting_search_ortograf/ting_search_ortograf.drush.inc, modules/ting_search_ortograf/ting_search_ortograf.info, modules/ting_search_ortograf/ting_search_ortograf.install, modules/ting_search_ortograf/ting_search_ortograf.module
See https://platform.dandigbib.org/issues/3115
=> 3115: update code to use ortograf.dbc.dk

modules/ting/ting.module
See https://platform.dandigbib.org/issues/3126
=> 3126: Remove random search querys

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/3074
=> 3074: Added campaign to IPE defaults

modules/ding_event/ding_event.views_default.inc
See https://platform.dandigbib.org/issues/3082
=> 3082: Added more link to events in groups

ding2.make
https://platform.dandigbib.org/issues/3040
=> 3040 by Inlead: Update autologout contrib module.

modules/p2/ding_message/ding_message.module
http://platform.dandigbib.org/issues/2552
=> 2552: Fixed notification update on cron

themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/sass/components/view/view.scss, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/3086
=> 3086: Read more button on mobile

modules/p2/ting_openlist/TingOpenlistRequestException.php, modules/p2/ting_openlist/ting_openlist.admin.inc, modules/p2/ting_openlist/ting_openlist.handler.inc, modules/p2/ting_openlist/ting_openlist.info, modules/p2/ting_openlist/ting_openlist.install, modules/p2/ting_openlist/ting_openlist.module
http://platform.dandigbib.org/issues/2593
=> 2593: Ting openlist SOAP to REST

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc
https://platform.dandigbib.org/issues/3159
=> 3159: Fixed opening hours subqueue

ding2.profile, modules/ting_covers_addi/ting_covers_addi.admin.inc, modules/ting_covers_addi/ting_covers_addi.install, translations/da.po
https://platform.dandigbib.org/issues/2811
=> 2811 by Inlead: Upgrade to Moreinfo v2.10

themes/ddbasic/sass/components/ting-object/ting-object.scss
https://platform.dandigbib.org/issues/2435
=> 2435: Fixed Ting object list-item color

modules/ding_eresource/ding_eresource.features.field_instance.inc, modules/ding_eresource/ding_eresource.features.inc, themes/ddbasic/sass/components/node/eresource.scss
https://platform.dandigbib.org/issues/3091
=> 3091: Fixed 16/9 format on E-resource

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/3110
=> 3110: Fixed teaser event date

themes/ddbasic/sass/components/menu.scss, themes/ddbasic/scripts/profile-dropdown.js
https://platform.dandigbib.org/issues/3119
=> 3119: Fixed tablet usermenu bug

modules/p2/ting_openlist/include/ting_openlist_analysis.inc, modules/p2/ting_openlist/ting_openlist.admin.inc
https://platform.dandigbib.org/issues/3157
=> 3157: Openlist analysis

modules/p2/ding_list/include/form.inc, modules/p2/ding_list/include/functions.handler.inc, modules/p2/ting_openlist/ting_openlist.module
https://platform.dandigbib.org/issues/2593
@tripox and I have experienced some problems with the introduction of exceptions for OpenList. These should be addressed by this PR.
Primary problems:
1. Class `TingOpenlistRequestException` cannot be found. It must be included.
2. `TingOpenlistRequestException` is always thrown when making requests to OpenList
=> 2593: Openlist REST fixes

ding2.make
https://platform.dandigbib.org/issues/3098
=> 3098 by Inlead: Added patch to oembed module.

modules/ding_user_frontend/ding_user_frontend.pages_default.inc
https://platform.dandigbib.org/issues/3097
=> 3097: Remove username from "My personal library" panel page title

ding2.make
https://platform.dandigbib.org/issues/2692
The change on line 231 is a linebreak fix not related to the issue.
=> 2692: Updated memcache module

modules/alma/alma.module, modules/ding_reservation/ding_reservation.module
http://platform.dandigbib.org/issues/2288
=> 2288 by Inlead: Re-think the translations of interest periods.

modules/ding_dibs/includes/dibs.payment.inc
See https://platform.dandigbib.org/issues/2577
=> 2577: More info in dibs reports

modules/ting_search/plugins/content_types/search_backends.inc
https://platform.dandigbib.org/issues/629
=> 629: Fix translations of search backends

modules/ding_user/ding_user.module
Cleans up #200
Ref http://platform.dandigbib.org/issues/448
=> 488 fix bad hashing

modules/p2/ding_list/include/form.inc, themes/ddbasic/sass/base/form.scss, themes/ddbasic/sass/p2/p2-class-panel.scss
https://platform.dandigbib.org/issues/3156
=> 3156: Styled shared list edit

themes/ddbasic/sass/components/node/library.scss, themes/ddbasic/template.field.php
https://platform.dandigbib.org/issues/3103
=> 3103: Allow all image formats on library teaser

modules/p2/ding_message/ding_message.module
https://platform.dandigbib.org/issues/2986
=> 2986: Notification link on lists

modules/p2/ding_list/theme/theme.inc, modules/p2/ding_message/ding_message.admin.inc, modules/p2/ding_message/ding_message.module
https://platform.dandigbib.org/issues/2376
=> 2376: Clear messages and redirection

modules/p2/ding_list/plugins/content_types/add_list.inc
https://platform.dandigbib.org/issues/2331
=> 2331: Hide follow button on own lists

modules/ding_event/ding_event.module
https://platform.dandigbib.org/issues/2742
=> 2742: Combined event filter breaks view

modules/ting_search/js/ting_search.js
https://platform.dandigbib.org/issues/2983
=> 2983: Fixed search spinner

ding2.profile, modules/ting_covers_addi/ting_covers_addi.admin.inc, modules/ting_covers_addi/ting_covers_addi.install, translations/da.po
https://platform.dandigbib.org/issues/2811
=> 2811 by Inlead: Upgrade to Moreinfo v2.11

modules/ting/ting.module, modules/ting_infomedia/css/ting_infomedia_article_view.css, modules/ting_infomedia/includes/ting_infomedia.field.inc, modules/ting_infomedia/includes/ting_infomedia.wrapper.inc, modules/ting_infomedia/plugins/arguments/infomedia.inc, modules/ting_infomedia/plugins/content_types/infomedia_content_type.inc, modules/ting_infomedia/plugins/contexts/infomedia.inc, modules/ting_infomedia/ting_infomedia.install, modules/ting_infomedia/ting_infomedia.module, modules/ting_infomedia/ting_infomedia_article_view.tpl.php
=> Revert "1437: infomedia login"

modules/ting_search/js/ting_search.js, modules/ting_search/js/ting_search_overlay.js, themes/ddbasic/sass/components/class.scss
This reverts changes in #849 and #934 because they failed testing.
=> Revert 2983

modules/ding_user/ding_user.module
Reverts ding2/ding2#368 as it failed user testing.
=> Revert "488 fix bad hashing"

modules/ding_loan/plugins/content_types/loans.inc
Reverts ding2/ding2#891 as it has not been user tested.
=> Revert "3078: Correct title when renewing multiple loans."

modules/ting/ting.field.inc
https://platform.dandigbib.org/issues/3286
=> 3286: Fixed material collection type

modules/ding_frontend/ding_frontend.module, modules/ting_search/ting_search.module
https://platform.dandigbib.org/issues/3270
=> 3270 by Inlead: Cardinality violation upon Search.

modules/ding_base/ding_base.module, themes/ddbasic/theme-settings.php
https://platform.dandigbib.org/issues/3289
=> 3289: Fix css color generator

drupal.make
https://platform.dandigbib.org/issues/3315
=> 3315: Update Drupal Core to 7.57

modules/opensearch/includes/opensearch.search.inc
See https://platform.dandigbib.org/issues/731
=> 731: Removed sorting on AcquisitionDate

modules/opensearch/includes/opensearch.search.inc, modules/ting/src/Search/TingSearchRequest.php
Added support for search for other facets than defined by ding_facetbrowser.
See https://platform.dandigbib.org/issues/3407
=> 3407: Support for setting facets in SAL

modules/fbs/fbs.features.field_base.inc, modules/fbs/fbs.features.field_instance.inc, modules/fbs/fbs.info, modules/fbs/includes/fbs.reservation.inc, themes/ddbasic/sass/components/form/form-user-profile.scss
https://platform.dandigbib.org/issues/3397
=> 3397: Fixed missing interest period

circle.yml
See https://platform.dandigbib.org/issues/3147
=> 3147: Remove Behat test artifacts from build

modules/ding_event/ding_event.field_group.inc, modules/ding_event/ding_event.views_default.inc, themes/ddbasic/sass/base/form.scss, themes/ddbasic/sass/components/panel/class-panel.scss, themes/ddbasic/templates/view/views-exposed-form--ding-event--ding-event-list.tpl.php
https://platform.dandigbib.org/issues/3349
=> 3349: Fixed event view labels and submit

modules/ding_availability/ding_availability.admin.inc
https://platform.dandigbib.org/issues/3402
The previous approach had been renamed and refactored.
Update surrounding documentation as well.
=> 3402: Fix submit handler for availability source and type config

ding2.make
Issue: https://platform.dandigbib.org/issues/3487
The version we are currently using is way being the latest so we
patch instead of updating.
=> 3487: Patch Media against SA-CONTRIB-2018-020

ding2.profile, modules/opensearch/opensearch.install, modules/opensearch/opensearch.module, translations/da.po
https://platform.dandigbib.org/issues/3534
=> 3534: Upgrade to opensearch 5.0

modules/ding_event/ding_event.strongarm.inc, modules/ding_news/ding_news.strongarm.inc
https://platform.dandigbib.org/issues/3536
=> 3536 by Inlead: Enable mobile flag per default.

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3538
=> 3538 by Inlead: Populating ticket link and event status from place2book.

modules/p2/ding_message/ding_message.install
https://platform.dandigbib.org/issues/3333
=> 3333: Drop list_id field, to change type

ding2.make, modules/ding_event/ding_event.field_group.inc
https://platform.dandigbib.org/issues/3466
=> 3466: Patch field_group and ctools

ding2.install
https://platform.dandigbib.org/issues/3565
=> 3565 by Inlead: Disable and uninstall ding_mobilesearch module.

ding2.profile
https://platform.dandigbib.org/issues/3572
=> 3572 by Inlead: Activate modules on clean installs.

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3538
=> 3538 by Inlead: Removing inefficient conditions.

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/include/functions.handler.inc, modules/p2/ding_list/include/functions.inc, modules/p2/ding_list/plugins/content_types/public_lists.inc
https://platform.dandigbib.org/issues/3333
=> OpenList - architecture update

modules/ting_infomedia/ting_infomedia.module
Update Infomedia service URL description to v. 1.4.
https://platform.dandigbib.org/issues/3383
=> 3383: Infomedia WS URL v. 1.4

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/js/ding_entity_rating.js
https://platform.dandigbib.org/issues/3463
=> 3463: Reset anonymous ratings if not logged in

modules/alma/includes/alma.user.inc, modules/ding_provider/connie/connie.user.inc, modules/ding_user/ding_user.module, modules/fbs/includes/fbs.user.inc, modules/openruth/includes/openruth.user.inc, modules/p2/ting_openlist/ting_openlist.module
https://platform.dandigbib.org/issues/3592
=> 3592: Openlist id

modules/ding_frontend/ding_frontend.module
https://platform.dandigbib.org/issues/3270
=> 3270 by Inlead: Extending list of escaped symbols.

themes/ddbasic/README.md, themes/ddbasic/gulpfile.js, themes/ddbasic/package.json
http://platform.dandigbib.org/issues/2578
=> 2578: DDBasic V2.0 Theme documentation

modules/p2/ding_list/ding_list.info
https://platform.dandigbib.org/issues/3731
=> 3731: Added panels dependency

modules/ding_app_content_rss/ding_app_content_rss.features.inc
See https://platform.dandigbib.org/issues/3735
=> 3735: Allow role "local editor" to set mobile flag

modules/fbs/fbs.module
See https://platform.dandigbib.org/issues/3615
=> 3615: Added resident information to fbs creds

modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.module, modules/ding_gatewayf/modules/ding_gatewayf_registration/templates/ding-gatewayf-registration-information.tpl.php, themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/panel/class-panel.scss
https://platform.dandigbib.org/issues/3485
=> 3485: Added style gatewayf link

themes/ddbasic/sass/configuration/_mixin.scss
https://platform.dandigbib.org/issues/3399
=> 3399: White arrow on buttons

modules/ding_debt/plugins/content_types/debts/debts.inc
https://platform.dandigbib.org/issues/2008
=> 2008: Fixed translation for Fee Date

ding2.info, ding2.install, ding2.make, ding2.profile, modules/ding_user/ding_user.module, modules/ding_user/plugins/content_types/profile2/profile2.inc, themes/ddbasic/templates/customerror.tpl.php
http://platform.dandigbib.org/issues/1549
=> 1549 by Inlead: Implement customerror module.

modules/ding_event/ding_event.views_default.inc
https://platform.dandigbib.org/issues/3563
=> 3563: Added autosubmit to events view

themes/ddbasic/sass/components/opening-hours.scss
https://platform.dandigbib.org/issues/3438
=> 3438: Styling of Opening hours notice

modules/p2/ding_interaction/plugins/content_types/interaction_pane.inc
See https://platform.dandigbib.org/issues/3381
=> 3381: Remember to include ui.widget

modules/p2/ding_list/plugins/content_types/list_menu.inc
https://platform.dandigbib.org/issues/3358
=>  Better user experience in connection with subscribing to (public) lists

modules/ding_content/ding_content.features.wysiwyg.inc, modules/ding_content/ding_content.info, themes/ddbasic/sass/wysiwyg.scss
https://platform.dandigbib.org/issues/3342
=> 3342: Added WYSIWYG styles to media

README.md, drupal.make
https://platform.dandigbib.org/issues/3335
=> 3335 by Inlead: Add Core patch to fix tablescroll.

themes/ddbasic/sass/components/header.scss, themes/ddbasic/sass/p2/p2-entity-buttons.scss, themes/ddbasic/scripts/menu.js
https://platform.dandigbib.org/issues/3320
=> 3320: Fixed p2-list covered by header

themes/ddbasic/sass/components/form/form-user-login.scss, themes/ddbasic/sass/components/panel/pane-user-login.scss
https://platform.dandigbib.org/issues/3301
=> 3301: Login on mobile

modules/ding_ipe_filter/css/ding_ipe_filter.css, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/3269
=> 3269 by Inlead: Review IPE implementation.

themes/ddbasic/sass/components/cookie.scss, themes/ddbasic/scripts/site.js, themes/ddbasic/templates/eu-cookie-compliance-popup-info.tpl.php
https://platform.dandigbib.org/issues/3268
=> 3268: Cookie notification fixed

themes/ddbasic/sass/components/form/form-user-profile.scss
https://platform.dandigbib.org/issues/3216
=> 3216: Fixed interest period

modules/ding_reservation/plugins/content_types/reservations/reservations.inc
https://platform.dandigbib.org/issues/3190
=> 3190: Sort by res-que and title

modules/ding_event/ding_event.features.field_base.inc, modules/ding_event/ding_event.features.field_instance.inc, modules/ding_event/ding_event.strongarm.inc
https://platform.dandigbib.org/issues/3144
=> 3144: Show to date on ding_event full

themes/ddbasic/sass/components/node/event.scss
https://platform.dandigbib.org/issues/3139
=> 3139: Changed event book button color

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.admin.inc, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc, themes/ddbasic/sass/components/node/library.scss, themes/ddbasic/scripts/ddbasic.common.js
https://platform.dandigbib.org/issues/3109
=> 3109: Opening hours expand options

ding2.make
https://platform.dandigbib.org/issues/3077
=> 3077: Update media_vimeo to 2.1 to allow https

modules/ding_ddbasic/ding_ddbasic.module
https://platform.dandigbib.org/issues/3059
=> 3059: Force color scheme to custom

themes/ddbasic/sass/components/menu.scss
https://platform.dandigbib.org/issues/3058
=> 3058: Fixed menu color

ding2.make
https://platform.dandigbib.org/issues/2376
=> 2376: Update message contrib module

themes/ddbasic/template.php
https://platform.dandigbib.org/issues/281
=> 281: Added alt attribute to read more

modules/ding_library/ding_library.views_default.inc
https://platform.dandigbib.org/issues/3310
=> 3110: Library list dependant on nodequeue

modules/fbs/fbs.module
=> 3043: Validate user on hold date

modules/p2/ding_list/src/DingList.php, modules/p2/ding_list/theme/theme.inc, modules/p2/ting_openlist/ting_openlist.handler.inc
https://platform.dandigbib.org/issues/3467
=> 3467: List pager

modules/ting_field_search/plugins/ting_field_search_ctools_export_ui.class.php, modules/ting_field_search/plugins/ting_field_search_ctools_export_ui.inc, modules/ting_field_search/ting_field_search.admin.inc, modules/ting_field_search/ting_field_search.facets.inc, modules/ting_field_search/ting_field_search.install, modules/ting_field_search/ting_field_search.module, modules/ting_field_search/ting_field_search.ting_field_search_default_profiles.inc, themes/ddbasic/sass/base/standard.scss, themes/ddbasic/template.php
Extension to field search to allow grouping of profiles and define which should be available on which pages.
See https://platform.dandigbib.org/issues/3236
=> 3236: Added search field profile filters

ding2.make
https://platform.dandigbib.org/issues/3487
=> 3487: Fix typo causing media patch to fail

modules/ding_provider/ding_provider.module
https://platform.dandigbib.org/issues/3695
=> 3695: Fix issue with automatic deletion of provider users

modules/p2/ding_list/include/functions.handler.inc
https://platform.dandigbib.org/issues/3749
=> 3749: Check list exists in get list

modules/p2/ding_message/ding_message.module
https://platform.dandigbib.org/issues/3706
=> 3706: Dont check false collections

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3755
=> 3755 by Inlead: Re-implement changes from #1096 (issue 3538).

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.module, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc, themes/ddbasic/template.node.php, themes/ddbasic/templates/node--ding-library.tpl.php
See https://platform.dandigbib.org/issues/3046
=> Issue 3046: opning hours - close days

modules/ding_tabroll/README.md, modules/ding_tabroll/ding_tabroll.module, modules/ding_tabroll/js/ding_tabroll.js, modules/ding_tabroll/js/jquery-ui-tabs-rotate.js
http://platform.dandigbib.org/issues/691
=> 691 by Inlead: Setting to control Tabroll speed.

modules/ding_place2book/ding_place2book.install, modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3704
=> 3704 by Inlead: Update events with missing p2b data.

modules/ding_place2book/ding_place2book.install, modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3704
=> 3704 by Inlead: Tiny typo of great importance.

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/templates/ding-list-add-button.tpl.php, modules/p2/ding_list/theme/theme.inc, tests/behat/features/03-searching-object.feature, tests/behat/features/bootstrap/LibContext.php, tests/behat/features/bootstrap/Page/ObjectPage.php, themes/ddbasic/sass/p2/p2-entity-buttons.scss
https://platform.dandigbib.org/issues/3684
=> 3684: Show add to lists for anonymous users

modules/p2/ding_list/plugins/content_types/list_menu.inc
https://platform.dandigbib.org/issues/3818
=> 3818: Fix missing bundle

modules/fbs/fbs.module
=> 3043: Fixed form validation profile2

modules/p2/ding_list/ding_list.module
https://platform.dandigbib.org/issues/3801
=> 3801: Add missing use for DingListElement

modules/p2/ding_entity_rating/js/ding_entity_rating.js
https://platform.dandigbib.org/issues/3817
=> 3817: Dont get rating on anon

modules/p2/ding_list/theme/theme.inc
https://platform.dandigbib.org/issues/3264
=> 3264: Changed missing item text

ding2.install, modules/ding_mobilesearch/README.md, modules/ding_mobilesearch/ding_mobilesearch.api.php, modules/ding_mobilesearch/ding_mobilesearch.info, modules/ding_mobilesearch/ding_mobilesearch.install, modules/ding_mobilesearch/ding_mobilesearch.module, modules/ding_mobilesearch/includes/admin.inc, modules/ding_mobilesearch/includes/trigger.inc, modules/ding_mobilesearch/lib/NationalStorageComponent/GenericStorage.class.inc, modules/ding_mobilesearch/lib/NationalStorageComponent/NationalStorage.class.inc, modules/ding_mobilesearch/lib/bootstrap.inc, modules/ding_mobilesearch/plugins/rest.inc
Reverts ding2/ding2#1101 and ding2/ding2#1102
=> Revert 3581 and 3565.

themes/ddbasic/scripts/ting-object/ting-object.js
https://platform.dandigbib.org/issues/3187
=> 3187: Fix hover order of ting objects

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.module, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc, themes/ddbasic/template.node.php, themes/ddbasic/templates/node--ding-library.tpl.php
https://platform.dandigbib.org/issues/3046
This reverts commit 475ab59d1f16c54b33a2440688906eb6283c81b5, reversing
changes made to 90c76de0f20b02bdad90301dc7615e219bafe662 as requested by the business.
=> 3046: Revert #881

themes/ddbasic/sass/components/class.scss, themes/ddbasic/sass/components/form/form-user-login.scss
https://platform.dandigbib.org/issues/3059
=> 3059: Login button colors

modules/ding_news/ding_news.views_default.inc
https://platform.dandigbib.org/issues/3472
=> 3472: Added autosubmit news_list

modules/p2/ding_list/plugins/content_types/list_menu.inc
https://platform.dandigbib.org/issues/3818
=> 3818: Check for list context

modules/fbs/fbs.module
https://platform.dandigbib.org/issues/3611
=> 3611: Validate german phone numbers

modules/ding_event/ding_event.features.field_instance.inc, modules/ding_event/ding_event.field_group.inc, modules/ding_event/ding_event.info, themes/ddbasic/template.node.php, themes/ddbasic/templates/node/node--ding-event--view-mode--teaser.tpl.php
https://platform.dandigbib.org/issues/3302
=> 3302: Changed display of room/organizers

ding2.install, modules/ding_ddbasic/ding_ddbasic.module
https://platform.dandigbib.org/issues/3057
=> Expand menu items

ding2_v4.vcl
This PR adds a configuration file for varnish 4.0 that can be used with DDB CMS.
See https://platform.dandigbib.org/issues/3105
=> 3105: Varnish 4 vcl file

modules/fbs/fbs.module
Reverts ding2/ding2#580
Phone number validation is now handled by change in #1128.
=> Revert "813: Validate phone number"

modules/fbs/fbs.module
=> 3043: Fixed on hold date validation

modules/p2/ding_message/ding_message.module
https://platform.dandigbib.org/issues/2376
=> 2376: Check users with no previous message checks

ding2.install, translations/da.po
Update translations with latest changes.
=> Core: Translation update

modules/fbs/fbs.module
=> 3043: Fixed error fbs validation on_hold

drupal.make
https://platform.dandigbib.org/issues/3899
Updatet Drupal core to 7.60
None
No comments
=> 3899: Update Drupal core to 7.60

modules/p2/ding_list/ding_list.module, modules/p2/ding_list/js/ding-list-private-sharer.js, modules/ting_infomedia/includes/ting_infomedia.wrapper.inc, modules/ting_infomedia/ting_infomedia.module
https://platform.dandigbib.org/issues/3896
Better handling of exceptions in the informedia module when access is denied.
__Before__:
__After__:
No comments
=> 3896: Error handling in informedia module

modules/p2/ding_list/include/form.inc, modules/p2/ding_list/include/functions.inc
https://platform.dandigbib.org/issues/3830
=> 3830: Add not_public checkbox to list edit

docs/search-abstraction-layer.md, modules/ding_provider/connie_search/src/ConnieSearchResult.php, modules/opensearch/src/OpenSearchTingSearchResult.php, modules/p2/ding_message/ding_message.module, modules/p2/ding_serendipity/ding_serendipity.module, modules/ting/src/Search/NullSearchResult.php, modules/ting/src/Search/TingSearchResultInterface.php, modules/ting_new_materials/plugins/content_types/new_materials.inc, modules/ting_search/plugins/content_types/ting_search.inc, modules/ting_search/ting_search.module
https://platform.dandigbib.org/issues/3804
Rename method as described in the issue.
=> 3804: Rename getNumTotalCollections to getNumCollections

modules/p2/ding_list/ding_list.features.field_instance.inc, modules/p2/ding_list/ding_list.info, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/ding_list.pages_default.inc, modules/p2/ding_list/include/form.inc, modules/p2/ding_list/plugins/access/reset_lists.inc, modules/p2/ding_list/plugins/content_types/lists.inc, modules/p2/ding_list/plugins/content_types/reset_user_lists.inc, modules/p2/ting_openlist/ting_openlist.handler.inc
https://platform.dandigbib.org/issues/2480
=> Reset user lists

modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/1491
=> 1491: Validate pincode on provider profile form

modules/p2/ding_serendipity/ding_serendipity.module, modules/p2/ding_serendipity_fallback/ding_serendipity_fallback.module
https://platform.dandigbib.org/issues/3795
=> 3795: Added limit to serendipity fallback search

modules/opensearch/src/OpenSearchTingObject.php, modules/ting/src/TingObject.php, modules/ting/src/TingObjectInterface.php, modules/ting_material_details/ting_material_details.field.inc
https://platform.dandigbib.org/issues/3794
=> 3794 by Inlead: Fix misspelling of genre.

modules/ding_ting_frontend/ding_ting_frontend.features.field_base.inc, modules/ding_ting_frontend/ding_ting_frontend.features.field_instance.inc, modules/ding_ting_frontend/ding_ting_frontend.info, modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc
https://platform.dandigbib.org/issues/3915
Added campaign plus panel pane to object view panel. So basically a feature re-export of ding_ting_frontend.
No screenshot.
No comments
=> 3915: Added campaign plus to object view panel

modules/bpi/bpi.syndicate.inc, modules/bpi/css/bpi-admin.styles.css
https://platform.dandigbib.org/issues/3642
Make filters fieldset open by default. Also hide the logical operator filter which internally is now default to an `and`.
=> 3642 by Inlead: Sanitize facets.

modules/alma/includes/alma.user.inc, modules/ding_gatewayf/modules/ding_gatewayf_registration/ding_gatewayf_registration.module, modules/ding_provider/ding_provider.exceptions.inc, modules/ding_provider/ding_provider.loan.inc, modules/ding_provider/ding_provider.module, modules/ding_provider/ding_provider.reservation.inc, modules/ding_provider/ding_provider.user.inc, modules/ding_reservation/ding_reservation.module, modules/ding_user/ding_user.module, modules/ding_user/plugins/content_types/profile2/profile2.inc, modules/fbs/includes/fbs.reservation.inc, modules/fbs/includes/fbs.user.inc, modules/fbs/tests/DebtProviderTest.php, modules/fbs/tests/FlowDebtTest.php, modules/fbs/tests/FlowLoantest.php, modules/fbs/tests/LoanProviderTest.php, modules/openruth/includes/openruth.reservation.inc
Clean up authentication and ensure the right messages is displayed.
=> 1261: block statuses

modules/ding_campaign_plus/modules/ding_campaign_plus_facet/ding_campaign_plus_facet.module
https://platform.dandigbib.org/issues/3918
Updated URL to explanation of the different facets that can be used in campaign plus as triggers.
No screenshot
No comments
=> 3918: Updated url to facet explanation in campaign UI

modules/ding_contact/ding_contact.module
https://platform.dandigbib.org/issues/3860
Changes the mail headers in order site's email settings are used.
=> 3860 by Inlead: Change contact form to use Site mail settings.

modules/ding_content/ding_content.pages_default.inc, modules/ding_eresource/ding_eresource.pages_default.inc, modules/ding_event/ding_event.pages_default.inc, modules/ding_frontpage/ding_frontpage.pages_default.inc, modules/ding_groups/ding_groups.pages_default.inc, modules/ding_library/ding_library.pages_default.inc, modules/ding_news/ding_news.pages_default.inc, modules/ding_page/ding_page.pages_default.inc
https://platform.dandigbib.org/issues/3957
Try to lazy load as many campaign as possible using lazy pane.
No screenshot
No comments
=> 3957: Added lazy pane to campaign plus

modules/ding_carousel/js/ding_carousel.js, modules/ting_search_carousel/plugins/content_types/carousel.inc, modules/ting_search_carousel/ting_search_carousel.module, modules/ting_search_carousel/ting_search_carousel.pages.inc
https://platform.dandigbib.org/issues/3465
Adds sorting option to carousels.
Depends on https://github.com/ding2/ding2/pull/1233. (should be rebased when that's merged)
=> 3465: sort carousels

modules/ting_field_search/plugins/ting_field_search_ctools_export_ui.inc, modules/ting_field_search/ting_field_search.module, modules/ting_search/ting_search.module, themes/ddbasic/template.php
https://platform.dandigbib.org/issues/3305
=> 3305 by Inlead: Add node search to ting_field_search.

modules/ding_campaign_plus/modules/ding_campaign_plus_facet/ding_campaign_plus_facet.module
See https://platform.dandigbib.org/issues/3918
Change an URL in help text for a field description.
No screenshot.
No comments.
=> 3918: Updated link to data well facet description

ding2.make
https://platform.dandigbib.org/issues/3982
Currently displaying the content listing can result in very long
query times causing the page to load very slowly or even time out.
The culprit seems to be the count query which Views makes to
determine how many results there are in total to render a pager.
```sql
SELECT
COUNT(*) AS expression
FROM (SELECT DISTINCT
node.nid AS nid,
node.title AS node_title,
node.language AS node_language,
history.timestamp AS history_timestamp,
node.created AS node_created,
node.changed AS node_changed,
node.type AS node_type,
users_node.name AS users_node_name,
users_node.uid AS users_node_uid,
node.status AS node_status,
workflow_node_current.sid AS workflow_node_current_sid,
1 AS expression
FROM node node
LEFT JOIN users users_node
ON node.uid = users_node.uid …
```
=> 3982: Speed up admin/content view by adding workflow node index

modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc
https://platform.dandigbib.org/issues/3983
Reorders panes on search page. Also removes a deleted pane
...
=> 3983 search page reorg

themes/ddbasic/sass/base/standard.scss, themes/ddbasic/sass/components/header.scss, themes/ddbasic/scripts/menu.js
This actually builds ontop of https://github.com/ding2/ding2/pull/1345
It adds the extra commit 5a4de3f which fixes issues where there are too many links in the menu.
=> 3667 menu search dropdown multiline

themes/ddbasic/scripts/menu.js
=> 3667: Make mainmenu multiline check even more specific.

ding2.make
https://platform.dandigbib.org/issues/4174
This fixes security vulnerability https://www.drupal.org/sa-contrib-2019-020
=> 4174: Upgrade Link module to 1.6

ding2.make
https://platform.dandigbib.org/issues/4188
This protects against https://www.drupal.org/sa-contrib-2019-026.
=> 4188: Upgrade services module to 3.22.

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://platform.dandigbib.org/issues/4173
Re-exported the default Section panel variant with the new required panel as per defined in the issue.
=> 4173 by Inlead: Re-export Section panel template.

modules/ding_nodelist/templates/ding_nodelist.ding_event.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_page.rolltab.tpl.php, modules/ding_tabroll/templates/views-view-fields--ding-tabroll.tpl.php, modules/ding_tabroll/templates/views-view-unformatted--ding-tabroll.tpl.php, themes/ddbasic/sass/components/ding-tabroll.scss, themes/ddbasic/templates/node/node--ding-event--view-mode--teaser.tpl.php
https://platform.dandigbib.org/issues/4097
These are minor fixes which makes the W3C HTML Validator happy
=> 4097: W3C Invalid syntax fixes

themes/ddbasic/templates/panel/pane-header.tpl.php
https://platform.dandigbib.org/issues/4080
To help screenreaders, an empty alt tag is required.
=> 4080: Add empty alt tag on logo, for WCAG.

ding2.install, translations/da.po
https://platform.dandigbib.org/issues/4052
The message "Your account is limited due to outstanding debt. Please contact your library for more information." is shown both on Danish and English.
=> 4052 by Inlead: String shown both on Danish and English.

modules/ding_app_content_rss/ding_app_content_rss.module, modules/ding_app_content_rss/ding_app_content_rss.views_default.inc
https://platform.dandigbib.org/issues/3951
This commit contain changes and features export which adds Event CT "Place/Room" and  "Organizer" fields to Ding App Content RSS feed.
=> 3951 by Inlead: Add more metadata to RSS feed.

ding2.install, themes/ddbasic/template.node.php, translations/da.po
https://platform.dandigbib.org/issues/3350
=> 3350: Changed labels search-result

themes/ddbasic/sass/base/form.scss, themes/ddbasic/sass/components/ding-carousel.scss, themes/ddbasic/sass/components/form/form-search-sort.scss, themes/ddbasic/sass/components/ting-object/ting-object.scss, themes/ddbasic/sass/configuration/_mixin.scss
https://platform.dandigbib.org/issues/4093
Generally just better styling for focus, such as keyboard focus.
=> 4093: Better general focus styling on the site.

modules/p2/ding_list/ding_list.info, modules/p2/ding_list/ding_list.module, modules/p2/ding_list/ding_list.pages_default.inc, modules/p2/ding_list/plugins/content_types/list_data.inc, modules/p2/ding_list/plugins/content_types/list_info.inc, modules/p2/ding_list/plugins/content_types/list_menu.inc, modules/p2/ding_list/plugins/content_types/private_share.inc, modules/p2/ding_list/src/DingList.php, modules/p2/ding_list/templates/ding-list-data.tpl.php, modules/p2/ding_list/theme/theme.inc, modules/p2/ding_sharer/ding_sharer.module, modules/p2/ding_sharer/plugins/content_types/sharer_pane.inc, tests/behat/features/bootstrap/P2Context.php, tests/behat/features/bootstrap/Page/ListPage.php, themes/ddbasic/sass/components/ding-carousel.scss, themes/ddbasic/sass/p2/p2-class-panel.scss, themes/ddbasic/sass/p2/p2-class.scss, themes/ddbasic/sass/p2/p2-list.scss, themes/ddbasic/templates/panel/panels-pane--list-info.tpl.php
https://platform.dandigbib.org/issues/2697
This reintroduces changes from ding2/ding2#1445, which had previously been reverted because of test failures.
This PR also contains the necessary updates to the codebase and tests to make them pass again. Please check out the individual commit comments for more details.
Scrutinizer comments are replicated from `panel-pane.tpl.php`. I think they should be disregarded.
=> Revert "Revert "2697: Remake ding lists""

ding2.make
https://platform.dandigbib.org/issues/4215
Security update of the views contrib module.
No screenshot
No comments
=> 4215: Updated views module

ding2.make
https://platform.dandigbib.org/issues/4255
This addresses security vulnerability
https://www.drupal.org/sa-contrib-2019-043
=> 4255: Update Services module to 3.24

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/4394
This is an alternative solution to the one presented in: #1476 
Handles cloned nodes with p2b sync using hook_clone_node_alter(). Need to make sure that the cloned node doesn't reference the same event and prices in p2b API.
The node clone module supports two different methods of cloning and we need to handle them differently:
- **prepopulate**: In this mode the node clone is populated but not saved before showing the widget form. In this case we need to tell the widget form that it should use the cloned event and prices that we passed from alter instead of trying to fetch event and prices from p2b API
- **save-edit**: In this mode node clone is saved before showing the form. In this case we need to simulate the items array passed to our field …
=> 4394: Handle cloned nodes with p2b sync using node clone API

drupal.make
https://platform.dandigbib.org/issues/4363
Removed not needed patches and updated core version. Also changed from using ssh to https to enable clone inside docker container on non Linux boxes.
Non
Non
=> 4363: Updated Drupal makefile

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module
https://platform.dandigbib.org/issues/4147
Add ding campaign plus to IPE filter to allow usages in sections.
No screenshot
No comment
=> 4147: Added campaign plus to IPE filter

modules/ding_place2book/ding_place2book.module, themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/4257
- Green ticket-buttons have white underlined text
- Waiting list buttons are now yellow instead of green
- Non-P2b ticket-buttons are now looking like P2b ticket-buttons (green coloured)
- Complete P2b ticket-button is now clickable
- Ticket sale start date and time is shown inside button
=> 4257 by Inlead: Various layout optimizations for ticket buttons.

themes/ddbasic/template.node.php
https://platform.dandigbib.org/issues/4094
Fixes comment:
https://github.com/ding2/ding2/pull/1442#discussion_r299023667
=> 4094: Use correct langcode

modules/ding_frontend/plugins/layouts/site_template/ding2-site-template.tpl.php, themes/ddbasic/templates/panel-layout/ding2-site-template.tpl.php
https://platform.dandigbib.org/issues/4091
Fixes an issue with SEO / accesability.
=> 4091: Add role=main to main content divs.

modules/p2/ding_list/include/form.inc, modules/p2/ding_list/theme/theme.inc
https://platform.dandigbib.org/issues/2697
Removed option to share list for all others than the list owner.
On follow list event - replace the follow form with unfollow form ajax.
=> 2697: List follow alterations

modules/ding_adgangsplatformen/ding_adgangsplatformen.module
https://platform.dandigbib.org/issues/4565
Fix issue with DBC deployment and php 5.6
No screenshot.
No comments
=> 4565: Fixed issues with php7 vs 5.6

modules/ding_webtrekk/ding_webtrekk.js
https://platform.dandigbib.org/issues/4570
Minor code style changes made during JS debug.
No screenshot.
There is no changes in the code, only code style.
=> 4570: JS code style in webtrekk

ding2.install, translations/da.po
No issue for this change.
Update our translations.
=> Core: Update translations

modules/bpi/bpi.images.inc, modules/bpi/bpi.module
=> Revert "4625 by Inlead: Adopt with recent service changes."

.circleci/config.yml, ding2.profile, modules/opensearch/opensearch.install, modules/opensearch/opensearch.module
https://platform.dandigbib.org/issues/4512
Ensure the latest version of opensearch is used on existing installations and as defaulf value on fresh installs.
Also updated the version used in install parameter in circle config,
=> 4512: Update Open Search version to 5.2

ding2.install, modules/ding_registration/ding_registration.module
https://platform.dandigbib.org/issues/4642
- Enable ding_registration module for existing sites
- Fix ding_registration settings url
- Fix idp name in url
=> 4642: Ding registration fixes

modules/ding_user_frontend/ding_user_frontend.module
https://platform.dandigbib.org/issues/4610
Remove request new password. The functionality makes it possible to check if a given email address
is used by an account. We can't leak that information.
=> 4610: Remove request new password

ding2.make
https://platform.dandigbib.org/issues/4624
Upgrades admin_views to newest version fixing security issue.
=> 4624: Upgrade admin_views

ding2.make
https://platform.dandigbib.org/issues/4623
Upgrade nodequeue to latest version fixing security issue.
=> 4623: Upgrade nodequeue

themes/ddbasic/sass/base/standard.scss, themes/ddbasic/sass/components/node/event.scss, themes/ddbasic/sass/components/node/news.scss, themes/ddbasic/sass/configuration/_typography.scss
https://platform.dandigbib.org/issues/4193
Tries to fix up the h2/h3 styling.
=> 4193 headline styling

modules/ding_campaign_plus/ding_campaign_plus.drush.inc, modules/ding_campaign_plus/ding_campaign_plus.module, modules/ding_campaign_plus/modules/ding_campaign_plus_facet/ding_campaign_plus_facet.module
https://platform.dandigbib.org/issues/4581
Added drush function to test campaign plus validation for a given campaign (help in debugging).
Changed validation function for campaign facet validation mails.
No screenshot.
No comments
=> 4581: Fixed search query in campaign facet validation

modules/ding_loan/plugins/content_types/loans.inc, translations/da.po
https://platform.dandigbib.org/issues/3290
Follow up to: #1589
Add links in the translation strings and add default translations.
=> 3290: Overdue loans empty - follow up

project-core.make
https://platform.dandigbib.org/issues/4829
Drupal 7 has an Open Redirect vulnerability. For example, a user could be tricked into visiting a specially crafted link which would redirect them to an arbitrary external URL.
- [x ] My complies with [our coding guidelines](../docs/code_guidelines.md).
=> bug4829: Update Drupal core to 7.70

modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/4580
Webtrekk was using gatewayf code that have been removed from the code base.
No screenshot.
No comments
=> 4580: Updated webtrekk to adgangsplatformen

project-core.make
None - yet.
Core: Update Drupal Core to 7.72
This addresses https://www.drupal.org/sa-core-2020-004
=> Core: Update Drupal Core to 7.72

modules/ding_react/plugins/content_types/related_materials.inc
https://platform.dandigbib.org/issues/4886
Limit related materials to ones available at the local library.
Depends on https://github.com/danskernesdigitalebibliotek/ddb-react/pull/109 being merged.
=> 4886: Limit related materials to those available at the local library

modules/ding_base/ding_base.module, modules/ding_contact/ding_contact.module
https://platform.dandigbib.org/issues/4906
Need to update the source text to be able to roll out a new standard translation.
=> 4906: Update privacy notice on contact form and webforms

modules/ding_registration/includes/ding_registration.acceptance.inc, modules/ding_user/ding_user.install, modules/ding_user/ding_user.module, modules/ding_user_form/ding_user_form.module
https://platform.dandigbib.org/issues/4429
Allow for configuring maximum and minimun pincode lengths.
=> 4429: Allow for variable length pincodes

modules/bpi/bpi.syndicate.inc, modules/bpi/css/bpi-admin.styles.css
https://platform.dandigbib.org/issues/4436
Display various top ranked lists regarding syndication and push activity.
Null.
=> 4436 by Inlead: Display top ranking.

modules/ding_page/ding_page.features.field_base.inc, modules/ding_page/ding_page.features.field_instance.inc
https://platform.dandigbib.org/issues/4325
Configure crop for list image on ding_page.
=> Configure cropping for page list image

themes/ddbasic/ddbasic.info, themes/ddbasic/sass/components/links.scss
https://platform.dandigbib.org/issues/4810
Add underline to body links
=> 4810: Add underline to body links

modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/js/node_blocks.js, modules/ding_nodelist/plugins/content_types/ding_nodelist.inc, modules/ding_tabroll/ding_tabroll.module
https://platform.dandigbib.org/issues/4983
Fix event display.
=> 4983 more bugfixes

modules/ding_sections/ding_sections.install, modules/ding_sections/ding_sections.module, themes/ddbasic/sass/components/view/view.scss
https://platform.dandigbib.org/issues/4241
Fix tablet view of sections, add spacing between sections in mobile view, and configure cropping for section images. Also remove some code that did absolutely nothing.
Before:
After:
=> 4241 fixes

modules/ting_subsearch/ting_subsearch_bibdk/ting_subsearch_bibdk.admin.inc, modules/ting_subsearch/ting_subsearch_bibdk/ting_subsearch_bibdk.module, modules/ting_subsearch/ting_subsearch_suggestions/plugins/content_types/ting_subsearch_suggestions.inc, modules/ting_subsearch/ting_subsearch_suggestions/ting_subsearch_suggestions.admin.inc, modules/ting_subsearch/ting_subsearch_suggestions/ting_subsearch_suggestions.module, modules/ting_subsearch/ting_subsearch_translate/plugins/content_types/ting_subsearch_translate.inc, modules/ting_subsearch/ting_subsearch_translate/ting_subsearch_translate.admin.inc, modules/ting_subsearch/ting_subsearch_translate/ting_subsearch_translate.module
https://platform.dandigbib.org/issues/4985
Provide better default values for subsearch triggers.
=> 4985: Provide better default values for subsearch triggers

modules/fbs/includes/fbs.reservation.inc
https://platform.dandigbib.org/issues/5000
Filter out excluded branches when checking availability.
=> 5000: reservation branches

.circleci/config.yml, tests/behat/composer.json, tests/behat/composer.lock
https://platform.dandigbib.org/issues/4986
Upgrade to Composer 2
=> 4986 composer 2

project-core.make
https://platform.dandigbib.org/issues/5006
Update Drupal Core to 7.75 to addresses https://www.drupal.org/sa-core-2020-013.
=> 5006: Update Drupal Core to 7.75

modules/ting_subsearch/ting_subsearch.module
https://platform.dandigbib.org/issues/5030
Fix a typo in ting_subsearch hook_permission implementation.
=> 5030: Fix subsearch permissions

project-core.make
https://platform.dandigbib.org/issues/5049
This addresses [SA-CORE-2021-001](https://www.drupal.org/sa-core-2021-001).
=> 5049: Update Drupal Core to 7.78

themes/ddbasic/sass/components/links.scss
https://platform.dandigbib.org/issues/5078
Persist link underline on hover
=> 5078: Persist link underline on hover

modules/ting_smart_search/includes/ting_smart_search.admin.inc, modules/ting_smart_search/ting_smart_search.module
https://platform.dandigbib.org/issues/4869
Exposes smart search records as a json array.
=> 4869: Expose smart search records

modules/fbs/includes/fbs.availability.inc
See https://platform.dandigbib.org/issues/3019
=> 3019: Sorting holdsing based on library placement

modules/ding_entity/ding_entity.module, modules/ting_das/css/ting_das.css, modules/ting_das/includes/ting_das.admin.inc, modules/ting_das/includes/ting_das.client.inc, modules/ting_das/ting_das.info, modules/ting_das/ting_das.install, modules/ting_das/ting_das.module
See https://platform.dandigbib.org/issues/2175
Support for placing copies at digital article service at the the danish royal library. The service is un-documented but an agreement to test the service by a group of libraries have been accepted.
The service was create long ago for use by bib.dk only.
It adds an "Order digital copy" button to articles that don't already has an "See online" button and if the user is logged in the button is only displayed for users that is resident in the municipality (sa this is another limitation of the condition of usage).
Also note that an requirement (if possible) was that the module use be usable without any other core changes.
No screenshot.
No comments.
=> 2175: Guldknap (ting_das)

modules/ding_user/ding_user.module
https://platform.dandigbib.org/issues/4878
Only allow to send copy on contact form if user is logged in.
=> 4878: Contact form send copy spam

themes/ddbasic/template.php, themes/ddbasic/templates/view/views-exposed-form--ding-event--ding-event-list.tpl.php
https://platform.dandigbib.org/issues/4085
Fix event list exposed views form to make it accessible.
=> 4085: Added modified exposed form for events

modules/ding_react/ding_react.module, modules/ding_react/js/ding-react.js, modules/ding_react/js/ding-react.reset.js, project.make
**Do not merge while temporary builds of React components are included!**
https://platform.dandigbib.org/issues/4497
This PR contains a few more fixes in relation to Redux handling.
Please check the commit comments for additional detail.
This PR depends on danskernesdigitalebibliotek/ddb-react#138.
=> 4497: More changes to Redux handling

modules/ding_user_frontend/plugins/content_types/user_overview.inc
https://platform.dandigbib.org/issues/5237
Fix debt count on `user/me/view` by using `ding_debt_count()` which accounts for hidden debts, rather than just counting the list.
=> 5237 debt count

modules/ding_frontend/ding_frontend.pages_default.inc, modules/ding_user_form/js/ding_user_form.js, modules/ding_user_frontend/ding_user_frontend.module, themes/ddbasic/scripts/menu.js
https://platform.dandigbib.org/issues/5178
1. Every time an ajax request fires a new click event handler is attached to links/buttons resulting in the samme handler being fire on click x times and if the handler `toggles` some thing and the number of ajax request are odd... the effect will be that click handler do not do anything.
2. The user information (sub-menu) header sometimes just show a spinner and newer gets loaded. Changing lazy pane to load on page load and not on page scroll for the header element fixes this.
3. Change reuse of $item variabel inside loops in user menu tree build
No screenshot
No comments
=> 5178: JavaScript fixes

modules/ding_react/ding_react.install, modules/ding_react/ding_react.module
https://platform.dandigbib.org/issues/5107
Removes the migration code from ding_react. Also removes the field we kept from ting_openlist.
=> 5107: Remove list/search migrations

project-core.make
https://platform.dandigbib.org/issues/5217
Security risk: Critical 15∕25 AC:Complex/A:User/CI:All/II:All/E:Theoretical/TD:Uncommon
Install the latest version:
If you are using Drupal 7, update to Drupal 7.82.
=> 5217: Update Drupal version to 7.82

modules/ding_react/ding_react.admin.inc, modules/ding_react/ding_react.install, modules/ding_react/ding_react.module, modules/ding_react/plugins/content_types/checklist.inc, modules/ding_react/plugins/content_types/related_materials.inc
https://platform.dandigbib.org/issues/5107
Removes the missed migration variable and admin. Includes some codestyle fixes for good meassure.
=> 5107 remove migration 2

modules/ding_registration/includes/ding_registration.acceptance.inc, modules/fbs/includes/fbs.user.inc
https://platform.dandigbib.org/issues/5092
The changes in #1813 and #1833. The changes do not work so the business has decided to roll them back.
=> 5092: Revert changes

modules/ting_das/css/ting_das.css, modules/ting_das/includes/ting_das.client.inc, modules/ting_das/ting_das.module
https://platform.dandigbib.org/issues/5292
Removed unnecessary fields from the request to das service
=> 5292: Removed unnecessary fields in das request

project-core.make
https://platform.dandigbib.org/issues/5325
[Drupal core - Moderately critical - Cross Site Scripting - SA-CORE-2022-001](https://www.drupal.org/sa-core-2022-001)
=> 5325: update Drupal to v7.86

modules/fbs/includes/fbs.availability.inc
(https://platform.dandigbib.org/issues/5312)
This pull request contains a small change to the fbs availability provider. This change is a prerequisite for an upcoming IMS-module that will modify the output of the fbs availability provider and add in detailed placement info acquired from IMS. The IMS-module will be developed as a stand alone module outside of ding2. 
The change has no visible result
=> 5312: Add itemNumber and available to result

modules/ding_debt_easy/ding_debt_easy.module
https://platform.dandigbib.org/issues/5117#change-55920
Fixed logic statement in switching between testing and live nets easy end points.
No screenhost
No comments
=> Fixed switching between test/live in nets easy integration

project.make
https://platform.dandigbib.org/issues/5355
This addresses https://www.drupal.org/sa-contrib-2022-031.
=> #5355: Update Role Delegation to 1.3

themes/ddbasic/sass/components/header.scss
https://platform.dandigbib.org/issues/5282#change-55245
Scrolling of mobile menu not working on Iphones.
=> 5282: Fixed mobilemenu scrolling on iphones

modules/ding_webtrekk/ding_webtrekk.js
https://platform.dandigbib.org/issues/5334
MWA event tracking the presence off cover on a object or collection page. We need to handle both covers loaded on page load and those who come with ajax calls. So both are handled in js.
=> 5334: Added handling of object and collection covers

modules/ding_reservation/ding_reservation.module, modules/ding_webtrekk/ding_webtrekk.js, modules/ding_webtrekk/ding_webtrekk.module
https://platform.dandigbib.org/issues/5354
Implements tracking off deleting reservations action in Mapp. Is based on similar implemenation off renew buttons action.
=> 5354 mwa delete reservervation

project-core.make
=> Revert "Core: Revert "5325: update Drupal to v7.86""

project-core.make
[
Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5325)
[Drupal core - Moderately critical - Cross Site Scripting - SA-CORE-2022-001](https://www.drupal.org/sa-core-2022-001)
Bumped Drupal to latest version (7.90)
=> 5325: update drupal to v7.90

modules/ding_debt_easy/ding_debt_easy.module, modules/ding_debt_easy_reports/ding_debt_easy_reports.module
https://platform.dandigbib.org/issues/5413
Format date and amount in easy mail report.
=> 5413 easy report formatting

ding2.install, translations/da.po
=> Core: Translation updates

modules/ding_content/templates/media-vimeo-video--cookieinformation.tpl.php, modules/ding_content/templates/media-youtube-video--cookieinformation.tpl.php
https://platform.dandigbib.org/issues/5448#
Changed data-category from cookie-cat-statistic to cookie-cat-marketing
=> 5448: Changed data-category
